### ISSUE TITLE
Remove obsolete UseGoogleAuthentication

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#10]
Google deprecated OpenId in favor of OAuth2. The old provider doesn't work anymore. 
https://developers.google.com/identity/sign-in/auth-migration#timetable 

Katana currently has OpenId and OAuth2 implementations. Remove the obsolete extension, handler, and options. Would it be worth renaming GoogleOAuth2AuthenticationOptions back to GoogleAuthenticationOptions? ASP.NET Core did.

https://katanaproject.codeplex.com/workitem/487

**Comment by slaneyrw** [comment]
Terminology - they have deprecated OAuth1 and OpenId **2.0**.  The current protocol is OpenId-Connect, not straight Auth2
