### ISSUE TITLE
Encoding in cookie

### ISSUE THREAD

**Issue by LordRhialto** [aspnet/AspNetKatana#106]
We are running Microsoft.Owin v3.1.0 and are still experiencing this problem:

`String identityCookie = Context.Request.Cookies[identityCookieName];`

returns a string value with base64 encoded data in it (here, only a part has been shown) `eKUiOV0mSV6Kzk 4G4R8w/sgh6BbO` instead of a space there should be a +.

See also: [https://github.com/aspnet/HttpAbstractions/issues/547](url)

**Comment by anurse** [comment]
Katana URL encodes cookie values to ensure that user-provided values work. As a result, we have to URL decode incoming values to support round-trip behavior. So this is by design.
