### ISSUE TITLE
Bug in MicrosoftAccountAuthenticatedContext

### ISSUE THREAD

**Issue by bsmithb2** [aspnet/AspNetKatana#107]
When attempting to log in using the Microsoft social providers, some accounts appear not to have email addresses. We've identified it usually being Personal accounts, and might be related to outlook.com or hotmail.com email addresses. 

This occurs due to a bug in the MicrosoftAccountAuthenticatedContext, which is incorrectly checking for null on a string value, rather then string.IsNullOrEmpty(). This was fixed by 737de41e3a689eb9157cdc3c99512b0973886f91 by @Tratcher in July. 

Just wondering when we can expect that code to drop into a preview or production? Is it worth manually hacking the provider to fix by stuffing the userPrincipalName into the claim manually? 

Thanks!

**Comment by Tratcher** [comment]
The preview is now available: https://www.nuget.org/packages/Microsoft.Owin.Security.MicrosoftAccount/4.0.0-alpha1
