### ISSUE TITLE
Supply an ICookieManager implementatoin for System.Web

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#11]
One of the most common issues hit by users is a conflict in the response cookie header that causes values to be dropped. See http://katanaproject.codeplex.com/wikipage?title=System.Web%20response%20cookie%20integration%20issues 

This can cause infinite auth loops and other hard to diagnose issues. While we can't directly solve the issue, we can provide helpers for the most common mitigation. This would involve taking the workaround code from the link above and adding it to the SystemWeb package where it could be easily referenced by apps.

We may also add ICookieManager to the other auth providers (e.g. OIDC, Facebook, etc.) as they set temporary cookies during the auth flow.

We'll need to update the wiki to show the new workaround.

**Comment by hobozero** [comment]
Hi Chris (@Tratcher),
Am I to understand that this addressed in [Katana 3.1 preview](https://github.com/aspnet/AspNetKatana/milestone/2?closed=1)?  I'm willing to add the workaround, cited above, but I'd otherwise like to keep it clean!
Cheers, Ty

**Comment by Tratcher** [comment]
Yes, you can use https://www.nuget.org/packages/Microsoft.Owin.Host.SystemWeb/3.1.0. Note you still have to plug the new SystemWebChunkingCookieManager into the CookieAuthenticationOptions as shown in the workaround.
https://github.com/aspnet/AspNetKatana/commit/49b78c0874587832e01ba8cad23d9ce8e4f78f19#diff-92b168b3f5222ace0406d683417c1fa1R75
