### ISSUE TITLE
Microsoft Account OAuth2 sign-on stop to work after update the Microsoft.Owin packages from v3.0.1 to v3.1.0

### ISSUE THREAD

**Issue by luronumen** [aspnet/AspNetKatana#112]
I have updated the following Nuget packages from **v3.0.1** to **v3.1.0**:

- Microsoft.Owin
- Microsoft.Owin.Host.SystemWeb
- Microsoft.Owin.Security
- Microsoft.Owin.Security.Cookies
- Microsoft.Owin.Security.Google
- Microsoft.Owin.Security.MicrosoftAccount

And after these updates the following issue is displayed when I try to authenticate using a Microsoft Account:

_Correlation ID: 1a411cc0-446c-42bb-8659-cdd7dd9e6199
AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope wl.emails is not valid._

Important notes:

- This issue is only happening when I try to use a Microsoft Account for authenticating and there is no issue when I use a Google or Facebook account for authenticating it
- When I do the downgrade for the **v3.0.1** the Microsoft Account authentication back to work again
-  This issue is still reproducible on **v4.0.0-alpha1** and the issues [#48](https://github.com/aspnet/AspNetKatana/pull/48) and [#89](https://github.com/aspnet/AspNetKatana/pull/89) did not fixed it

I have attached the [Startup.Auth.cs](https://github.com/aspnet/AspNetKatana/files/1281815/Startup.Auth.cs.txt) class from the System for your better debuging.

For more details you can also check the [ASP.NET MVC 5 - Microsoft Account OAuth2 sign-on stop to work after update the Microsoft.Owin packages from v3.0.1 to v3.1.0](https://forums.asp.net/t/2120757.aspx?ASP+NET+MVC+5+Microsoft+Account+OAuth2+sign+on+stop+to+work+after+update+the+Microsoft+Owin+packages+from+v3+0+1+to+v3+1+0)

**Comment by Tratcher** [comment]
In the 3.1 release all of the security packages were updated to use the latest APIs available from their respective providers. In this instance the MicrosoftAccount 3.0.1 package was using an obsolete API to authenticate users and was moved to a new API. The new API uses different values for Scope (https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-scopes). However, you don't need to specify any scopes to get the e-mail, you can remove that parameter.

There have been no changes to this behavior for 4.0.0. #48 was a separate issue.

**Comment by luronumen** [comment]
Hi @Tratcher 

Thank you very much for your prompt reply!
Based on it I could identify where is the issue:

================================

Scenario 1 (v3.1.0 + Scope = { "wl.emails" })
Fail - AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope wl.emails is not valid.

================================

Scenario 2 (v3.1.0 + without Scope)
Fail - System.NullReferenceException on System.Security.Claims.ClaimsPrincipal.Current.FindFirst(System.Security.Claims.ClaimTypes.Email).Value

================================

Scenario 3 (4.0.0-alpha1 + without Scope)
Pass!

================================

I other words, I have to use the 4.0.0-alpha1 without any Scope for continue able to read email info from the Microsoft Account.

Is there any plan for release the final 4.0.0 version soon?

Feel free for close this issue as dup of [#89](https://github.com/aspnet/AspNetKatana/pull/89)

**Comment by Tratcher** [comment]
Yes 4.0.0 will be out soon, we're just waiting for feedback.

**Comment by luronumen** [comment]
Thanks @Tratcher 

In other words, from now on, _GoogleOAuth2AuthenticationOptions_ and _MicrosoftAccountAuthenticationOptions_ do not need nothing more than _ClientId_ and _ClientSecret_ to the _System.Security.Claims.ClaimsPrincipal.Current.FindFirst(System.Security.Claims.ClaimTypes.Email).Value_ has the user email account info.

Is there any possibility of _FacebookAuthenticationOptions_ having similar behavior? Currently the **Fields = { "email" }, Scope = { "email" }** are required to the _System.Security.Claims.ClaimsPrincipal.Current.FindFirst(System.Security.Claims.ClaimTypes.Email).Value_
 is not empty


,

**Comment by Tratcher** [comment]
@luronumen That's a good idea. Can you open a new bug so we don't loose track of it?

**Comment by luronumen** [comment]
Sure @Tratcher!

I just open the issue #113 for traking it.

Besides Facebook do you think it would be possible to do something similar for Twitter as well?
- _app.UseTwitterAuthentication(new TwitterAuthenticationOptions { ConsumerKey = "MyConsumerKey", ConsumerSecret = "MyConsumerSecret" });_

I noticed you have work to simplify Twitter email account here: [#765](https://github.com/aspnet/Security/issues/765)

**Comment by Tratcher** [comment]
Twitter does not have it enabled by default because it has significant pre-req on their end. You have to contact support to enable it.

**Comment by luronumen** [comment]
I see. But I have set in my [Twitter Apps](https://apps.twitter.com/) the _Access level_ to **Read-only** and **Can request a user's email address** option as well.

Is there something more that I have to do to have the user email associated with the Twitter account through the _System.Security.Claims.ClaimsPrincipal.Current.FindFirst(System.Security.Claims.ClaimTypes.Email).Value_?

Using _app.UseTwitterAuthentication(new TwitterAuthenticationOptions { ConsumerKey = "MyConsumerKey", ConsumerSecret = "MyConsumerSecret" });_ is returning System.NullReferenceException when I try to read the user email info through _System.Security.Claims.ClaimsPrincipal.Current.FindFirst(System.Security.Claims.ClaimTypes.Email).Value_

**Comment by Tratcher** [comment]
You also need `RetrieveUserDetails = true`

**Comment by luronumen** [comment]
it does not working.
_app.UseTwitterAuthentication(new TwitterAuthenticationOptions { ConsumerKey = "MyConsumerKey", ConsumerSecret = "MyConsumerSecret", RetrieveUserDetails = true });_ is returning the following compilation issue:

_Error	CS0117	'TwitterAuthenticationOptions' does not contain a definition for 'RetrieveUserDetails'_

**Comment by Tratcher** [comment]
Sorry, I forgot which repo I was in. E-mail support was only added to ASP.NET Core. The hideous event code workaround should be similar for Katana. https://github.com/aspnet/Security/issues/765#issuecomment-206411817

**Comment by luronumen** [comment]
Thanks for the clarification @Tratcher 

Is there any possibility to design something similar for the _ASP.NET Framework_ by adding the _RetrieveUserDetails_ property on _TwitterAuthenticationOptions_ class as well?

Do you think it would be good we opened an issue for tracking it?

**Comment by Tratcher** [comment]
We're not planning significant feature work like this for Katana. Our current focus is bug fixes and keeping it up to date with external providers, dependencies, etc..

**Comment by luronumen** [comment]
I see. Okay then @Tratcher!

**Comment by yeimylorena** [comment]
4.0.0-Microsoft Account is compatible with Net framework 4.5.2?
