### ISSUE TITLE
Simplify the way to recover the user email associated with Facebook account

### ISSUE THREAD

**Issue by luronumen** [aspnet/AspNetKatana#113]
Currently to retrieve the user email associated with the Facebook account through the _System.Security.Claims.ClaimsPrincipal.Current.FindFirst(System.Security.Claims.ClaimTypes.Email).Value_ the developer needs to set **Fields = { "email" }, Scope = { "email" }** on _FacebookAuthenticationOptions_ object:
- _app.UseFacebookAuthentication(new FacebookAuthenticationOptions { AppId = "MyAppId", AppSecret = "MyAppSecret"**, Fields = { "email" }, Scope = { "email" }** });_

The proposal of this issue is to simplify the process of recovering the user email associated with the Facebook account for something similar to what already have on _GoogleOAuth2AuthenticationOptions_ and _MicrosoftAccountAuthenticationOptions_:

- _app.UseFacebookAuthentication(new FacebookAuthenticationOptions { AppId = "MyAppId", AppSecret = "MyAppSecret" });_
- _app.UseGoogleAuthentication(new GoogleOAuth2AuthenticationOptions { ClientId = "MyClientId", ClientSecret = "MyClientSecret" });_
- _app.UseMicrosoftAccountAuthentication(new MicrosoftAccountAuthenticationOptions { ClientId = "MyClientId", ClientSecret = "MyClientSecret" });_

**Comment by Tratcher** [comment]
Yes, we should consider enabling the email Field and Scope by default.

**Comment by luronumen** [comment]
Do you think we could have this issue fixed before the final 4.0.0 version @Tratcher?

**Comment by Tratcher** [comment]
Yes, we'll consider it for 4.0.0

**Comment by luronumen** [comment]
Thank you very much @Tratcher!

**Comment by Tratcher** [comment]
Note we do this for Core: https://github.com/aspnet/Security/blob/bd8ecd02684d490ece96c484e1092386f3515dec/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookOptions.cs#L30-L34
We also use hashsets to avoid duplicate scopes and fields.
