### ISSUE TITLE
Could your read "SecurityTokenServiceAddress" from property

### ISSUE THREAD

**Issue by JoyceLiang** [aspnet/AspNetKatana#114]
Hi,
Visual Studio now(15.5) support account from multiple-cloud (public cloud, blackforest(de), mooncake(cn), and so on).  When a user pass his blackforest tenant and audience use below api, he'll get a 400 response, from the fiddler trace, the request is send to "https://login.windows.net" , and this value is hard coded in [WindowsAzureActiveDirectoryBearerAuthenticationExtensions.cs](https://github.com/aspnet/AspNetKatana/blob/5d58dab237663b694515a3adbb36dd246a7d4ca2/src/Microsoft.Owin.Security.ActiveDirectory/WindowsAzureActiveDirectoryBearerAuthenticationExtensions.cs) 

Could you change your API, and let user set the uri from outside.

`public void ConfigureAuth(IAppBuilder app)
        {
            app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidAudience = ConfigurationManager.AppSettings["ida:Audience"]
                    },
                });
        }`

**Comment by Tratcher** [comment]
You can set the MetadataAddress directly.
https://github.com/aspnet/AspNetKatana/blob/5d58dab237663b694515a3adbb36dd246a7d4ca2/src/Microsoft.Owin.Security.ActiveDirectory/WindowsAzureActiveDirectoryBearerAuthenticationExtensions.cs#L34

**Comment by JoyceLiang** [comment]
Thank you @Tratcher, that works, will close this issue.
