### ISSUE TITLE
Owin is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240)

### ISSUE THREAD

**Issue by Martin-Stein** [aspnet/AspNetKatana#117]
Please update the libraries to be compatible with (UAP,Version=v10.0.10240)

thanks in advance
Martin

**Comment by ysmoradi** [comment]
Why do you think it should be compatible with that profile?

**Comment by Martin-Stein** [comment]
Because this represents the latest .NET Version!

(I have looked a little beet deeper, UAP,Version=v10.0.10240 uses .Net 4.6.

So to be more precisely the issue should be named as Owin is not compatible with .Net 4.6!

 

 

Kind regards,

 

 

Martin

 

Von: Yaser Moradi [mailto:notifications@github.com] 
Gesendet: Montag, 18. September 2017 19:21
An: aspnet/AspNetKatana <AspNetKatana@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Author <author@noreply.github.com>
Betreff: Re: [aspnet/AspNetKatana] Owin is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) (#117)

 

Why do you think it should be compatible with that profile?

**Comment by Tratcher** [comment]
@Martin-Stein Microsoft.Owin works fine with .NET 4.6. UAP however imposes additional requirements. I haven't tried it yet, what trouble have you had?

**Comment by Martin-Stein** [comment]
HI,

 

When I try to install the NuGet package, Verson 3.1,or 4.0 -alpha,the installation rolls back and I receive this messages:

 

the package  Microsoft.Owin 4.0.0-alpha1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package Microsoft.Owin 4.0.0-alpha1 supports: net451 (.NETFramework,Version=v4.5.1)

 

the package  Owin 1.0.0 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). package Owin 1.0.0 supports: net40 (.NETFramework,Version=v4.0)

 

 

 

Von: Chris Ross [mailto:notifications@github.com] 
Gesendet: Montag, 18. September 2017 20:07
An: aspnet/AspNetKatana <AspNetKatana@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [aspnet/AspNetKatana] Owin is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) (#117)

 

@Martin-Stein <https://github.com/martin-stein>  Microsoft.Owin works fine with .NET 4.6. UAP however imposes additional requirements. I haven't tried it yet, what trouble have you had?

**Comment by Tratcher** [comment]
Ok, that makes sense. UAP is an entire target framework independent of / build on top of .NET. Even if you could install these packages you wouldn't be able to use most of them in that environment. Neither System.Web nor HttpListener work in the UAP sandbox, so you wouldn't be able to receive requests.

**Comment by Martin-Stein** [comment]
Hi Chris,

 

That means, there will be no Owin.Security.* for UAP applications???

 

Kind regards,

 

Martin 

 

Von: Chris Ross [mailto:notifications@github.com] 
Gesendet: Montag, 18. September 2017 23:53
An: aspnet/AspNetKatana <AspNetKatana@noreply.github.com>
Cc: Martin-Stein <mytrainer@freenet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [aspnet/AspNetKatana] Owin is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) (#117)

 

Ok, that makes sense. UAP is an entire target framework independent of / build on top of .NET. Even if you could install these packages you wouldn't be able to use most of them in that environment. Neither System.Web nor HttpListener work in the UAP sandbox, so you wouldn't be able to receive requests.

**Comment by Tratcher** [comment]
What server would you use to receive requests?

That said, I think UAP/UWP is getting netstandard support soon so you may be able to use the Microsoft.AspNetCore.Authentication.* versions of these components.

**Comment by muratg** [comment]
Not enough details on this bug, so closing it.  Please let us know if you are still interested in this.
