### ISSUE TITLE
Redirect url comparison should be case-insensitive.

### ISSUE THREAD

**Issue by hemant271** [aspnet/AspNetKatana#118]
I recently used this project as development for new authorization server, and while requesting for access token from authorization code I faced this issue.

I think url comparison should be case-insensitive. [StringComparer.OrdinalIgnoreCase]

https://github.com/aspnet/AspNetKatana/blob/a4ad9a82cde44ac27242a2d23238aada2ec5b4be/src/Microsoft.Owin.Security.OAuth/OAuthAuthorizationServerHandler.cs#L526

**Comment by hemant271** [comment]
I am still not clear if this is not an issue. Please provide a short explanation.
I'll close this after that.

**Comment by muratg** [comment]
@javiercn Thoughts on this?  What's the general approach in case sensitivity?

**Comment by javiercn** [comment]
Nope. redirect uri comparison should be case sensitive as per spec, both oAuth 2.0 and Open ID Connect. Urls are case sensitive so it needs to be an exact match.

**Comment by hemant271** [comment]
Thanks @javiercn for update.
I found this on requesting authorization code with redirect_uri **http://localhost:12345/callback** and  requesting token with **http://localhost:12345/Callback**, Because both resources would be same in .net project.
