### ISSUE TITLE
License contradiction

### ISSUE THREAD

**Issue by ivanlysiuk** [aspnet/AspNetKatana#122]
We have a legal issue with the licenses, I suspect it was just a left over, but our legal department gives us a headache. He is the deal:
1) https://github.com/aspnet/AspNetKatana/blob/dev/LICENSE.txt clearly refers to APL2
while 
2) https://www.nuget.org/packages/Microsoft.Owin/3.1.0 refers to [MS-.NET-Library License](https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm)

The Nuget package mentions the second license only, without mentioning APL2. However, APL2 must be mentioned as the source code used for the NuGet package uses APL2 (which implies that its license file must be propagated into the distributed package).

Thank you

**Comment by ivanlysiuk** [comment]
The other libs with the same issue are:
Microsoft.Owin.FileSystems
Microsoft.Owin.Host.HttpListener
Microsoft.Owin.Hosting
Microsoft.Owin.StaticFiles

**Comment by Tratcher** [comment]
The source code and the compiled binaries are intentionally licensed differently. @muratg

**Comment by ivanlysiuk** [comment]
Could you please clarify the intention? Thank you

**Comment by Eilon** [comment]
FYI, I contacted our license experts and I'm awaiting a response from them.

**Comment by Eilon** [comment]
We should change the licenses of the NuGet packages to be the same as the source codez - i.e. .NET Foundation, Apache 2.0. Same as we do in ASP.NET Core.
