### ISSUE TITLE
WWW-Authenticate header is mangled

### ISSUE THREAD

**Issue by ravenpride** [aspnet/AspNetKatana#123]
Multiple WWW-Authenticate headers in a response are converted to a comma-separated representation, although RFC 7235 explicitly allows it (see https://tools.ietf.org/html/rfc7235#page-7).

The mangling is done in the following file (line 154 ff):
AspNetKatana/src/Microsoft.Owin.Host.HttpListener/RequestProcessing/ResponseHeadersDictionary.cs

I've the task to implement a webservice with multiple authentication options and some clients have a problem to parse multiple challenges in a single comma-separated WWW-Authenticate header.

Could you please check whether removing the mangling is an option? In my opinion the implementation would be more compliant to the RFC this way :-)

Thank you in advance!

**Comment by Tratcher** [comment]
Unfortunately not, this is a limitation of the underlying System.Net.HttpListener APIs. Switching to ASP.NET Core is the only suggestion I can give you, it provides more compliant servers.
