### ISSUE TITLE
Owin will alway close connection when AuthenticationSchemes is set

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [aspnet/AspNetKatana#124]
I am using Owin / Katana as a http listener. It will nicely allow me to keep my client connections open with a client created like this:

            var credentialsCache = new CredentialCache { { uri, "NTLM", CredentialCache.DefaultNetworkCredentials } };
            var handler = new HttpClientHandler { Credentials = credentialsCache };
            var client = new HttpClient(handler) { BaseAddress = uri };
            client.DefaultRequestHeaders.ConnectionClose = false;
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            ServicePointManager.FindServicePoint(uri).ConnectionLeaseTimeout = 120 * 1000;  // Close connection after two minutes

However when I add required authentication scheme to my listener, the host will close the connection after every request,. I add this to my Config method:

                var listener = (HttpListener)appBuilder.Properties[typeof(HttpListener).FullName];
                listener.AuthenticationSchemes = AuthenticationSchemes.IntegratedWindowsAuthentication;

This will not only add delay but will eventually exhaust my available ports. I can see in netstat the list of connections in TIME_WAIT is ever growing.
Is it not possible to keep connections open when AuthenticationSchemes is set?

**Comment by Tratcher** [comment]
Closing the connection per request is a security feature of windows auth. You can override it by setting UnsafeConnectionNtlmAuthentication.
https://msdn.microsoft.com/en-us/library/system.net.httplistener.unsafeconnectionntlmauthentication(v=vs.110).aspx
Only the first request will be challenged, and then all subsequent requests on that connection will reuse the same cached credentials. Only do this if you're positive the connections can never be shared by multiple users.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Ok. That is exactly what I am looking for.
However if I use AuthenticationSchemes.IntegratedWindowsAuthentication; the problem remains and connections are closed at every request.
If I use Negotiate, I am rejected. I guess it prefers Kerberos

**Comment by FenrisWolfAtMiddleEarth** [comment]
The only similar setting I have found on the HttpClient is ConnectionClose = false. However that also does not solve the problem. The problem can be recreated with these lines of code:

    class Program
    {
        static void Main()
        {
            var httpListener = WebApp.Start($"http://+:8900/", appBuilder =>
            {
                var listener = (HttpListener)appBuilder.Properties[typeof(HttpListener).FullName];
                listener.AuthenticationSchemes = AuthenticationSchemes.Ntlm;
                listener.UnsafeConnectionNtlmAuthentication = true;

                var config = new HttpConfiguration();
                config.Routes.MapHttpRoute("DefaultApi", "api/{controller}/{id}", new { id = RouteParameter.Optional });
                appBuilder.UseWebApi(config);
            });

            var uri = new Uri("http://localhost:8900");
            var credentialsCache = new CredentialCache { { uri, "NTLM", CredentialCache.DefaultNetworkCredentials } };
            var handler = new HttpClientHandler { Credentials = credentialsCache};
            var client = new HttpClient(handler) { BaseAddress = uri };
            client.DefaultRequestHeaders.ConnectionClose = false;
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            ServicePointManager.FindServicePoint(uri).ConnectionLeaseTimeout = 120 * 1000;  // Close connection after two minutes

            var sw = Stopwatch.StartNew();
            for (int i = 0; i < 1000; i++)
            {
                using (var result = client.GetAsync("api/HelloUniverse?callerId=Me").Result)
                {
                    using (var response = result.Content.ReadAsStringAsync())
                    {
                        Console.WriteLine($"{i:#####} Received: {response.Result}");
                    }
                }
            }
            sw.Stop();
            Console.WriteLine($"Done {sw.ElapsedMilliseconds}");

            Console.ReadKey();
        }
    }

Other than that, only a Controller is needed:

    public class HelloUniverseController : ApiController
    {
        public string Get(string callerId)
        {
            return "Hello universe";
        }
    }

I am using framework 461 with these package references:
"Microsoft.AspNet.WebApi.Core" Version="5.2.3"
"Microsoft.AspNet.WebApi.Owin" Version="5.2.3"
"Microsoft.Owin.Host.HttpListener" Version="3.1.0"
"Microsoft.Owin.Hosting" Version="3.1.0"

Any advice would be greatly appreciated.

**Comment by Tratcher** [comment]
You need WebRequestHandler instead of HttpClientHandler:
https://msdn.microsoft.com/en-us/library/system.net.http.webrequesthandler.unsafeauthenticatedconnectionsharing(v=vs.110).aspx

**Comment by FenrisWolfAtMiddleEarth** [comment]
Works like a charm. It makes a huge difference in performance.
Thank you very much.
