### ISSUE TITLE
WsFederation package

### ISSUE THREAD

**Issue by StenPetrov** [aspnet/AspNetKatana#126]
package id="Microsoft.IdentityModel.Protocols.WsFederation" version="5.2.0.407281058-pre" targetFramework="net451" 

This is nowhere to be found!

**Comment by Tratcher** [comment]
Why do you need that version? The latest is https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.WsFederation/5.2.0-preview1-408290725
