### ISSUE TITLE
MapWhenAsync not working with UseWebApi with MapHttpAttributeRoutes

### ISSUE THREAD

**Issue by timtong1982** [aspnet/AspNetKatana#127]
goal: enable attribute routing at host/uxapi/...etc
```
app.MapWhenAsync(
                async _
                    => await Task.FromResult(
                        _.Request.Path.HasValue &&
                        _.Request.Path.Value.StartsWith("/uxapi", StringComparison.InvariantCultureIgnoreCase)),
                _
                    =>
                {
                    _.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
                    _.UseCookieAuthentication(new CookieAuthenticationOptions());
                    HttpConfiguration webApiConfig = new HttpConfiguration();
                    webApiConfig.MapHttpAttributeRoutes();
                    _.UseWebApi(webApiConfig);
                });
above is not working, but when changes to:
 app.Map(
             "/uxapi", ... (same above)
```
the attribute is working

**Comment by Tratcher** [comment]
If Map works for you then why aren't you using it?

It's also not clear why you're using MapWhenAsync rather than MapWhen.

Rather than `_.Request.Path.Value.StartsWith` try `_.Request.Path.StartsWithSegments`.

**Comment by timtong1982** [comment]
Thanks Tratcher for replying!

the reason I want to use MapWhen* is in the future, we probably want to more branching than the request URL

tried both MapWhen and MapWhenAsync are not working.

**Comment by ysmoradi** [comment]
I've used Map, MapWhen and MapWhenAsync several times. It's a complicated thing and you can't simply say those Map & MapWhenAsync in your sample code are equal. As an example,in both asp.net core and pipeline, request path & path base will be affected by Map.
I'm not in front of PC, so I'm not able to test, but for following samples: Map("/api") and MapWhen(c => ... /*request starts with /api*/). Map needs attribute routing with value "/test{id}" but MapWhen needs "/api/test{id}". So there is a difference.
