### ISSUE TITLE
WS-Federation Encryption

### ISSUE THREAD

**Issue by plraustin** [aspnet/AspNetKatana#131]
Any plans to support encryption for WS-Federation Protocol?

**Comment by Tratcher** [comment]
Message encryption? No.

**Comment by muratg** [comment]
We don't plan to do this in Katana.  

@brentschmaltz  Do you guys have any thoughts of supporting this in IdentityModel?

**Comment by brentschmaltz** [comment]
The only encryption I know of is for SAML2 tokens, which the spec allows for EncryptedAssertion.
We have an issue in vNext to support this: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/734 . There is no date for this yet.

We do have plans for TokenBinding
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/716

Haven't planned on ProofOfPossession yet as the spec is a long way away. TB should be closed first quarter of 2018.
