### ISSUE TITLE
401 Unauthorized for services on same application server

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#132]
_From @FenrisWolfAtMiddleEarth on October 31, 2017 13:20_

Hi,

We are hosting multiple webservices with Owin on the same applicationserver. Our services require NTLM authentification. The services are accessed through a DNS-name which points to a load-balancer.
When service A tries to access service B and the load-balancer selects the B instance on the same application server as service A, we are rejected with a 401 unauthorized.
It looks like our issue corresponds nicely to the problem described in this article
https://support.microsoft.com/en-us/help/896861/you-receive-error-401-1-when-you-browse-a-web-site-that-uses-integrate
However the suggested solution here is to update registry keys, which it is not a preferred solution. That is just more configuration when our application servers are replaced or another node is added to the load balancer.
Is there any way this can be solved which does not involve registry keys? Preferably through application code on the client or the host.

_Copied from original issue: owin/owin#54_

**Comment by Tratcher** [comment]
NTLM can only be turned on or off in application code, there is no way to configure it from there. Have you tried the suggested workaround to verify it fixes your scenario?

**Comment by FenrisWolfAtMiddleEarth** [comment]
Yes. We have tried the suggested solution 2) DisableLoopbackCheck = 1
That does fix the problem
However changing registry settings is not a good solution. Today it is all about phoenix-servers. Servers are not fixed hardware like it was 15-20 years ago.  We are constantly disposing and creating new virtual servrs for automated tests and other purposes. So having application dependency to machine-configuration such as registry-keys is not where we want to be.
So I am looking for a way to override the loopbackcheck in code.

**Comment by Tratcher** [comment]
Then you'll need to pick a different protocol that's not 15-20 years old. JWT Bearer is quite popular these days.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Fair enough. Problems is as always legacy code and systems.
I will look in to whether it is doable in our organization.
Thanks for your input.
