### ISSUE TITLE
Open ID Connect - State not passed to OpenIdConnectProtocolValidator

### ISSUE THREAD

**Issue by AntSharK** [aspnet/AspNetKatana#136]
The "state" parameter is not passed into the OpenIdConnectProtocolValidationContext() during authentication, even if RequireState is set to true.

So if ProtocolValidator.RequireState is set to true, authentication will fail even if the State parameter is passed in.

**Comment by Tratcher** [comment]
The handler already checks for state so the validator does not need to.
https://github.com/aspnet/AspNetKatana/blob/7db01eb2db3acf787651b4dc27d5fd05dc47e4ec/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L240-L246

**Comment by AntSharK** [comment]
The problem is down the line:
https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L355-L361

Unfortunately, the default OpenIdConnectProtocolValidator does not pick up the state automatically from the ProtocolMessage, and it's not passed in.

So this exception gets thrown since RequireState is true, but the state is blank:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L709-712

**Comment by Tratcher** [comment]
Why are you turning on RequireState? It's not required in this context.

**Comment by AntSharK** [comment]
That is true. I see the default ProtocolValidator is now initiated with RequireStateValidation = false. So, perhaps slightly confusing, but I guess not really a bug.
