### ISSUE TITLE
TicketSerializer does not serialize Claim Properties

### ISSUE THREAD

**Issue by brian-knoll-micronetonline** [aspnet/AspNetKatana#137]
### Title
*Serializing and then Deserializing a ticket loses data*  

### Functional impact
*not all data available when looking at claim*

### Minimal repro steps
*Execute this C# code snippet*
```
var claim = new Claim("TestClaimType", "Everything");
claim.Properties["Important Property"] = "Important Value";
var identity = new ClaimsIdentity(new[] {claim}, "authType");
var properties = new AuthenticationProperties();
var ticket = new AuthenticationTicket(identity, properties);
Console.WriteLine(ticket.Identity.Claims.First().Properties);
TicketSerializer ticketSerializer = new TicketSerializer();
ticket = ticketSerializer.Deserialize(ticketSerializer.Serialize(ticket));
Console.WriteLine(ticket.Identity.Claims.First().Properties);
```

### Expected result
*All data would survive the serialization and deserialization*  

### Actual result
*Only some of the data survives*

**Comment by Tratcher** [comment]
@brentschmaltz how commonly do people set claim properties? This is the first ask I've seen for this in 5 years.

Also, this is a significant interop break.

**Comment by brian-knoll-micronetonline** [comment]
i have committed an additional change to cleanup the interop break.

**Comment by Tratcher** [comment]
We've decided not to take this change.
