### ISSUE TITLE
singin id for IdentityServer3

### ISSUE THREAD

**Issue by lyolikaa** [aspnet/AspNetKatana#142]
Hello.
I'm trying to implement Quickbooks SSO provider with Katana middleware.
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions...
..
SignInAsAuthenticationType = signInAsType,//"idsrv.external"
...
As a response I get callback to IS3: http://localhost:44333/callback?state=... 
and it says about error: _No signin id passed_
Do I need hanlde it in OpenIdConnectAuthenticationNotifications, or override something in OpenIdConnectAuthenticationHandler
Thank you.)

**Comment by Tratcher** [comment]
That's not much to go on. At a minimum you'd need to share more of your configuration. More likely you'll need to ask IS3 what that error means.

**Comment by lyolikaa** [comment]
@Tratcher , more details: 


```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions

            {
                ClientId = IntuitClientId,
                Authority = "Quickbooks",
                MetadataAddress = "https://developer.intuit.com/.well-known/openid_sandbox_configuration/",
                RedirectUri = "https://localhost:44333/callback",
                CallbackPath = new PathString("/callback"),
                ClientSecret = IntuitClientSecret,
                ResponseType = "code",//code only for Intuit
                Scope = "com.intuit.quickbooks.accounting",
```

Actually I follow Intuit manual _https://developer.intuit.com/docs/00_quickbooks_online/2_build/10_authentication_and_authorization/50_identity/20_openid_connect_
I am able to authorize and get callback and stuck in that IS3 error
In doubt, where signin id is missed

**Comment by lyolikaa** [comment]
I've connected IdentityServer3 sources to debug, it cannot take "signin" from middleware, here:   

 `
      

        public static async Task<string> GetSignInIdFromExternalProvider(this IOwinContext context)
        {
            if (context == null) throw new ArgumentNullException("context");
            
            var result = await context.GetAuthenticationFrom(Constants.ExternalAuthenticationType);

            if (result != null)
            {
                string val;
                if (result.Properties.Dictionary.TryGetValue(Constants.Authentication.SigninId, out val))
                {
                    return val;
                }
            }
            return null;
        }

**Comment by Tratcher** [comment]
Those result.Properties flow in the State field of the protocol. Does a Fiddler trace show the State field being sent back to IS3?

**Comment by lyolikaa** [comment]
mmm, what a State? I see in Notifications.RedirectToIdentityProvider context.ProtocolMessage.State = something-quickbooks-special

**Comment by lyolikaa** [comment]
var result gets null here:
![image](https://user-images.githubusercontent.com/11559028/34148910-ed88abdc-e4ab-11e7-8c2c-e69b2a6ee7cd.png)

**Comment by lyolikaa** [comment]
I tried put some id in UserService.PreAuthenticateAsync, Notifications.RedirectToIdentityProvider...
maybe I have to enable:
```
 app.SetDefaultSignInAsAuthenticationType("External");
     app.UseCookieAuthentication(new CookieAuthenticationOptions
    
```
or use 
`app.UseOAuthAuthorizationServer(new OAuthAuthorizationServerOptions`
instead of 
` app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions`

**Comment by Tratcher** [comment]
You really need to go ask IS3 these questions. They have pretty good samples and docs last I checked.
