### ISSUE TITLE
MicrosoftAccountAuthenticationProvider.OnAuthenticated does not have access to properties

### ISSUE THREAD

**Issue by chrispatrick** [aspnet/AspNetKatana#143]
I'm not sure if there's a reason for this behaviour, but I'm using the MicrosoftAccountAuthenticationMiddleware and implementing a custom handler in OnAuthenticated. However, context.Properties is null at this point which means I can't maintain any custom state across the authentication process without doing something like manually creating and deleting cookies.

It appears to be a pretty simple thing in MicrosoftAccountAuthenticationHandler.cs to swap lines 124 and 126 around so that the properties are set on the context before OnAuthenticated is called.

**Comment by Tratcher** [comment]
This looks like a typo. All of the other providers set the Properties first.
https://github.com/aspnet/AspNetKatana/blob/1653abe19b8740977e368ee0782f1e3eb2c65d03/src/Microsoft.Owin.Security.MicrosoftAccount/MicrosoftAccountAuthenticationHandler.cs#L124-L128
https://github.com/aspnet/AspNetKatana/blob/1653abe19b8740977e368ee0782f1e3eb2c65d03/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs#L148-L152

Feel free to send a PR if you get to it before I do.

**Comment by chrispatrick** [comment]
Thanks. Thought it might be a typo. PR submitted.
