### ISSUE TITLE
Request.Path throws ArgumentException for OPTIONS * HTTP/1.1

### ISSUE THREAD

**Issue by ryanski44** [aspnet/AspNetKatana#149]
OPTIONS * HTTP/1.1 is a valid HTTP Request (https://tools.ietf.org/html/rfc7231#section-4.3.7). When using IOwinContext to interrogate this request, calling Request.Path throws this exception:

System.ArgumentException: 
The path must start with a '/' followed by one or more characters.
Parameter name: value

This exception comes from PathString which makes sure that the path starts with a "/".

This rule makes sense for every other case, however for this case it would only make sense if there was another way to determine that this was an OPTIONS request for * and that Path is not applicable. As far as I could tell, there is not a way to get this information.

Furthermore, many libraries that use Request.Path (like System.Web.Http.Owin) will not catch this exception, and therefore not handle this OPTIONS request properly.

**Comment by Tratcher** [comment]
For reference, when we handled this in ASP.NET Core we opted to leave path empty and only expose the * in the raw target field.

Which server were you using, SystemWeb or HttpListener?

**Comment by ryanski44** [comment]
@Tratcher, we are using HttpListener.

**Comment by Tratcher** [comment]
Workaround: Clear the request path before it gets consumed.
```
            app.Use((context, next) =>
            {
                if (context.Get<string>("owin.RequestPath") == "*")
                {
                    context.Set<string>("owin.RequestPath", "");
                }
                return next();
            });
```

**Comment by ryanski44** [comment]
@Tratcher,
Thanks, I'll try that!

**Comment by muratg** [comment]
Simple workaround. We won't be fixing this.
