### ISSUE TITLE
Odd behavior with cookie authentication in windows service.

### ISSUE THREAD

**Issue by henriquecampos** [aspnet/AspNetKatana#150]
I'm facing an strange behavior when running a owin self host SignalR project. My project setup is as follows:

SignalRSelfHost -> A console app with SignalR hubs. I'm using Topshelf to simplify service installation, but tried with regular services with the same behavior.

JavascriptClient -> A ASP.NET MVC app that authenticates the user (using cookies) and connects to the self hosted signalr app.

When running as a simple console app, everything works as expected, both the projects are listening on localhost (different ports), and the user name and id are visible on both projects. But when i tried installing and running the first project as a service, the user became unavailable. The service configuration is as follows:

	public void Configuration(IAppBuilder app)
	{
		app.UseCors(CorsOptions.AllowAll);

		var dataProtectionProvider = new DpapiDataProtectionProvider("AppName");
		app.SetDataProtectionProvider(dataProtectionProvider);
		var protector = dataProtectionProvider.Create("Access_Token");
		var ticketDataFormat = new TicketDataFormat(protector);

		// Configure the sign in cookie
		app.UseCookieAuthentication(new CookieAuthenticationOptions
		{
			AuthenticationType = "ApplicationCookie",
			CookieDomain = "localhost",
			LoginPath = new PathString("/Account/Login"),
			TicketDataFormat = ticketDataFormat
		});

		app.MapSignalR();
	}

The web configuration is very similar:

	public void ConfigureAuth(IAppBuilder app)
	{
		// Configure the db context, user manager and signin manager to use a single instance per request
		app.CreatePerOwinContext(ApplicationDbContext.Create);
		app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
		app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);

		var dataProtectionProvider = new DpapiDataProtectionProvider("AppName");
		app.SetDataProtectionProvider(dataProtectionProvider);
		var protector = dataProtectionProvider.Create("Access_Token");
		var ticketDataFormat = new TicketDataFormat(protector);

		// Configure the sign in cookie
		app.UseCookieAuthentication(new CookieAuthenticationOptions
		{
			AuthenticationType = "ApplicationCookie",
			CookieDomain = "localhost",
			LoginPath = new PathString("/Account/Login"),
			TicketDataFormat = ticketDataFormat
		});
	}

I can provide a simple demo if you find it useful.

**Comment by henriquecampos** [comment]
I've found my problem. The Microsoft.Owin.Security.DataProtection.DpapiDataProtector class uses the DataProtectionScope.CurrentUser scope, with was not working on the windows service. I created my own class using LocalMachine scope, and after clearing the cookies, everything is working fine.

I'll leave the code here for reference:

	internal class LocalMachineDpapiDataProtector : IDataProtector
    {
        private readonly DpapiDataProtector _protector;

        public LocalMachineDpapiDataProtector(string appName) : this(appName, new[] { "Access_Token" }) { }

        public LocalMachineDpapiDataProtector(string appName, string[] purposes)
        {
            _protector = new DpapiDataProtector(appName, "Microsoft.Owin.Security.IDataProtector", purposes)
            {
                Scope = DataProtectionScope.LocalMachine
            };
        }

        public byte[] Protect(byte[] userData)
        {
            return _protector.Protect(userData);
        }

        public byte[] Unprotect(byte[] protectedData)
        {
            return _protector.Unprotect(protectedData);
        }
    }


And the configuration:

	var protector = new LocalMachineDpapiDataProtector("AppName");
	var ticketDataFormat = new TicketDataFormat(protector);

	var options = new CookieAuthenticationOptions
	{
		AuthenticationType = "ApplicationCookie",
		CookieDomain = "localhost",
		LoginPath = new PathString("/Account/Login"),
		TicketDataFormat = ticketDataFormat
	};
	
	app.UseCookieAuthentication(options);

**Comment by Tratcher** [comment]
Nice.
