### ISSUE TITLE
ChunkingCookieManager can return values that aren't fully %-decoded

### ISSUE THREAD

**Issue by elezar42** [aspnet/AspNetKatana#151]
If a %-encoded value results in an encoded entity right at the boundary for chunking, that entity won't get decoded when returned via GetRequestCookie. Since the entire value gets escaped before chunking, it's possible for the encoded entity (e.g., %20) to get split between the cookie chunks. However, GetRequestCookie relies on the OwinRequest to handle the decoding of the cookies, which of course decodes each individual chunk separately. This means that any encoded entities that were spread across multiple cookie chunks will still be encoded once the chunked cookies are rejoined.

**Comment by Tratcher** [comment]
Where are you using the ChunkingCookieManager? The default usage in CookieAuth wouldn't have this problem as it doesn't use any values that would require escaping.

**Comment by elezar42** [comment]
I'm using it directly from my own code. I have a rather large value that is encrypted & Base64 encoded, that I need to store in a cookie. It can be too large for a single cookie, so I'm using the ChunkingCookieManager. Since that class is public rather than internal, I thought it would be safe to use directly...

**Comment by Tratcher** [comment]
An encrypted & Base64 encoded value wouldn't need %-encoding... that's exactly what CookieAuth does. Can you share some raw values before chunking, and what the round trip looks like?

**Comment by elezar42** [comment]
Base64 encoding can include + and /, both of which would get %-encoded. Ahh, I just looked at what exactly CookieAuth is doing, and looks like it's using the Base64UrlTextEncoder, which automatically replaces + and / with - and _. I guess I could do the same thing, but it still feels like a bug to me, that the ChunkingCookieManager doesn't work with standard Base64 strings.

**Comment by Tratcher** [comment]
It's always better to use cookie values that don't require additional encoding. The encoding provided by the cookie APIs is only there to prevent invalid values from corrupting the protocol.

I don't anticipate trying to fix this ourselves in ChunkingCookieManager. You're welcome to take a look and see how complex a fix might be.

**Comment by Tratcher** [comment]
FYI I had a second internal customer report about this. It was the same situation with base64 content and they've applied the same mitigation using the Base64UrlTextEncoder.

Note this issue does not occur in AspNetCore, that version of the chunking cookie manager chunks before any encoding would happen. It avoids splicing, but mask the chunk size calculation less accurate.
