### ISSUE TITLE
OAuthValidateClientAuthenticationContext.ClientId and Parameters are null

### ISSUE THREAD

**Issue by mukeshrebari** [aspnet/AspNetKatana#153]
Can anyone answer [this](https://stackoverflow.com/questions/47933471/oauthvalidateclientauthenticationcontext-clientid-and-parameters-are-null-after)

I have a strange case for above OAuth process ClientId is null as well as Parameters is empty.

1. The above code works fine on all of our developer machines.

2. Compiled Version of Web API also works if hosted in IIS on Developer Machine.
3. But When I try to host Web API on my remote server it always gives error "Missing ClientId".
4. It uses to work perfectly on the same server before upgrading NuGet packages. Microsoft.Owin.Security.OAuth 3.0.1.0 upgraded to 3.1.0.0 Microsoft.Owin.Security 3.0.1.0 upgraded to 3.1.0.0 And All Unity Packages

**Comment by indiaweblab** [comment]
Can anyone tell me, If I am at the right place to raise this issue? Or no one is in the mood to help me out? I tried my all efforts in resolving this bug but no luck

**Comment by muratg** [comment]
I don't know the Katana auth server very well, but how do you register your client apps with that? Perhaps it's registered properly on your dev machine, but not your prod server?
