### ISSUE TITLE
Configuration caching in OpenIdConnectAuthenticationHandler

### ISSUE THREAD

**Issue by dzmitrykarnitski** [aspnet/AspNetKatana#156]
Hi,

I am trying to make OpenIdConnect authentication configuration somewhat dynamic. I supposed that this can be achieved by creating some notification handlers and overwriting default configuration manager to provide a necessary configuration at runtime. However, a configuration provided by configuration is also cached inside the authentication handler. 
Like here:
https://github.com/aspnet/AspNetKatana/blob/6fcee9515f439cd3f8da54977f97280e8056eee4/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L280

Can someone explain why we need to cache the configuration in the configuration manager and in the authentication handler?
And is it possible to make configuration caching optional in the handler?

**Comment by Tratcher** [comment]
New handlers are created for each request so that caching shouldn't impact you much.

**Comment by dzmitrykarnitski** [comment]
Yes, I agree. Everything works fine for now. Just wanted to be sure that this will be ok in future. Configuration manager already caches the value, so I didn't find any reasons to cache the configuration again in the handler.

**Comment by Tratcher** [comment]
The handler wants to make sure it uses the same configuration for the duration of a request. The ConfigurationManager caches but could update it's cache at any time.

**Comment by dzmitrykarnitski** [comment]
Oh, makes sense. It seems, that in my case it might even help. Thank you! 
Closing this.
