### ISSUE TITLE
Microsoft.Owin.Security.Jwt Token signature validation.

### ISSUE THREAD

**Issue by yaliashkevich** [aspnet/AspNetKatana#157]
I'm using Microsoft.Owin.Security.Jwt middleware to authenticate request with JWT access token produced by IdentityServer. It works fine.
The only question I have is token signature validation. For now I have to configure the IssuerSigningToken/IssuerSigningKey in the code (startup.cs).

My goal is to implement "auto" keys discovery (load JWK set from uri specified in discovery document: /.well-known/openid-configuration/jwks).

Is it any built-in support for such scenario?

**Comment by Tratcher** [comment]
No, but it's something we are looking into for the future.

**Comment by muratg** [comment]
@yaliashkevich I recommend looking at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/ repo instead. The implementation details for JWT is there.
