### ISSUE TITLE
Combine multiple WebAPI assemblies in one host process (here: Unit test project) results in "404 / Not found" at controller endpoints

### ISSUE THREAD

**Issue by netsrotr** [aspnet/AspNetKatana#161]
### Combine multiple WebAPI assemblies (WebAPI 2 **v5.2.3**) in one host process
*Navigating any API endpoint  results in "404 / Not found", but hosting each API separately it runs fine*

### Functional impact
*This issue has an big impact to our project structure design*  

### Minimal repro steps
*Attached is a sample solution containing two API projects and one unit test project you can run to see the issue.*  

1. unzip the samples app
2. compile the projects (NuGet restore)
3. run the unit tests

### Expected result
*I would expect to get the HTTP Result OK (200)*  

### Actual result
*I always get HTTP 404 (Not found)*  

### Further technical details
I try to figure out how to setup/configure a host (IIS) using MVC/WebAPI 2 **v5.2.3** to listen for multiple contained API endpoints contained in external assemblies. Documentation is not very clear about if it is allowed to setup multiple HttpConfiguration(s) but it is possible (except I have route clashes, that is not the case here).
Attached is a sample that uses a Unit test to:

1. run two servers in the same process (similar to IIS host) that share a common HttpConfiguration
2. run two servers in the same process that do **not** share the config.

Both tests are failing. I'm really stuck what I am doing wrong or badly configured or is not possible at all?
I have applied work to provide custom AssemblyResolver per API inheriting DefaultAssembliesResolver, but seems does not matter. Also using the approach introduced here [https://www.strathweb.com/2016/05/running-multiple-asp-net-web-api-pipelines-side-by-side/](https://www.strathweb.com/2016/05/running-multiple-asp-net-web-api-pipelines-side-by-side/) did not worked.

Can anyone point the right direction please?  Thanks i.A.

[MultipleWebAPIs.zip](https://github.com/aspnet/AspNetKatana/files/1673707/MultipleWebAPIs.zip)

**Comment by netsrotr** [comment]
Maybe this is the wrong git repo, I filed the same issue against AspNetWebStack too: [https://github.com/aspnet/AspNetWebStack/issues/122](https://github.com/aspnet/AspNetWebStack/issues/122)
Thank you.

**Comment by Tratcher** [comment]
Yes, AspNetWebStack looks more appropriate. Closing this for now.
