### ISSUE TITLE
Webforms access_denied

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetKatana#163]
I have a new Webforms project Facebook and Microsoft ID

https://coworking.ppedv.de/Account/Login

GET /signin-microsoft?code=Md3a43ad7-046a-d49a-ee81- ....
GET /Account/RegisterExternalLogin?providerName=Microsoft&returnUrl=&error=access_denied HTTP/1.1

GET /signin-facebook?code=AQDiJ6xLEpCP0vE562FhFWx5TwW_
GET /Account/RegisterExternalLogin?providerName=Facebook&returnUrl=&error=access_denied HTTP/1.1

4. preview 1

**Comment by Tratcher** [comment]
Sounds like your client secrets are missing or invalid.

**Comment by hannespreishuber** [comment]
ok, you are kind of right- took now a new App registration (konvergent in german) and not live- this works. Still on Facebook issue
