### ISSUE TITLE
How To Decode The Paylod From A Token Issued From Microsoft.Owin.Security.OAuth Middleware

### ISSUE THREAD

**Issue by rhavlick** [aspnet/AspNetKatana#164]
Hello,

I am being issued a token from the Microsoft.Owin.Security.OAuth middleware and as a client I need to see the payload.  Normally with other JWT tokens they are just base 64 encoded and can be read from a site like jwt.io.  Does anyone know if there is a way to read the payload from the token that was issued?

Thanks

**Comment by Tratcher** [comment]
These are not JWT tokens, the default format is encrypted on the server. This is how it's read elsewhere in the app:
https://github.com/aspnet/AspNetKatana/blob/5d6e25b303e0efa27fde385750b59ff58ce194b5/src/Microsoft.Owin.Security.OAuth/OAuthBearerAuthenticationMiddleware.cs#L56-L59

**Comment by rhavlick** [comment]
Thanks Tratcher, so client side, would there be any way to decode that token so the client can see the payload?  (From the client side I need to see some claims).

Thanks so much.

**Comment by Tratcher** [comment]
And by client you mean in the Browser or similar? Not directly. The server would have to expose an endpoint that toke the token and returns the claim data.

**Comment by rhavlick** [comment]
Great, thanks again Tratcher, that is simple enough.
