### ISSUE TITLE
Authenticate crashes when using AuthenticationMode.Passive

### ISSUE THREAD

**Issue by mliesmons** [aspnet/AspNetKatana#166]
Specifying Passive, and logging on explicitly with a challenge once the application has started, results in the exception:
`Object synchronization method was called from an unsynchronized block of code.`

**Comment by Tratcher** [comment]
Stack trace? Repro code?

**Comment by mliesmons** [comment]
This is part of a large IoT project solution, I reverted back to 3.1.0
No time to make an isolated repro, sorry.

I moved to the 4.0 preview in another project to get rid of the version mess with System.IdentityModel.Tokens.Jwt, where  authentication mode is Active, and here I do not have the issue.

Just try it in Passive mode with UseOpenIdConnectAuthentication:


        public void ConfigureAuth(IAppBuilder app)
        {
#if DEBUG
            if (SecurityExtensions.ComputerIsDomainJoined)
            {
                System.Net.WebRequest.DefaultWebProxy = new System.Net.WebProxy(new Uri(Properties.Settings.Default.ProxyAddress), true);
            }
#endif
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            // There is a bug in the latest version of OWIN
            // https://github.com/KentorIT/owin-cookie-saver
            app.UseKentorOwinCookieSaver();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = CookieAuthenticationDefaults.AuthenticationType,
                CookieHttpOnly = true,
                CookieSecure = CookieSecureOption.Always,
            });

            app.UseOpenIdConnectAuthentication(
                CreateOptions(AuthenticationMode.Passive, OpenIdConnectAuthenticationDefaults.AuthenticationType, SecurityExtensions.CommonAuthority, SecurityExtensions.ClientId));
            app.UseOpenIdConnectAuthentication(
                CreateOptions(AuthenticationMode.Passive, Properties.Settings.Default.SignUpOrInPolicyId, TenantNameB2CAuthority, SecurityExtensions.ClientIdB2C));
            app.UseOpenIdConnectAuthentication(
                CreateOptions(AuthenticationMode.Passive, Properties.Settings.Default.UserProfilePolicyId, TenantNameB2CAuthority, SecurityExtensions.ClientIdB2C));
            app.UseOpenIdConnectAuthentication(
                CreateOptions(AuthenticationMode.Passive, Properties.Settings.Default.PasswordResetPolicyId, TenantNameB2CAuthority, SecurityExtensions.ClientIdB2C));
        }

        private string MetadataAddress(string authority, string authenticationType)
        {
            switch(authenticationType)
            {
                case OpenIdConnectAuthenticationDefaults.AuthenticationType:
                    return $"{authority}/.well-known/openid-configuration";
                default:
                    return $"{authority}/v2.0/.well-known/openid-configuration?p={authenticationType}";
            }
        }

        private OpenIdConnectAuthenticationOptions CreateOptions(AuthenticationMode mode, string authenticationType, string authority, string clientId)
        {
            var options = new OpenIdConnectAuthenticationOptions
            {
                AuthenticationMode = mode,
                AuthenticationType = authenticationType,
                Authority = authority,
                ClientId = clientId,
                MetadataAddress = MetadataAddress(authority, authenticationType),

                PostLogoutRedirectUri = SecurityExtensions.RedirectUri,
                RedirectUri = SecurityExtensions.RedirectUri,
                TokenValidationParameters = new Tokens.TokenValidationParameters
                {
                    // Make sure ClaimsPrincipal.Current.Identity.Name finds our name claim
                    NameClaimType = SecurityExtensions.NameClaimType,

                    // Could optionally call WebAPI to validate (e.g. against the DB)
                    // WebAPI IS validating the issuer when it receives a token
                    ValidateIssuer = false,

                    // Makes retrieval of our issued token easy by storing it in the principal
                    // Use SecurityExtensions.CurrentToken to access it
                    SaveSigninToken = true
                },
                SecurityTokenHandlers = new Tokens.SecurityTokenHandlerCollection(new[] { new TokenValidator() }),
                Notifications = new OpenIdConnectAuthenticationNotifications()
                {
                    AuthenticationFailed = AuthenticationFailed,
                    SecurityTokenReceived = TokenValidated.SecurityTokenReceived,
                    SecurityTokenValidated = TokenValidated.SecurityTokenValidated,
                    RedirectToIdentityProvider = RedirectToIdentityProvider,
                }
            };

            return options;
        }

**Comment by Tratcher** [comment]
@mliesmons that helps but you still haven't said what the error was.

**Comment by Tratcher** [comment]
@mliesmons thanks. A stack trace would also help if you can get it.

**Comment by mliesmons** [comment]
As mentioned in my very first comment:

“Object synchronization method was called from an unsynchronized block of code.”

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
