### ISSUE TITLE
BootstrapContext is NULL after TokenValidationParameters is shifted to Microsoft.IdentityModel.Tokens

### ISSUE THREAD

**Issue by GauravDhavale** [aspnet/AspNetKatana#167]
I was facing the TokenValidationParameters related error as highlighted in [this](https://github.com/aspnet/AspNetKatana/issues/76).  So, I updated the related packages to the preview versions as suggested in this issue and also updated TVP namespace to `Microsoft.IdentityModel.Tokens` from `System.IdentityModel.Tokens`. However, I'm facing issues while fetching the access token using the `ClaimsPrincipal` and `BootstrapContext` as it's in the namespace `System.IdentityModel.Tokens`. 

My code in Startup.Auth.cs file is as follows: 

 ```
public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {

                    ClientId = clientId,
                    Authority = authority,
                    PostLogoutRedirectUri = postLogoutRedirectUri,
                    RedirectUri = postLogoutRedirectUri,
                    TokenValidationParameters = new TokenValidationParameters
                    {
                        SaveSigninToken = true
                    },
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthorizationCodeReceived = async context =>
                        {
                            var code = context.Code;
                            ClientCredential credential = new ClientCredential(clientId, appKey);
                            string signedInUserID = context.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier).Value;
                            AuthenticationContext authContext = new AuthenticationContext(authority);
                            AuthenticationResult ar = await authContext.AcquireTokenByAuthorizationCodeAsync(code, new Uri(RedirectUri), credential, "https://graph.windows.net");
                        },
                        AuthenticationFailed = context =>
                        {
                            context.HandleResponse();
                            context.Response.Redirect("/Error?message=" + context.Exception.Message);
                            return Task.FromResult(0);
                        }
                    }
                });

        }

```

In another file in Home controller, I want to get the user information along with Access Token using below code: 

```
  private Task GetTokenViaBootStrap()
        {
            return Task.Run(async () =>
            {
                var bc = ClaimsPrincipal.Current.Identities.First().BootstrapContext as BootstrapContext;

                string userName = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Upn) != null ? ClaimsPrincipal.Current.FindFirst(ClaimTypes.Upn).Value : ClaimsPrincipal.Current.FindFirst(ClaimTypes.Email).Value;
                string userAccessToken = bc.Token;
                UserAssertion userAssertion = new UserAssertion(bc.Token, "urn:ietf:params:oauth:grant-type:jwt-bearer", userName);
                string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
                string signedInUserID = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;
                AuthenticationContext authContext = new AuthenticationContext(authority);
                ClientCredential cred = new ClientCredential(clientId, appKey);
                result = await authContext.AcquireTokenAsync("https://graph.microsoft.com", cred, userAssertion);
                UserAccessToken = result.AccessToken;
            });

        }
```
`The ClaimsPrincipal.Current.Identities.First().BootstrapContext ` part contains the value but when I tried to get its parameters using `as BootstrapContext` it gives NULL.

**In the above code, I'm getting a NULL value for bc. Any help to resolve this issue?**

PS: I have also posted this issue on [TokenValidationParameters ](https://github.com/aspnet/AspNetKatana/issues/76) error issue thread but since its closed, I created a new issue.

**Comment by Tratcher** [comment]
What is in ClaimsPrincipal.Current.Identities.First().BootstrapContext now? I recall it changed from a BootstrapContext to a string. It may only be your cast failing.

**Comment by GauravDhavale** [comment]
yes, It contains some token value of type object string. 
 ![image](https://user-images.githubusercontent.com/24877974/36122679-d31fa09a-100f-11e8-97a0-cd6e8fa009a8.png)

As BootstrapContext image: 
![image](https://user-images.githubusercontent.com/24877974/36122734-0f889a64-1010-11e8-8e9e-12e1660cd8ed.png)

![image](https://user-images.githubusercontent.com/24877974/36122861-80276f20-1010-11e8-87d0-fd7348fa6895.png)

How shall I get the token value from `BootstrapContext`?

**Comment by Tratcher** [comment]
Is that string the userAccessToken you're looking for? Can you consume it directly?

**Comment by GauravDhavale** [comment]
Well, I don't think I will be able to consume it directly. I compare the payload data of Bearer access token and bootstrapContext value. 

I checked the below variable value which is in Startup.Auth.cs
![image](https://user-images.githubusercontent.com/24877974/36134578-40803696-104b-11e8-903c-e2fd26b59e34.png)

AuthenticationResult is from Microsoft.IdentityModel.Clients.ActiveDirectory. 

It contains the below value. 
![image](https://user-images.githubusercontent.com/24877974/36134557-1c8802c8-104b-11e8-938f-652ce17f5fcc.png)

**Comment by Tratcher** [comment]
@brentschmaltz do you follow what's going on here?

**Comment by GauravDhavale** [comment]
I used the BootstrapContext value directly in the `userAssertion`. It helps to get the `AccessToken`. 

```
  private Task GetTokenViaBootStrap()
        {
            return Task.Run(async () =>
            {
                var bc = ClaimsPrincipal.Current.Identities.First().BootstrapContext;// as BootstrapContext;
                string userName = ClaimsPrincipal.Current.FindFirst(ClaimTypes.Upn) != null ? ClaimsPrincipal.Current.FindFirst(ClaimTypes.Upn).Value : ClaimsPrincipal.Current.FindFirst(ClaimTypes.Email).Value;
                UserAssertion userAssertion = new UserAssertion(bc.ToString(), "urn:ietf:params:oauth:grant-type:jwt-bearer", userName);
                string userObjectID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
                string signedInUserID = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;
                Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext authContext = new Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext(authority);
                ClientCredential cred = new ClientCredential(clientId, appKey);
                result = await authContext.AcquireTokenAsync("https://graph.microsoft.com", cred, userAssertion);
                string UserAccessToken = result.AccessToken;
            });

        }
```

**Comment by brentschmaltz** [comment]
@GauravDhavale I had missed this. Is this still an issue?
If so can you open an issue here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
