### ISSUE TITLE
Facebook Login HTTPS redirect uri

### ISSUE THREAD

**Issue by coultonluke** [aspnet/AspNetKatana#168]
Facebook is recommending that I use a HTTPS redirect URL, instead of HTTP. I've been trying to find a way to configure it to generate a HTTPS URL, at the moment it's generating a HTTPs URL.

https://www.facebook.com/v2.8/dialog/oauth?response_type=code&client_id=255162614498922&redirect_uri=http://example.com/signin-facebook&scope=&state=-x4AVtFysadfadsfsadROH6E1QJ82gv4e4j48s32K5xbmqlF-JFbE5Y2Tx_MAdSquCP6CjZjic8Ye6gwasdfdfask3PXWkyxS42Ajpks9IuumDOl6CUJsadfafsasfdasdfbfpEFUDyxJUR3fARlWc83Lysadffdsdaffsdafasdsdafx_ziTnttz

Currently it is generating: http://example.com/signin-facebook for the redirect_uri, but I'd like a HTTPS URL to redirect the user to.

Is there a way to configure it to generate a HTTPS URL?

This relates to packages Microsoft.Owin.Security and Microsoft.Owin.Security.Facebook.

Currently my OwinStart looks like this:

```
public class OwinStart
{
    public void Configuration(IAppBuilder app)
    {
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Welcome")
            });

            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

            // Configure Facebook authentication
            app.UseFacebookAuthentication(new FacebookAuthenticationOptions
            {
                AppId = ConfigurationManager.AppSettings["FacebookAppId"],
                AppSecret = ConfigurationManager.AppSettings["FacebookAppSecret"]
            });
    }
}
```
Also, there doesn't appear to be a way of Forcing HTTP within the FacebookAuthenticationOptions class or from the Challenge() method that instigates the redirect to Facebook:

```
internal class ChallengeResult : HttpUnauthorizedResult
{
    // TODO: Specify an XsrfKey?
    private const string XsrfKey = "SomethingHere";

    public ChallengeResult(string provider, string redirectUri)
        : this(provider, redirectUri, null)
    {
    }

    public ChallengeResult(string provider, string redirectUri, string userId)
    {
        this.LoginProvider = provider;
        this.RedirectUri = redirectUri;
        this.UserId = userId;
    }

    public string LoginProvider { get; set; }
    public string RedirectUri { get; set; }
    public string UserId { get; set; }

    public override void ExecuteResult(ControllerContext context)
    {
        var properties = new AuthenticationProperties { RedirectUri = this.RedirectUri };

        if (this.UserId != null)
        {
            properties.Dictionary[XsrfKey] = this.UserId;
        }

        context.HttpContext.GetOwinContext().Authentication.Challenge(properties, this.LoginProvider);
    }
}
```

**Comment by Tratcher** [comment]
It generates that URL based on your current request. The most intimidate question is why aren't your authenticated endpoints already requiring HTTPS? E.g. [RequireHttps]

**Comment by coultonluke** [comment]
Thank you for the lightening quick response.  

My servers are behind a load balancer, it is shit that this handles the HTTPS connection and my servers serve traffic through it over HTTP only.  I have a redirection rule that forces redirection from HTTP to HTTPS based on the connection header being returned from the load balancer.  As far as MVC is concerned, it is communicating over HTTP rather than HTTPS (other than the redirect to HTTPS through the rewrite rule).

Thanks for any advice with regards to this.

**Comment by Tratcher** [comment]
Reverse proxies commonly forward you the original scheme in a request header x-forwarded-proto. You can do a basic middleware ahead of security to read those headers and apply them to your request. Several components will function better if they're given accurate information.

**Comment by coultonluke** [comment]
Currently I am using that header in order to perform a redirect to HTTPS.  So you're saying there's a supported way to configure ASP.NET MVC to work without a redirect rule from HTTP to HTTPS?

**Comment by Tratcher** [comment]
No, you should keep the https redirect. To get FacebookAuth to generate the correct urls you should do read x-forwarded-scheme and set the request scheme. E.g.
```
app.Use((context, next) =>
{
  if (context.Request.Headers["x-forwarded-proto"] == "https")
  {
    context.Request.Scheme = "https";
  }
  return next();
});
// Use Cookies
// Use Facebook
```

**Comment by coultonluke** [comment]
Fantastic, that has done the trick.  Thank you for your help!

**Comment by EdSF** [comment]
A key item in the above is that it is **necessary** do this if your application offloads SSL (to SSL concentrator/load balancer, etc) as stated in the [SO answer](https://stackoverflow.com/a/48794939/304683)

- The traffic between end user to your site is SSL (hits SSL concentrator/load balancer)
- The traffic between SSL concentrator/lb and your application is `http`
- therefore your application's context is `http`

So your app **must** force it's context to https _without_ doing things like `HttpRequest.IsSecureConnection` or similar - that will never be `true` and results in a redirect loop.
