### ISSUE TITLE
'TokenValidationParameters' no longer in 'System.IdentityModel.Tokens'

### ISSUE THREAD

**Issue by onionhammer** [aspnet/AspNetKatana#170]
We cannot upgrade to the latest `System.IdentityModel.Tokens.Jwt` because the Owin OpenID Connect library still references the old library, but doesnt declare it as a specific versioned dependency, which results in this:

Where it has no idea where this type is defined.

![image](https://user-images.githubusercontent.com/969938/36211177-2157bafc-1166-11e8-8cf6-513ecb2c8bb8.png)

**Comment by Tratcher** [comment]
Which version of OIDC are you using?
TokenValidationParameters is in the Microsoft.IdentityModel.Tokens package and namespace, Which OIDC has a direct reference to: https://www.nuget.org/packages/Microsoft.Owin.Security.OpenIdConnect/4.0.0-preview1

**Comment by onionhammer** [comment]
@Tratcher This is version 3.1.0 of Microsoft.Owin.Security.OpenIdConnect, along with version 5.2.1 of `System.IdentityModel.Tokens.Jwt`. The latest compatible version of `Sysatem.IdentityModel.Tokens.Jwt` appears to be `4.0.4.x`, but the Dependencies of Microsoft.Owin.Security.OpenIdConnect indicate that it should work with anything >= 4.0.0

![image](https://user-images.githubusercontent.com/969938/36220787-81c84300-1181-11e8-8e29-426388fd8a57.png)

**Comment by Tratcher** [comment]
OIDC 3.1.0 can't be used with IdentityModel 5.x due to breaking changes. You need to move to OIDC 4.0.0 preview.

**Comment by onionhammer** [comment]
@Tratcher which package is that?

**Comment by Tratcher** [comment]
OIDC = Microsoft.Owin.Security.OpenIdConnect, but you should update all of the Microsoft.Owin packages.

**Comment by onionhammer** [comment]
@Tratcher Not sure I follow... 3.1.0 is the latest published version of `Microsoft.Owin.Security.OpenIdConnect`, there are no previews published

**Comment by onionhammer** [comment]
Okay, so it sounds like you guys have already resolved this issue in the preview? I will close this issue then.

Any clues when OIDC 4.0 come out of preview?

**Comment by onionhammer** [comment]
Actually.. there is no corresponding 4.0 preview for `Microsoft.Owin.Security.Jwt`

**Comment by Tratcher** [comment]
4.0.0 is now out of preview. https://www.nuget.org/packages/Microsoft.Owin/4.0.0

**Comment by joviledog** [comment]
Are you said that there are methods in OWIN that could replace the role of the TokenValidationParameters functionality?  Please provide guidance.
