### ISSUE TITLE
Fails to load SystemWeb if OutputPath is different than Default (.\bin)

### ISSUE THREAD

**Issue by aateeque** [aspnet/AspNetKatana#172]
In an ASP.NET 5 project changing the default `OutputPath` from `.\bin` to something else (like `..\.output\service`) causes:

```c#
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
Server Error in '/' Application.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Owin.Host.SystemWeb' or one of its dependencies. The system cannot find the file specified.

Source Error: 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
```

This is when running (F5) from Visual Studio in iisexpress. From the Fusion log it appears that the initial `PrivatePath` is set to `$(MSBuildThisFileDirectory)\bin` where obvioulsy the `bin` isn't anymore. 

Digging deeper, I can see that IIS traces the exception from `ManagedPipelineHandler` with `Notification | MAP_REQUEST_HANDLER`

What is the issue here?

**Comment by Tratcher** [comment]
ASP.NET 5? You mean ASP.NET Core? These components are not supported in Core. Or were you referring to ASP.NET 4.5?

**Comment by aateeque** [comment]
Sorry, meant ASP.NET 4.5 - mvc5

**Comment by Tratcher** [comment]
Ah, that makes more sense. I don't know what's wrong with it, but I do wonder why you changed it?

**Comment by aateeque** [comment]
I want you get Debug and Release builds output in different folders. 
Besides changing OutputPath is just normal feature of msbuild

**Comment by Tratcher** [comment]
I talked to the tooling team and they said this is a general requirement of ASP.NET 4.5 apps, app dlls must be in the bin folder. Closing as by-design.

**Comment by aateeque** [comment]
Is this documented anywhere?

**Comment by Tratcher** [comment]
@BillHiebert ?

**Comment by BillHiebert** [comment]
There is this https://msdn.microsoft.com/en-us/library/cc295391.aspx
