### ISSUE TITLE
Upgrading from 3.1.0 to 4.0.0

### ISSUE THREAD

**Issue by dimkanewtown** [aspnet/AspNetKatana#176]
Is there any documentation on what to expect when upgrading to version 4.0.0? Release notes would help as well. 

Thanks.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/AspNetKatana/wiki/Roadmap

**Comment by dimkanewtown** [comment]
Ah, I see the release notes are in the roadmap itself. Thank you!

**Comment by dimkanewtown** [comment]
For anyone else looking for it see this link:
[https://github.com/aspnet/AspNetKatana/wiki/Roadmap#400-release-february-2018](url)
