### ISSUE TITLE
Weird automatic queuing for identical GET requests?

### ISSUE THREAD

**Issue by KevivL** [aspnet/AspNetKatana#177]
I'm using microsoft.owin.host.httplistener v4.0 with the rest of the OWIN selfhost pipeline. Testing on a win7 desktop at the moment.

If i have a slightly long running controller like so:

        [HttpGet]
        [Route("wait")]
        public async Task<IHttpActionResult> Wait()
        {
            System.Console.WriteLine("Not Started");
            await Task.Delay(20000);
            return Ok();
        }

Multiple calls from the same host are immediately queued and never enter the controller in parallel.
I do see concurrent execution in cases of - a different host, different url (adding in a random query string), and funnily enough on a POST request (up to 5).

Looks like a fairness/scheduling thing in the selfhost? Possibly in the listener? It makes sense for the general use case but is there any way to control/modify this behavior?

I do have a controller in production where this is a bit of an issue, some requests can take a second or two to return so in the case of multiple requests from the same host they simply get queued up instead of going concurrently and i don't have any intervention open on my end to fix the specific case because it never even enters the controller.

I can inject a middleware but that can at best reject/debounce the subsequent requests but can't force concurrent execution?

**Comment by Tratcher** [comment]
There's no queuing model like this on the server. Are you sure the queuing isn't happening on the client? E.g. If all of the requests are queued on the same connection then they can't be executed concurrently. What client are you using?

**Comment by Tratcher** [comment]
How is if if you open two different browsers? E.g. Firefox and Chrome?

**Comment by KevivL** [comment]
One start per browser. Only had firefox and chrome so opened three tabs each. One entry from each side with the remaining two starting only after the previous one exited...

**Comment by Tratcher** [comment]
Yes, that sounds like client connection level queuing. A Fiddler or network trace would show this better.

**Comment by KevivL** [comment]
Yup. I did fiddler and saw the browser caching. Tested with a c# client. There's no such behavior, was just a browser feature causing me to think so. Sorry again for the bother. Closing now.
