### ISSUE TITLE
Microsoft.Owin.Security.ActiveDirectory 4.0 does not work after update

### ISSUE THREAD

**Issue by Daniel-Svensson** [aspnet/AspNetKatana#178]
After upgrade to 4.0 we could no login access our web server protected by Microsoft.Owin.Security.ActiveDirectory

It seems like Microsoft.Owin.Security.ActiveDirectory 4.0 contains a reference to Microsoft.IdentityModel.Protocols.WsFederation Version 5.2.0.0 but the nuget package does not contains a dependency to it.
The package already contains a dependency to System.IdentityModel.Tokens.Jwt so it should be easy to add an additional dependency to Microsoft.IdentityModel.Protocols.WsFederation.

Solution:
 * Add a package dependency to Microsoft.IdentityModel.Protocols.WsFederation in the nuspec at 
https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.ActiveDirectory/Microsoft.Owin.Security.ActiveDirectory.nuspec

Workaround:

* Install Microsoft.IdentityModel.Protocols.WsFederation manually

**Comment by Tratcher** [comment]
You're correct, we missed adding those new dependencies to the nuspec. Luckily the workaround is easy.

@muratg We may need to patch this.
