### ISSUE TITLE
No owin.Environment item was found in the context in IIS Web Farm ARR hosting

### ISSUE THREAD

**Issue by kolte** [aspnet/AspNetKatana#179]
I am trying to set load balancing with IIS ARR but getting this error when I try to login, It works fine if I test it outside ARR

Server Error in '/' Application. No owin.Environment item was found in the context. Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: No owin.Environment item was found in the context.

**Comment by Tratcher** [comment]
Stack trace? Code?

**Comment by kolte** [comment]
Server Error in '/' Application.
No owin.Environment item was found in the context.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: No owin.Environment item was found in the context.

Source Error: 


Line 21:             get
Line 22:             {
Line 23:                 return this._userManager ?? this.HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
Line 24:             }
Line 25:             private set

Source File: D:\Projects\Other\Project\Project\Project.Web\Controllers\BaseController.cs    Line: 23 

Stack Trace: 


[InvalidOperationException: No owin.Environment item was found in the context.]
   System.Web.HttpContextBaseExtensions.GetOwinContext(HttpContextBase context) +100
   Project.Web.Controllers.BaseController.get_UserManager() in D:\Projects\Other\Project\Project\Project.Web\Controllers\BaseController.cs:23
   Project.Web.Controllers.<Login>d__19.MoveNext() in D:\Projects\Other\Project\Project\Project.Web\Controllers\AccountController.cs:321
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +60
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +92
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +385
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +385
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +185
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +70
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +393
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +195
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2633.0

**Comment by kolte** [comment]
Thanks in Advance, I am not really sure why it's not working with ARR load balancing. did you get chance to look at this issue please? Thank you again.

**Comment by Tratcher** [comment]
@kolte this isn't any environment we have much experience with. Can you describe your setup more? The Web Farm framework is described as an obsolete configuration. https://blogs.iis.net/iisoobs, https://forums.iis.net/t/1237081.aspx?Web+Farm+ARR+Setup+for+IIS+10+and+Server+2016+

**Comment by Tratcher** [comment]
If you're really stuck then your best bet is to contact Microsoft Support.

**Comment by kolte** [comment]
Thank you, sorry
