### ISSUE TITLE
Does Microsoft.Owin.Security.OpenIdConnect 5.2.1 support ASP.NET 4.x?

### ISSUE THREAD

**Issue by JohanPetersson** [aspnet/AspNetKatana#180]
I'm running a ASP.NET 4.7.2 application and installed Microsoft.Owin.Security.OpenIdConnect 4.0.0. This package has a dependency to System.IdentityModel.Tokens.Jwt 5.2.1. The documentation for this package clearly states that this version doesn't support ASP.NET 4.x. System.IdentityModel.Tokens.Jwt Version 4.x  is only supported in ASP.NET 4.x and 5.x is only supported in .NET Core.

This is very confusing and in my opinion this doesn't follow semantic versioning. Why wasn't a new package with a new id for System.IdentityModel.Tokens.Jwt introduced instead that supports .NET Core? And does this mean that we shouldn't install Microsoft.Owin.Security.OpenIdConnect 4.0.0 in ASP.NET 4.x projects and downgrade to 3.1.0?

The project seems to run fine with System.IdentityModel.Tokens.Jwt 5.2.1 though.

**Comment by Tratcher** [comment]
Note the latest version of Microsoft.Owin.Security.OpenIdConnect is 4.0.0, not 5.2.1. 

The readme at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/ is out of date and being updated (@brentschmaltz). IdenitytModel version 5 made breaking changes such that it was no longer compatible with Microsoft.Owin.* 3.x. Microsoft.AspNetCore.* was developed using IdentityModel version 5. Microsoft.Owin.* 4.0 has been updated to support IM 5. It was never about .NET vs .NET Core, only about version mismatches.

**Comment by JohanPetersson** [comment]
You are correct, we have 4.0.0 installed. I've updated my first message.

Ah ok, so then we should be fine. Thank you.

**Comment by sudarshan1933** [comment]
Hi,
Can anyone please help me in this issue? 

https://stackoverflow.com/questions/50891611/implement-openid-connect-authetication-in-asp-net-web-api

I am stuck from lastweek. Thanks in Advance.

**Comment by Engineerumair** [comment]
Is Microsoft.Owin.Security.OpenIDConnect supported in .Net 4.0 if not then how can we use OIDC in webforms app based on .Net 4.0?

**Comment by Tratcher** [comment]
The latest version supports .Net 4.5.1.

**Comment by Engineerumair** [comment]
can we use the previous versions with .net 4.0?

**Comment by Tratcher** [comment]
No. You would need to go back to version 2.1 to get .net 4.0 support (5 years old), and that was before we developed OpenIdConnect. Why do you need 4.0? 4.5 is [6 years old](https://en.wikipedia.org/wiki/.NET_Framework#Release_history) and has been installed by default since Windows 8.

**Comment by Engineerumair** [comment]
Because of Existing application
