### ISSUE TITLE
How to get the facebook token expiration date

### ISSUE THREAD

**Issue by walidboum** [aspnet/AspNetKatana#181]
I am using the owin facebook auth middlware for my service. Using the appId and app secret, my service is successfully getting a facebook token for the user. (upon successful auth from the user on the facebook portal).

Let's say now I want to check when a specific facebook token is going to expire and issue a refresh. 
Facebook has an api to get information about the token: https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension 

GET /debug_token?
  input_token={input-token}&
  access_token={access-token}

The problem here is that I haven't found the place where the access_token is stored in the facebook auth provider. The app access token that was used to obtain the user's token.

Can you please help?

**Comment by Tratcher** [comment]
The token isn't stored by default, it's only used to fetch the user information. If you want to extend that functionality you need to hook into the [provider](https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security.Facebook/Provider/FacebookAuthenticationProvider.cs#L28) and store the token and expiration somewhere. Storing it in the AuthenticationProperties is a short term option to flow it back to your login endpoint for more permanent storage.
