### ISSUE TITLE
User is not authenticated when we clear the browser history

### ISSUE THREAD

**Issue by nighotatul** [aspnet/AspNetKatana#182]
We have implemented OWIN authentication in our module and are successfully implemented for windows authentication in our asp.net web-form application. The strange behaviour happening when we clear history of browser and again login then user is not authenticated and because of user is not authenticated, our application redirect to a login page.

These behaviour only happen when browser history is clear if we not clear the browser history then application running without redirect to login page.

At that time we close the browser and we again clean and rebuild our application and run it again then user is authenticated and we successfully redirect to other page.

**Comment by Tratcher** [comment]
Can you share a Fiddler trace with of the repro?

This sounds like a usage question more appropriate for a forum like StackOverflow.
