### ISSUE TITLE
Cannot remove the "Server" Header

### ISSUE THREAD

**Issue by vslepakov** [aspnet/AspNetKatana#183]
Hi,

we use OWIN self host and for security reasons we would like to remove the Server header (Microsoft-HTTPAPI/2.0) from the response. 

How to achieve this?

Thanks and best regards

**Comment by Tratcher** [comment]
FYI removing the server header is an ineffective security measure.

Microsoft.Owin uses System.Net.HttpListener, you'll need to search for solutions involving that component. I'm not aware of any simple solutions.
