### ISSUE TITLE
Which .NET version ?

### ISSUE THREAD

**Issue by mpoirier101** [aspnet/AspNetKatana#184]
Trying to update the package version from 3.1.0 to 4.0.0 I get this message.

Could not install package 'Microsoft.Owin 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I just cannot find what is the .NET version requirement anywhere...

Thanks !

**Comment by CZEMacLeod** [comment]
Not sure what changed, but `Microsoft.Owin 4.0.0` requires net451 or higher.

**Comment by Eilon** [comment]
@mpoirier101 can you post what your CSPROJ looks like so that we can try to reproduce this behavior?

**Comment by Tratcher** [comment]
@CZEMacLeod is correct, the packages require 4.5.1 now.

**Comment by mpoirier101** [comment]
Thanks ! 

This is what I needed to know (4.5.1). I just could not find this info anywhere...
