### ISSUE TITLE
Support AuthenticationOptions modification per request

### ISSUE THREAD

**Issue by xperiandri** [aspnet/AspNetKatana#185]
I want to authenticate ASP.NET OWIN app using OpenIdConnect provider.
My app is multi-tenant and tenant is distinguished by subdomain.

There is an ability to do some stuff before request is sent on RedirectToIdentityProvider event. And it even exposes Options that are mutable. Which leads to [crazy stupid errors](https://github.com/IdentityServer/IdentityServer3/issues/1458#issuecomment-110178584)

Pay attention to my comments in this snippet

``` C#
OpenIdConnectAuthenticationOptions openIdConnectOptions = null;
openIdConnectOptions = new OpenIdConnectAuthenticationOptions
{
    Authority = authority,
    ClientId = clientId,
    ClientSecret = clientSecret,
    RedirectUri = "signin-oidc",
    PostLogoutRedirectUri = "signout-oidc",
    ResponseType = string.Join(" ", new string[]
                {
        OpenIdConnectConstants.ResponseTypes.Code,
        OpenIdConnectConstants.ResponseTypes.IdToken,
        OpenIdConnectConstants.ResponseTypes.Token
                }),
    Scope = string.Join(" ", new string[]
                {
        OpenIdConnectConstants.Scopes.OpenId,
        OpenIdConnectConstants.Scopes.Email,
        OpenIdConnectConstants.Scopes.Profile,
        OpenIdConnectConstants.Scopes.OfflineAccess
                }),

    TokenValidationParameters = new TokenValidationParameters
    {
        NameClaimType = OpenIdConnectConstants.Claims.Email,
        RoleClaimType = OpenIdConnectConstants.Claims.Role
    },

    SignInAsAuthenticationType = "Cookies",

    Notifications = new OpenIdConnectAuthenticationNotifications
    {
        AuthorizationCodeReceived = async n =>
        {
		...
        },

        RedirectToIdentityProvider = n =>
        {
            // SAME MUTABLE INSTANCE
            bool equals = object.ReferenceEquals(n.Options, openIdConnectOptions);

            Uri requestUri = n.Request.Uri;
            var options = n.Options;
            
            // I MUTATE IT
            // IMAGINE WHICH CRAZY MULTITHREADING ERRORS CAN HAPPEN!!!
            options.RedirectUri = requestUri.ToString() + "signin-oidc";
            options.PostLogoutRedirectUri = requestUri.ToString() + "signout-oidc";
            options.Resource = TenantHelper.GetTenantName(requestUri);

            // if signing out, add the id_token_hint
            if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
            {
                var idTokenHint = n.OwinContext.Authentication.User.GetClaim(OpenIdConnectConstants.Parameters.IdToken);

                if (idTokenHint != null)
                {
                    n.ProtocolMessage.IdTokenHint = idTokenHint;
                }
            }

            return Task.CompletedTask;
        }
    }
};
app.UseOpenIdConnectAuthentication(openIdConnectOptions);
```

You must protect average user from such errors!!! It is a very bad and inflexible design!!!
____________

I think it architecture must be redesigned to fix this design issue and allow to modify options per request.

My proposal 1:
1. Make options clonable
2. Change this line to pass options clone https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security/Infrastructure/AuthenticationMiddleware.cs#L27

My proposal 2:
1. Make all options read only
2. Change to `protected set` https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler%601.cs#L14
3. Change to `set`
https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security/Provider/BaseContext%601.cs#L19
4. Add `Options = notification.Options;` after
https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L93
https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L164

**Comment by Tratcher** [comment]
Multi tennancy is a non-goal for this project. If you have a finite number of tenants then you can add a middleware instance for each of them (but remember to give them unique CallbackPaths) and challenge then by name. For anything more complex I recommend you fork the code and customize as needed.

**Comment by xperiandri** [comment]
Even if it is not the goal leaving mutable shared options instance is stupid idea if not to say worse.

**Comment by xperiandri** [comment]
Do you think that eliminating hours of research and production issues of guy like this
https://github.com/IdentityServer/IdentityServer3/issues/1458#issuecomment-110178584
don't worth a little change from proposal 1 or 2?

So my question is pull request for each my options can be accepted if no other proposals be discussed?

**Comment by Tratcher** [comment]
Neither of these proposals are suitable, cloning the options on every request would be grossly inefficient. What you really need for a scenario like this is a cached set of options and the ability to look them up per request. ASP.NET Core 2.0 has a some of the necessary infrastructure for that, but it would require a significant overhaul to port it over here.

**Comment by xperiandri** [comment]
Could you point me to that you mean?

**Comment by Tratcher** [comment]
Core has a service called IAuthenticationSchemeProvider that can be used to add, cache, and remove providers. If you override this you can even created providers on the fly such as for lazy multi-tenant scenarios. 
https://github.com/aspnet/AuthSamples/blob/40f7347337850304c1cfeed0b3db0c0ca5176a39/samples/DynamicSchemes/Controllers/AuthController.cs
https://github.com/aspnet/HttpAbstractions/blob/e5cffe685bdf6d2f5e6182385cf6626f444d9a0a/src/Microsoft.AspNetCore.Authentication.Abstractions/IAuthenticationSchemeProvider.cs

You still have to implement the multi-tenant part yourself, but at least there's a place to do it.

**Comment by xperiandri** [comment]
Ah, just use different schemes

**Comment by xperiandri** [comment]
OK, let's do something with what we have now here

I can do this. And add cache here. But as you can see that 2 methods are internal.
Can thy become public?
``` C#
internal class TenancyOpenIdConnectAuthenticationMiddleware : OpenIdConnectAuthenticationMiddleware
{
    static readonly object[] emptyParameters = new object[0];
    static readonly MethodInfo Initialize;
    static readonly MethodInfo TeardownAsync;

    static TenancyOpenIdConnectAuthenticationMiddleware()
    {
        var type = typeof(AuthenticationHandler<OpenIdConnectAuthenticationOptions>);
        Initialize = type.GetMethod("Initialize");
        TeardownAsync = type.GetMethod("TeardownAsync");
    }

    public TenancyOpenIdConnectAuthenticationMiddleware(OwinMiddleware next, IAppBuilder app, OpenIdConnectAuthenticationOptions options)
        : base(next, app, options) { }

    public override async Task Invoke(IOwinContext context)
    {
        AuthenticationHandler<OpenIdConnectAuthenticationOptions> handler = CreateHandler();
        await (Initialize.Invoke(handler, new object[] { Options.Copy(), context }) as Task);
        if (!await handler.InvokeAsync())
        {
            await Next.Invoke(context);
        }
        await (TeardownAsync.Invoke(handler, emptyParameters) as Task);
    }
}
```

**Comment by Tratcher** [comment]
Which methods specifically?

You're still copying the options...

I should warn you that we have no scheduled releases for these packages at the moment. Even if we changed something here there's no telling when it would be released.

**Comment by xperiandri** [comment]
I thought it is absolutely deducible from by sample where I get them using reflection.

https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler%601.cs#L22

https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler.cs#L93

**Comment by Tratcher** [comment]
We don't have plans to design or build this functionality right now.

**Comment by jpablosierral** [comment]
Thanks for answer Tratcher!
regards.

**Comment by stilbu** [comment]
> Hello,
> about this issue, I would like to add something:
> We want to make our app multi authority, so we need to change the authority dynamically (more or less is the same problem).
> 
> What do you think about create a new event to handle this? Something like 'OnRequestAuthority', and inside we could do "what we need"?
> 
> I think that this not break anything or generates big problems.
> 
> Regards.

Have you ever found a solution for this? I am trying to figure one out, but no success yet.

**Comment by clklachu** [comment]
> Hello,
> about this issue, I would like to add something:
> We want to make our app multi authority, so we need to change the authority dynamically (more or less is the same problem).
> 
> What do you think about create a new event to handle this? Something like 'OnRequestAuthority', and inside we could do "what we need"?
> 
> I think that this not break anything or generates big problems.
> 
> Regards.

Hello,

Any solution or direction on this? I'm also in the same multi tenant situation , but no success yet. Please share some info
