### ISSUE TITLE
NameClaimType Doesn't Seem like Validation in TokenValidationParameters

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/AspNetKatana#186]
Apparently one must configure where to get the user's name claim from so that they can perform operations like `var name = User.Identity.Name;`

In the following [Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/blob/cf011352babed2685c9c324e308a2b8775640c2b/TaskWebApp/App_Start/Startup.Auth.cs#L78) example, the value is configured via `TokenValidationParameters`.

That doesn't feel right to me.  It is not validating the name claim, it is telling it where to find it, no?

```csharp
app.UseOpenIdConnectAuthentication(
	new OpenIdConnectAuthenticationOptions
	{
		// Generate the metadata address using the tenant and policy information
		MetadataAddress = String.Format(AadInstance, Tenant, DefaultPolicy),

		// These are standard OpenID Connect parameters, with values pulled from web.config
		ClientId = ClientId,
		RedirectUri = RedirectUri,
		PostLogoutRedirectUri = RedirectUri,

                ....

		// Specify the claims to validate
		TokenValidationParameters = new TokenValidationParameters
		{
			NameClaimType = "name"
		},
	}
);
```

---

[nameClaimType](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/windows-identity-foundation/nameclaimtype)

>Sets the claim type that specifies the Name property. The claim type is used to search for a Claim in the collection of ClaimsIdentity objects returned by the ValidateToken method of this token handler. The value of the matching claim is then set as the name of the IIdentity generated from this token handler.

---

Reference: [Azure AD B2C: User.Identity.Name is null, but User.Identity.m_instance_claims[9] has the name](https://stackoverflow.com/a/49470129/185123)

**Comment by Tratcher** [comment]
TokenValidationParameters is used both to configure the validation for the incoming token and to configure mapping that data into a ClaimsIdentity, both of these operations take place in the same IdentityModel API. You can learn more about TokenValidationParameters over at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/

**Comment by spottedmahn** [comment]
Gotcha, that's what it seemed like.  Thanks @Tratcher.  Validation **and** configuration.

IMHO, this comment should be updated as such

https://github.com/aspnet/AspNetKatana/blob/64bf627964ca9bd312cfda31916194212731c11c/src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs#L263

Thoughts?

**Comment by Tratcher** [comment]
Feel free 😁
