### ISSUE TITLE
Add response_mode=query support for OpenID Connect

### ISSUE THREAD

**Issue by vpwilson** [aspnet/AspNetKatana#189]
I trying to use AWS Cognito as IDP but response_mode = query isn't currently supported  in AspNetKatana whereas it is supported in asp.net core implementation, please refer the link below. https://github.com/aspnet/Security/pull/279/commits/54128e813748e5143b3827c834a5b05cedd05916
Regards,
Vinod

**Comment by muratg** [comment]
We do not plan to add more features to Katana. Closing this.
