### ISSUE TITLE
OpenIdConnect Authorization code flow

### ISSUE THREAD

**Issue by adefalque** [aspnet/AspNetKatana#191]
Is there any chance to see the support of OpenIdConnect authorization code flow in a near future?
I understand it is already implemented in AspNet Core, but of course it's not an option for a legacy project.

If not, would a small modification in AuthenticateCoreAsync method possible to allow a response without Id token but just a code? It would be then the responsibility of the developer to redeem the token from the AuthorizationCodeReceived notification.

Best,
Alex

**Comment by adefalque** [comment]
Thanks, is it something on the roadmap though?
I have a working implementation of code flow, do you think I could submit it as a pull request?
It's mostly based on the Asp.Net Core implementation, trying to minimize code changes.

**Comment by Tratcher** [comment]
No this isn't on the roadmap right now and we don't have any scheduled releases in the near term. You can submit the PR for discussion but I don't know when we'd ship it.

**Comment by adefalque** [comment]
Ok thanks Chris, I'll submit the PR

**Comment by LangdalP** [comment]
@adefalque Any chance of you making your working implementation of authorization code flow available, for instance as a PR or a fork? My team are looking to start using OpenID Connect with ASP.NET, but hit a road block when we found out that Katana does not support this flow.

**Comment by berhir** [comment]
Hi @adefalque, we are also looking for a way to use the authorization code flow. We will probably fork this repo and make the necessary changes. Do you think you can make your code available on github even if it's not finished yet? That would help us to get started, thank you!

**Comment by Joey523** [comment]
Hello adefalque, LangdalP and berhir, just reaching out to find out if any of you have successfully implemented a solution for the use of authorization code flow? I too just found out that Katana does not support this flow and as such presents a huge roadblock for us. Looking to implement OIDC with ASP.net webforms. Would appreciate it if someone can share their solution. Thanks!

**Comment by adefalque** [comment]
hi guys,

I've just pushed my local code to my cloned repo: https://github.com/adefalque/AspNetKatana/tree/feature/oidauthcode 

Still not ready for a PR and didn't retest it recently, but the idea is there.
Solution is mostly based on Asp.Net Core OpenIdConnect implementation: 
https://github.com/aspnet/Security/tree/master/src/Microsoft.AspNetCore.Authentication.OpenIdConnect

**Comment by muratg** [comment]
@adefalque We're not planning to make any more feature changes to Katana anymore. Thanks for your work on this, and perhaps it'll help someone else too!

**Comment by sixlettervariables** [comment]
@muratg can you update the README to let folks know this project is abandoned? We're fairly disappointed to hear this.
