### ISSUE TITLE
Improvement: CookieValidateIdentityContext.ReplaceIdentity keep ClaimsIdentity instance instead of creating new instance

### ISSUE THREAD

**Issue by MikeJansen** [aspnet/AspNetKatana#194]
Right now `CookieValidateIdentityContext.ReplaceIdentity()` will always set` Identity` to `new ClaimsIdentity(identity)`.  

If the application has implemented a `ClaimsIdentity`-derived class and replaces the identity, the derived class is lost.

`ReplaceIdentity()` should keep the existing instance passed as a parameter if it is a `ClaimsIdentity`, otherwise create a new instance.

I have a pull request I will submit right after I submit this issue.

**Comment by muratg** [comment]
This breaks serialization, so we don't plan to make a change here. Thanks for the PR, but I'll be closing the PR as well. Hopefully you're able to solve your own problem though!
