### ISSUE TITLE
State is not passed back by the OAuth server when redirecting with an error during the implicit_grant flow

### ISSUE THREAD

**Issue by ioi-christianco** [aspnet/AspNetKatana#198]
When implementing an OAuth authorization server, calling OAuthValidateAuthorizeRequestContext.SetError() during the authorize request validation does not include the "state" value provided as a query parameter to the authorize endpoint.
OAuthAuthorizationServerHandler.SendErrorRedirectAsync() will add the error query parameters, but will not append the state parameter from the authorize request.

This is in conflict with https://tools.ietf.org/html/rfc6749#section-4.2.2.1:

>    state
         REQUIRED if a "state" parameter was present in the client
         authorization request.  The exact value received from the
         client.

More concretely, this makes dealing with these error flows harder, as the caller cannot correlate the request when getting the error back.

To reproduce the issue, send an authorize call to an OAuthAuthorizationServer implementation which will validate the client_id and redirectUri, but set an error during the request authorization, for instance as an "unauthorized_client".
If a "state" query parameter is passed through the authorize request, it will not be included alongside the "error" query parameters to the redirect uri.

I will send a PR with an added test case and a proposed fix.

**Comment by PinpointTownes** [comment]
Amusing to see that this bug - known for a loooooooong time - may be finally fixed :smile: 

It's worth noting that fixing that won't be enough to make error responses fully work with the implicit flow. Currently, the callback is made by appending the error/description/uri as query string parameters. Sadly, this is not standard-compliant and they should be added as fragment parameters.
