### ISSUE TITLE
azure deployment - access_denied error 

### ISSUE THREAD

**Issue by ilanArtlist** [aspnet/AspNetKatana#200]
Hi there,
We are facing a strange behavior on azure webapp where we get access_denied error after  a few hours of successful logins.
It seems as if after a while there are too many redirects loop between owing and facebook api (Google as well).  
We are working on mvc5 as SPA hence using owin to create and login users.  
Any input will be appreciated.

startupauth.cs:

`  FacebookAuthOptions = new FacebookAuthenticationOptions()
            {
                AppId = FacebookLoginAppId,
                AppSecret = FacebookLoginAppSecret,
                BackchannelHttpHandler = new FacebookBackChannelHandler(),
                UserInformationEndpoint = "https://graph.facebook.com/v2.12/me?fields=id,email,first_name,last_name",
                Provider = new FacebookAuthProvider()
            };
            FacebookAuthOptions.Scope.Add("email");
            app.UseFacebookAuthentication(FacebookAuthOptions);`

Thanks
Ilan

**Comment by Tratcher** [comment]
Can you capture a Fiddler or network trace of the redirect loops? The most common cause is https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues

**Comment by CarloSaccone** [comment]
Hi, any update here? We're having exactly the same issue: we have a working solution (feel free to try) here:

https://200crowdfe.azurewebsites.net/account/login

When I deploy to the production website, it works for a while (sometimes a few minutes, sometimes hours), then it stops and starts answering "access_denied" with any provider, for any user.

Any idea? How can I debug/log the reason why the access_denied message comes out?
I debugged all the client calls, and the error is inside the final call to /signin-linkedin handler.

Thanks
