### ISSUE TITLE
Update dead link in Wiki

### ISSUE THREAD

**Issue by oleschri** [aspnet/AspNetKatana#202]
As CodePlex pages are not available anymore please edit the Wiki page
https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues
by changing the link
https://katanaproject.codeplex.com/workitem/197
to the archived version
https://web.archive.org/web/https://katanaproject.codeplex.com/workitem/197 .

**Comment by Tratcher** [comment]
Nice link, thanks.
