### ISSUE TITLE
Not installing the package Microsoft.Owin

### ISSUE THREAD

**Issue by fpompies** [aspnet/AspNetKatana#204]
I am creating Hangfire as a windows service. When I try to install Microsoft.Owin.Hosting I get the next error.:
Could not install package 'Microsoft.Owin 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The framework I use is .Net Framework 4.5

**Comment by CZEMacLeod** [comment]
@fpompies Pretty sure it has been mentioned in another issue, and maybe even the release notes for 4.0.0 but Microsoft.Owin 4.0.0 (and many of the related packages) require net451 or higher. 
Change your target framework to net451 and re-install the packages.

**Comment by philjones** [comment]
There are no release notes - not even tagged in releases.

Looking at the roadmap it links to some issues in 4.0.0:
https://github.com/aspnet/AspNetKatana/wiki/Roadmap

One of them is this one which updates the target version to 4.5.1
https://github.com/aspnet/AspNetKatana/issues/14

**Comment by fpompies** [comment]
It works, thnx.

Met vriendelijke groeten / Meilleures salutations / Best regards

Fred Pompies
Senior Software Engineer

**Comment by muratg** [comment]
:+1:
