### ISSUE TITLE
OpenidConnect first request never complete after long time of inactivity

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/AspNetKatana#205]
We use Owin OpenIdConnect for joining our old legacy system to IdentityServer4. 
Sometimes we see that first auth request after long time of inactivity - is never completed. It locked on Owin side, because IdentityServer4 logs are empty. If client press F5 - it works normal and authentication works well.
What the strange behaviour for openid flow? It's not normal to repeat request again.

**Comment by Tratcher** [comment]
You're going to have to be more specific. Which url / action is taking so long? If you attach the debugger were does it say it's stuck?

**Comment by ZOXEXIVO** [comment]
It's difficult to catch and we havent' traces.
We enter project url (running under IIS) and it not redirecting to openid server and site still loading. 
No errors in log.
I think, that problem may be catched by many other developers.

**Comment by ZOXEXIVO** [comment]
I found same issue at AspNetCore library
https://github.com/aspnet/Security/issues/1121

**Comment by muratg** [comment]
Closing this one as dup.
