### ISSUE TITLE
server.OnDispose from common keys recommendation is missing

### ISSUE THREAD

**Issue by binki** [aspnet/AspNetKatana#207]
I can’t find in the source code where the `server.OnDispose` property is supported. I assume that means there is no typed API provided around it.

When I look at http://owin.org/html/CommonKeys.html , it’s there. When I look in this typesafe wrapper API, it appears that the closest thing is https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin/OwinConstants.cs#L72 and https://github.com/aspnet/AspNetKatana/blob/24aa43641adac57cb5bd523b77bdc0ced9f0455d/src/Microsoft.Owin/BuilderProperties/AppProperties.cs#L79-L87 .

I can’t tell from the documentation if the behavior of `server.OnDispose` and `host.OnAppDisposing` is supposed to be identical. If it is, it would make sense for a new typed wrapper of `server.OnDispose` fall back to `host.OnAppDisposing` to support outdated IIS/SystemWeb. If they have different behaviors, it would be helpful for a new typesafe API for `server.OnDispose` to be added and the documentation describe the difference in behavior between the two options and maybe to deprecate `host.OnAppDisposing`.

**Comment by Tratcher** [comment]
Hmm, I don't know where server.OnDispose came from. It wasn't in the earlier CommonKeys I wrote.  Know any servers that implement it?

**Comment by Tratcher** [comment]
And yes, the described functionality is the same.

**Comment by binki** [comment]
@Tratcher 
> Know any servers that implement it?
I don’t. I just stumbled across it at https://github.com/Bobris/Nowin/issues/36#issuecomment-121273979 which states that it is the standard/recommended way to get the token. Maybe that means Nowin implements it, but I haven’t checked it out. I haven’t looked, but I suspect that means it would be good for SystemWeb to be updated to provide it too?

**Comment by Tratcher** [comment]
Last I checked only SystemWeb provided any such functionality, it'd be more straightforward to update the spec.

**Comment by muratg** [comment]
We don't plan to add more features to Katana as it stands now.
