### ISSUE TITLE
Owin breaks URIs with sections containing forward slash

### ISSUE THREAD

**Issue by bosh-b** [aspnet/AspNetKatana#208]
Imagine one has a URI like this: `https://api.domain.com/v1.0/section/faultySection('Parameter%2Fthat%20fails')?queryParameters=params`
(`%2F` encodes a forward slash). Since the slash is treated as a part of a query parameters (though being in segments), it is encoded, so one expects it to be encoded all the time: converting it back will break the meaning of the URI.
If I create an instance of `Uri` class with this URI, I see that `%2F` is retained, at least in some of the properties. That said, it would not be a problem to process that URI as desired.
However, if I call an OWIN service with an URI like that, `IOwinRequest.Uri` property will have the URI with decoded `%2F` all over the place, so that information is lost. That leads to the fact that URI is split to segments in a wrong way, breaking further URI processing.

IOwinRequest instance is built in `OwinHttpListener` using data provided in `System.Net.HttpListenerRequest` object, which, in turn, is provided by `System.Net.HttpListenerContext`, which is returned by `System.Net.HttpListener`.
There is a setting in App.config that controls how forward slash is treated in `System.Net.HttpListener`: 
```
<system.net>
    <settings>
      <httpListener unescapeRequestUrl="false"/>
    </settings>
</system.net>
```
By default that setting has value `true`, and that forces `HttpListener` to decode `%2F`, so that `OwinHttpListener` receives the URI already broken.
Flipping that setting to `false` forces `HttpListener` to retain `%2F` encoded, but `IOwinRequest.Uri` still has wrong value. That leads to the way how that field is constructed.

The field is constructed in `OwinHttpListener.ProcessRequestAsync` method. There, `GetPathAndQuery` method is called, which processes the URI coming from `HttpListenerRequest` object. In this method, there are these lines of code:
```
cookedPath = (string)CookedPathField.GetValue(request) ?? string.Empty;
query = (string)CookedQueryField.GetValue(request) ?? string.Empty;
```
`CookedPathField` is a `FieldInfo` object used to get the value of private `m_CookedUrlPath` field from `HttpListenerRequest` object.

And it's the place where everything happens. Though `HttpListenerRequest` now has proper URI value in `HttpListenerRequest.Url` field (due to the setting), the `m_CookedUrlPath` field **always** has all urlencoded characters decoded. That means as a result, `OwinContext` will always have wrong URI value, independently of the setting.

**Solution**
Changing the code in `GetPathAndQuery` to something like this:
```
cookedPath = request.Url.AbsolutePath;
```
solves the issue (I've tested it adding specific test case to the unit tests).
I doubt it's a proper fix, since there should be a **very** good reason why Reflection is used in first place.

**Workaround**
The proper URI value could always be obtained from original `HttpListenerContext`:
```
var httpListenerContext = (HttpListenerContext)owinContext.Environment["System.Net.HttpListenerContext"];
var url = httpListenerContext.Request.Url;
```

**Comment by Tratcher** [comment]
Nice analysis.

**Comment by muratg** [comment]
Putting this in 4.0.1 for investigation.

**Comment by Tratcher** [comment]
I found the tests that cover this [here](https://github.com/aspnet/AspNetKatana/blob/dev/tests/Microsoft.Owin.Host.IntegrationTests/PathEscapingTests.cs#L51-L59). The current behavior exists to avoid cases such as double un-escaping %25. Escaped # and ? also get messed up and break the URI structure. These workarounds got us rough parity with System.Web. We wouldn't risk regressing that.

Specific test results if I swap the behavior to match the mono code path (cleaned up for readability):
```
VerifyUnescapedPercent:
Expected: /%41/
Actual:   /A/

VerifyUnescapedPercent:
Expected: /%&*+:<>?
Actual:   /%25&*+:<>

VerifyUnescapedCharacters:
Expected: / !"#$'(),.-/0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{|}~
Actual:   / !"
```

I'm closing this as we do not plan to change it.
