### ISSUE TITLE
Enable SourceLink for easier debugging

### ISSUE THREAD

**Issue by MagicAndre1981** [aspnet/AspNetKatana#211]
### Expected  behavior

Press F11 to step into code and debug the code

### Actual behavior

because no PDBs + source info are found, debugger steps over

### Solution: 

[enable SourceLink](https://github.com/dotnet/sourcelink#using-sourcelink) to [fetch the source from github](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#source-link-file-specification) during debugging to be able to step into the code.

**Comment by Tratcher** [comment]
Related to https://github.com/aspnet/AspNetKatana/issues/237

**Comment by Tratcher** [comment]
Dropping this for 4.0.1, it's going to require a significant infrastructure overhaul.

**Comment by anurse** [comment]
We'll take a quick look at this for 4.1.0, but it'll be time-boxed.

**Comment by MagicAndre1981** [comment]
ok, I moved to Core version some time ago so this has no priority for me. But maybe others benefit from it.

**Comment by Tratcher** [comment]
All of the infrastructure and guidance for SourceLink is based on SDK style project files. Converting Katana over is a bigger task than we wanted to tackle in 4.1.0 so this got moved to the backlog.

**Comment by MagicAndre1981** [comment]
> Source Link supports **classic .NET Framework projects** as well as .NET SDK projects

So it doesn't matter which project style you use

**Comment by Tratcher** [comment]
@MagicAndre1981 Can you share any docs or samples for that scenario? I didn't see any.

**Comment by MagicAndre1981** [comment]
I only [quoted the source link documentation](https://github.com/dotnet/sourcelink#prerequisites-for-net-projects). 

Add the entries to the Release Configuration PropertyGroup

**Comment by Tratcher** [comment]
Fixed by moving to arcade.
