### ISSUE TITLE
ARR + owin problem with POST requests

### ISSUE THREAD

**Issue by hakonfjukstad** [aspnet/AspNetKatana#213]
Hello

I have set up ARR in my IIS application to forward some requests to another server. The application is an .NET Web Api (.Net full framework). After I switched to OWIN, only GET requests are redirected properly. Post requests fail with some references to mismatch in content length.
When I switch back to Global.asax the redirect works fine?
Any pointers?

**Comment by Tratcher** [comment]
That's a new one. The requests aren't 'redirected' using client side redirects (e.g. 302) right? They're internally forwarded?

What are you doing in your OWIN code? Do you have middleware that examines the request? My first guess is that the request body is being read in your app and so it does not get forwarded by ARR.

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
