### ISSUE TITLE
This repository vs Nuget Vesrion Inconsistency 

### ISSUE THREAD

**Issue by miksh7** [aspnet/AspNetKatana#214]
Nuget shows Latest Stable version 4.0.0 published on February 14, 2018 (2/14/2018)
This repository shows v4.0.0-alpha1 on Aug 29 2017

What's on Nuget?

**Comment by Tratcher** [comment]
Where do you see alpha1?

**Comment by miksh7** [comment]
https://github.com/aspnet/AspNetKatana/releases

**Comment by Tratcher** [comment]
Ah, we updated https://github.com/aspnet/AspNetKatana/wiki/Roadmap, but not releases. Thanks for the heads up.

**Comment by Tratcher** [comment]
Updated.
