### ISSUE TITLE
Version 4.0 says Dependency Newsoft.Json >= 9.0.1, but is it 10.0.0.0?

### ISSUE THREAD

**Issue by KarlZ** [aspnet/AspNetKatana#215]
I kept getting warnings about version mismatch when building. It took me a while, but then I opened up Microsoft.Owin.Security.OAuth.dll in .Net Reflector, it says that it relies on 10.0.0.0, not 9.0.1. Am I looking at something wrong?

**Comment by Tratcher** [comment]
You're right. The nuspec says 9.0.1: https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.OAuth/Microsoft.Owin.Security.OAuth.nuspec#L17
But it's using 10.0.1: https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.OAuth/packages.config#L3

It works fine if you install 10.0.1, right?

**Comment by Tratcher** [comment]
We updated it because of OpenIdConnect, but the nuspecs never got updated.
https://github.com/aspnet/AspNetKatana/commit/476b62a271a6075b64ea453a225d19133566e929

**Comment by KarlZ** [comment]
I'm using this code in some Azure Function Apps, and those are stuck on Newtonsoft.Json 9.0.1. So Microsoft.NET.Sdk.Functions has Jewtsonsfot.Json = 9.0.1 (NOT >=)... They say because the current Function App VMs are deploying that version. This has been a real headache.

**Comment by julioapm** [comment]
Same here! Using HangFire and lots of incompatibilities! Please correct the NuGet package description!
