### ISSUE TITLE
Issue in web.config after upgrade to 4.0

### ISSUE THREAD

**Issue by bbarrick** [aspnet/AspNetKatana#221]
I'm new to this so forgive me if there is something simple causing this. I recently updated to OWIN 4.0 through nuget and now my web.config is showing light blue tildes throughout the XML. Hovering over each one of them show's a different message but usually something like 'The global element 'location' has already been declared.' Any help would be appreciated.

**Comment by Tratcher** [comment]
These packages have no influence over the web.config. Did you update something else at the same time?

**Comment by Tratcher** [comment]
The binding redirects? Those are auto-generated by nuget. The message you're getting is a tooling warning, correct? It's not interfering with running the project?
