### ISSUE TITLE
How can I have dynamic expiration times from OAuth tokens?

### ISSUE THREAD

**Issue by lavilaso** [aspnet/AspNetKatana#222]
I need to set the dynamic expiration time of the tokens but trying to set it to ticket.Properties.ExpiresUtc does not work and it takes the default value.
I have different types of users with different expiration times, how can I implement this behavior without being overwritten by the default in my GrantResourceOwnerCredentials () method?

**Comment by muratg** [comment]
We don't plan to make changes on the auth server.

Did you try some others like IdentityServer or KeyCloak? Do they have this feature?
