### ISSUE TITLE
OWIN authentication with custom callbackpath for google not working

### ISSUE THREAD

**Issue by hamish-tushar** [aspnet/AspNetKatana#224]
Microsoft.Owin.Security.Google : 3.0.1

I am trying to integrate OWIN library and replacing existing dotnet oauth library. I am unable to get owin to work with my existing callback urls. 

            var authenticationOptions = new GoogleOAuth2AuthenticationOptions()
            {
                ClientId = AppSettings.GoogleOAuth2ClientID,
                ClientSecret = AppSettings.GoogleOAuth2ClientSecret,
                CallbackPath = new PathString("/user/customCallback"),
            };

I get 500 internal server error, and it does not even hit my controller endpoint for challenge URL. If i add signin-google to my developer console everything works but thats not an option for me. 

Can you please let me know what can be done to get this to work?

**Comment by Tratcher** [comment]
What do the logs say for the 500 error? https://github.com/aspnet/AspNetKatana/wiki/Debugging

The CallbackPath is a path handled internally by the middleware, it should not refer to an MVC controller.

**Comment by hamish-tushar** [comment]
Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationMiddleware Warning: 0 : The state field is missing or invalid.
    ProcessId=19404
    DateTime=2018-08-28T16:56:29.5837211Z
Microsoft.Owin.Security.Google.GoogleOAuth2AuthenticationMiddleware Warning: 0 : Invalid return state, unable to redirect.
    ProcessId=19404
    DateTime=2018-08-28T16:56:29.7528382Z

**Comment by hamish-tushar** [comment]
Basically anything other the signin-google does not work. Will OWIN for google only work for signin-google callback? Is that a limitation with OWIN ?

**Comment by Tratcher** [comment]
That CallbackPath is customizable, but it still must be a unique path handled only by that middleware. Why does it matter to you what the value is?

**Comment by hamish-tushar** [comment]
The value matters because I already have the url registered with Google (/user/customCallback) and cannot add more urls (/sigin-google) . I want to make sure that old uls work with new OWIN changes,

**Comment by Tratcher** [comment]
A custom value should just work. Can you share a Fiddler trace of the failed login flow?

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
