### ISSUE TITLE
Google callback url is going to http

### ISSUE THREAD

**Issue by hamish-tushar** [aspnet/AspNetKatana#225]
I am using owin for google oauth .             

var authenticationOptions = new GoogleOAuth2AuthenticationOptions()
            {
                ClientId = AppSettings.GoogleOAuth2ClientID,
                ClientSecret = AppSettings.GoogleOAuth2ClientSecret,
            };

I check in the browser and see the redirect uri  has redirect_uri=http%3A%2F%2Fwww.test.com%2Fsignin-google

How can I make this redirect https? Because on google console i have registered as https

**Comment by Tratcher** [comment]
It's taking the scheme from the current request when it creates the redirect. Did it start as https? If not then you should redirect to https before initiating auth.

**Comment by hamish-tushar** [comment]
Started off from https but the redirect to google has 
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=***&redirect_uri=http%3A%2F%2Fmydomain.com%2Fsignin-google&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&state=****

redirect url has http

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
