### ISSUE TITLE
Localized packages in Nuget are not referenced when installed

### ISSUE THREAD

**Issue by alexis-y** [aspnet/AspNetKatana#226]
The localized packages for v4.0.0 available in the oficial nuget repo are still listed as using .NETFramework v4.5, as opposed to the "core" packages which use v4.5.1.

As a result, the satellite assemblies aren't "picked up" by Visual Studio, copied to the output dir, etc.

I tried with just a couple of packages (Microsoft.Owin.es, Microsoft.Owin.Security.es), but have no reason to believe this isn't widespread across all languages.

**Comment by Tratcher** [comment]
Thanks, we'll take a look.

What's your interest in the localization packages? We've seen very low demand for them.

**Comment by alexis-y** [comment]
It's very low priority. I'm maintaining an app that is localized in a couple of languages. We're using the localized packages where available, and including the satellite assemblies (both ours and from dependencies) in the WIX-based installer. I'm not actually certain these localized packages have anything useful that we may expose to the user. Exception messages maybe?

Anyway, once I upgraded from 3.1 to 4.0 (and NetFX45 to 451), WIX complained that the satellite assemblies where not found in the output directory for the project. I already have a workaround in place.

**Comment by Tratcher** [comment]
Most of those error messages are intended for the developer, not the end user.

**Comment by muratg** [comment]
Thanks for the report, though this is not something we will be fixing.
