### ISSUE TITLE
A better Microsoft.Owin.Security.OpenIdConnect library

### ISSUE THREAD

**Issue by ghstahl** [aspnet/AspNetKatana#227]
Is there a version of this asp.net 4 OpenIdConnect library;
https://github.com/aspnet/AspNetKatana/blob/release/src/Microsoft.Owin.Security.OpenIdConnect/
That is as good as this one from asp.net core;
https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication.OpenIdConnect

The Microsoft.AspNetCore.Authentication.OpenIdConnect one covers a lot more variations to the flow.
i.e. Supports GET when the provider redirects back, and better handling of the AuthorizationCode flow.

I will take a third party alternative on asp.net 4 to replace the Microsoft.Owin.Security.OpenIdConnect library.

Some dude on stackoverflow suggests modifying the Microsoft.Owin.Security.OpenIdConnect, but why doesn't the ASP.NET team do this.  I know that folks don't really like to work on legacy libraries but there is a lot of this stuff still in the field and in need to switching over to using OpenIdConnect as a login provider. 

[stackoverflow suggestion](https://stackoverflow.com/questions/33661935/owin-middleware-for-openid-connect-code-flow-flow-type-authorizationcode)  

Thanks

**Comment by Tratcher** [comment]
I'm not aware of alternate implementations for ASP.NET 4.

**Comment by ghstahl** [comment]
Ok, so I had to make one.
https://github.com/ghstahl/OpenIdConnect-Code-Flow-ASP.NET-4-and-ASP.NET-Core/tree/master/src/P7.Microsoft.Owin.Security.OpenIdConnect

Its an direct replacement for Microsoft.Owin.Security.OpenIdConnect.

I verified that it works against Google using the 3 code flow variants as well as our internal OIDC provider that only supports the code flow.

Use at your own risk...

**Comment by muratg** [comment]
Thanks @ghstahl. Closing this issue as we don't plan to take any action on it at this point.
