### ISSUE TITLE
Cookie OpenIdConnect.nonce.xxxx is not in secure even though site use HTTPS

### ISSUE THREAD

**Issue by shNerotic** [aspnet/AspNetKatana#228]
Recently I published my site into Azure and use HTTPS as the protocol. I notice that when redirect to the login page , will add a cookie named OpenIdConnect.nonce.xxxx, but unfortunately it not in secure.

I saw the source code in the method RememberNonce in OpenIdConnectAuthenticationHandler.

```
Response.Cookies.Append(
                GetNonceKey(nonce),
                Convert.ToBase64String(Encoding.UTF8.GetBytes(Options.StateDataFormat.Protect(properties))),
                new CookieOptions
                {
                    HttpOnly = true,
                    Secure = Request.IsSecure
                });
```

So, I'm confused about the Request.IsSecure, does it mean my azure site is not Secure even though access via HTTPS?

can anyone help me, thanks in advance.

Info.  Microsoft.Owin.Security.OpenIdConnect version is 3.0.1

**Comment by Tratcher** [comment]
Right, if the request was HTTPS then it marks the cookie as secure.

It's possible that something is confusing IsSecure. Can you share a Fiddler trace of the initial request and redirect response?

**Comment by shNerotic** [comment]
> Right, if the request was HTTPS then it marks the cookie as secure.
> 
> It's possible that something is confusing IsSecure. Can you share a Fiddler trace of the initial request and redirect response?

Thank you. 

![oidc_nonce](https://user-images.githubusercontent.com/14741099/45800340-3655f080-bce3-11e8-8ea9-3ea2a2f0e741.png)

We can see the nonce cookie has no Secure flag.


I just overridden the RememberNonce method, force the CookieOptions.Secure is TRUE, then monitor the request and can see the Secure flag.
![oidc_nonce_secure](https://user-images.githubusercontent.com/14741099/45800170-a3b55180-bce2-11e8-8baf-5b33bbf74f4e.png)

I really don't know the real reason about this issue, seems it's the Request.IsSecure.

**Comment by Tratcher** [comment]
That's odd, the only thing that usually interferes with Scheme/IsSecure is a TLS terminating reverse proxy. This is running in Azure App Service as a normal web site?

Here's a troubleshooting [sample](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot) from ASP.NET Core that you should be able to adapt for Katana and run on your site. That should show you the scheme and headers as received by the application.

**Comment by shNerotic** [comment]
Yes. It is a normal web site in Azure App Service and I configure something in Application Gateway. 
a. TLS 1.2 (may cause that issue ? )
b. Portal & STS site  are both in HTTPS protocol 

![wechat screenshot_20180920223704](https://user-images.githubusercontent.com/14741099/45826598-5d361600-bd27-11e8-9bbc-88c8e8dace44.png)

I will use the sample you shared to check the site scheme, but may need some time before complete.

Thank you again.
