### ISSUE TITLE
Update nightly symbol publishing destination

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#23]
Nightly packages have moved to  `https://dotnet.myget.org/f/katana-dev/`

But symbol packages are still publishing to 'https://nuget.symbolsource.org/MyGet/aspnetwebstacknightly'

Is this a problem?

**Comment by muratg** [comment]
Backlogging for now. We can bring this back if there's enough interest.

**Comment by Tratcher** [comment]
Note symbolsource.org is all but defunct at this point. https://groups.google.com/forum/#!forum/symbolsource. Publishing symbols has been disabled on the CI.

**Comment by anurse** [comment]
I believe there's no reason we can't publish symbols for nightlies to the Microsoft Symbol Server. We should consider that.
