### ISSUE TITLE
Storing ClientSecret in Azure Keyvault

### ISSUE THREAD

**Issue by paulhickman-a365** [aspnet/AspNetKatana#231]
I am using OpenIdConnect, and would like to store the client secret in KeyVault to improve security. However, currently as `OpenIdConnectAuthenticationOptions.ClientSecret` is passed when constructing the pipeline, this means I have to connect to and retrieve the secret during application startup. If this fails due to network/key vault availability problems, then the application fails to start properly and doesn't recover. It also means that if the secret is changed whilst the application is running, then it must be restarted to read the new secret.

Is it possible to pass the client secret in any other way? Ideally, there would be a notification callback added to the `OpenIdConnectAuthenticationOptions` to obtain the current secret.

**Comment by Tratcher** [comment]
This OpenIdConnectin implementation doesn't actually use the ClientSecret, the option is there as a pass through for you to consume during the AuthorizationCodeReceived event. Inside AuthorizationCodeReceived you can do all of the things you're describing above.
