### ISSUE TITLE
IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null

### ISSUE THREAD

**Issue by kalyankrishna1** [aspnet/AspNetKatana#232]
Cross post from 
https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims/issues/42#issue-367167065

@mqamarmunir

**Comment by Tratcher** [comment]
@mqamarmunir what version isn't working for you? Can you provide the Fiddler trace for success and failure sceanrios?

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
