### ISSUE TITLE
symbolsource.org gone, non-dev builds are missing symbols?

### ISSUE THREAD

**Issue by YoloClin** [aspnet/AspNetKatana#237]
According to https://github.com/aspnet/AspNetKatana/wiki/Debugging symbols are hosted at symbolsource.org which is no longer online. 

Is there anywhere else I can access Symbols? The version I'm after is 4.0.0 but I assume others' would probably like to easily access symbols too :)

**Comment by Tratcher** [comment]
Nuget.org runs a symbol server now that we can publish to for the next release.
https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

It requires a new format so we wouldn't be able to publish symbols from prior releases.

**Comment by Tratcher** [comment]
The symbols have been published to the Microsoft symbol server and are loading for me in my project. However, I get an error "Source information is missing from the debug information for this module" and can't see the sources. Did the PDBs need to be build differently?

**Comment by Tratcher** [comment]
Ok, it looks like source stepping is a separate feature we'll have to revisit, likely using sourcelink and the nuget symbol server. For now the Microsoft Symbol Server will at least give you better stack traces and type inspection.

**Comment by anurse** [comment]
Closing. We publish to the Microsoft Symbol Server. We are looking at source link in #211.
