### ISSUE TITLE
How do you configure UseWindowsAzureActiveDirectoryBearerAuthentication?

### ISSUE THREAD

**Issue by nordleif** [aspnet/AspNetKatana#239]
I'm trying to configure UseWindowsAzureActiveDirectoryBearerAuthentication.
What options should I use. 
I have tried several examples on the Internet, but I cannot figure out what Tenant and ValidAudience is?

`
var azureBearerOptions = new WindowsAzureActiveDirectoryBearerAuthenticationOptions();
azureBearerOptions.Tenant = "???"; // Directory Id
azureBearerOptions.TokenValidationParameters = new TokenValidationParameters();
azureBearerOptions.TokenValidationParameters.ValidAudience = "???"; // Application Id 

application.UseWindowsAzureActiveDirectoryBearerAuthentication(azureBearerOptions);
`

I have created a Web app on Azure and received an access-token when I login in. 
I have also created a Owin self hosted application and what to validate the access token. 

Can you please point me in the right direct, so I'm using the correct options.

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v1-dotnet-webapi#step-2-set-up-the-app-to-use-the-owin-authentication-pipeline
"ida:Tenant is the name of your Azure AD tenant--for example, contoso.onmicrosoft.com.
ida:Audience is the App ID URI of the application that you entered in the Azure portal."

**Comment by nordleif** [comment]
I'm not sure what my Azure AD Tenant is?
My IT department says it is unique identifier (Directory ID).
The example says e.g. contoso.onmicrosoft.com.
Where can I find the tenant value in the Azure portal?

By the way, the example is outdated.
Audience is deprecated.
`
            var options = new WindowsAzureActiveDirectoryBearerAuthenticationOptions
            {
                Audience = "???",
                Tenant = "???",
            };
`
So I use:
`
var options = new WindowsAzureActiveDirectoryBearerAuthenticationOptions();
options .Tenant = "???";
options .TokenValidationParameters = new TokenValidationParameters();
options .TokenValidationParameters.ValidAudience = "???"; 
`

**Comment by Tratcher** [comment]
x-ref: https://github.com/MicrosoftDocs/azure-docs/issues/16848

Here's an updated version of the sample: https://github.com/AzureADQuickStarts/AppModelv2-NativeClient-DotNet/blob/complete/TodoListService/App_Start/Startup.Auth.cs

**Comment by anurse** [comment]
Closing as it doesn't look like there's action left here.
