### ISSUE TITLE
Add an option to exclude Request.PathBase from url generation

### ISSUE THREAD

**Issue by wc-matteo** [aspnet/AspNetKatana#24]
I'm using an IIS Module to rewrite PathBase out of the urls. The middlewares are not aware of this obviously and generate the "wrong" urls: 

e.g. FacebookAuthenticationMiddleware's `CallbackPath`:

```cs
string redirectUri = requestPrefix + Request.PathBase + Options.CallbackPath;
```
Could an option be added (per middleware) to tell it to exclude `Request.PathBase`? Or perhaps there's a better way?

**Comment by Tratcher** [comment]
You'd be better off writing a middleware that just cleared PathBase. Then you wouldn't have to customize each middleware. Something like:
```
app.Use((context, next) =>
{
  context.Request.PathBase = PathString.Empty;
  return next();
});
app.UseFacebook(...);
```

**Comment by wc-matteo** [comment]
Thanks @Tratcher. That seems a sensible approach!
