### ISSUE TITLE
OnCreate is mandatory if use OnCreateAsync in AuthenticationTokenProvider

### ISSUE THREAD

**Issue by dp-huang** [aspnet/AspNetKatana#241]
when using OnCreateAsync in AuthenticationTokenProvider, I get an error saying "The AuthenticationTokenProvider's required synchronous events have not been registered."

Check out the AuthenticationTokenProvider.cs sourcecode, 
```
if (OnCreateAsync != null && OnCreate == null)
{
    throw new InvalidOperationException(Resources.Exception_AuthenticationTokenDoesNotProvideSyncMethods);
}
```

Looks like OnCreate is mandatory if OnCreateAsync has a value. So I have to write the code like this,
```
RefreshTokenProvider = new AuthenticationTokenProvider
{
    OnCreateAsync = CreateRefreshTokenAsync,
    OnReceiveAsync = ReceiveRefreshTokenAsync,
    OnCreate = (context) => { },
    OnReceive = (context) => { }
}
```
The empty actions OnCreate and OnReceive make sense?

**Comment by anurse** [comment]
We don't have plans to make this kind of change in Katana. It's a little odd, but there's a pretty clear workaround here.
