### ISSUE TITLE
Session null nothing vb.net Webforms

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetKatana#243]
I try to rewrite msgraph-training-aspnetmvcapp to a Website Project vb.net and webforms. 
doenst work, cause Session object (here ctx) is Nothing (null) in Startup class Registration Event. SessionToken storage class Need it.  Same Code, same packeages in c# Project have a session object and works fine (Shows calender entrys)

         private async Task OnAuthorizationCodeReceivedAsync(AuthorizationCodeReceivedNotification notification)
        {
                       string signedInUserId = notification.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier).Value;

            var ctx = notification.OwinContext.Environment["System.Web.HttpContextBase"] as HttpContextBase;

**Comment by hannespreishuber** [comment]
added a GitHub Project as demo
https://github.com/hannespreishuber/demoAuthorizationCodeReceivedSessionNull

**Comment by Tratcher** [comment]
Is it the HttpContextBase that's null or HttpContextBase.Session?

**Comment by hannespreishuber** [comment]
Session null!

**Comment by Tratcher** [comment]
What does your Startup.Auth code look like? The IIS integrated pipeline has many stages and auth is usually run before session is loaded. That would affect Cookie auth, but I would not expect OpenIdConnect to be affected.

**Comment by Tratcher** [comment]
Nevermind, this is what's breaking you:
https://github.com/hannespreishuber/demoAuthorizationCodeReceivedSessionNull/blob/de87e53ecdc1078ce6c8b3ea77474eb4d74d6494/nochmal5/App_Start/StartupAuth.cs#L81

**Comment by Tratcher** [comment]
You can remove UseStageMarker, it's built into UseCookieAuthentication.

**Comment by hannespreishuber** [comment]
this is a dead line of Code, from 20 tries. I will remove it and give it a try, but dont think will work

**Comment by hannespreishuber** [comment]
ok started a new Project
VISUAL Studio - Web Project Webforms, add authenication (Company)
the Stagemarker line is generated (i remove it)
same effect session is null

**Comment by hannespreishuber** [comment]
the 60 Seconds Project https://github.com/hannespreishuber/nochmal7/tree/master/nochmal7
session is still  null

**Comment by Tratcher** [comment]
Still calls UseStageMarker?

**Comment by hannespreishuber** [comment]
with or without, doenst matter

**Comment by hannespreishuber** [comment]
https://github.com/hannespreishuber/nochmal7/blob/master/nochmal7/App_Start/StartupAuth.cs
and once again - this line is generated.

**Comment by hannespreishuber** [comment]
I am getting Closer. It must be the friendlyurl Redirect feature in conjunction with the owin pipeline

**Comment by hannespreishuber** [comment]
Also installed and mapped SignalR 2.4 destroys the session object.
correct order in Startup
  app.MapSignalR()
  ConfigureAuth(app)
still no glue - what exactly happens in magic owin

**Comment by Tratcher** [comment]
SignalR also adds a stage marker to make it run before session is loaded. SignalR has long running requests and if they acquired the session lock then the rest of the app would hang.

**Comment by hannespreishuber** [comment]
make sense, but how to troubleshoot such a issue? would it be possible to write out some warnings?

**Comment by Tratcher** [comment]
Warnings about what? These are components that don't generally require session.

**Comment by hannespreishuber** [comment]
from a coding point of view, there is zero evidence about how a object (HttpContextBase) will work in a specific Environment.  

"no session object, cause of stagemarker blah" during compile

I see no possibility to troubleshoot with debugger or any other tool. It is only by testing and compare behavior- Had to invest 30h to get it, Perhaps I am a complete idiot, or others fail into the same pitfall or do not use it.

**Comment by Tratcher** [comment]
Do you have a link to the specific samples?

**Comment by hannespreishuber** [comment]
https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp

**Comment by Tratcher** [comment]
And that sample doesn't work as is? Or it doesn't work after you've re-written it? The repro you posted does not match the sample [here](https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/blob/master/Demos/03-add-msgraph/graph-tutorial/App_Start/Startup.Auth.cs).

**Comment by hannespreishuber** [comment]
the sample works, which is confusing enough. It doenst work in some sceanrios with ASP.NET Webforms (Friendlyurls) and also SignalR. My Point is that it is impossible to get this dependency, which is somehow influenced by owin and session (still didnt get the Details) - For me - I am fine. Thinking About the rest of the world and how the magic could be more helpfull

**Comment by rpowell6** [comment]
I am also having an issue when attempting to retrofit the working MVC C# example (msgraph-training-aspnetmvcapp) into a WebForms app.  The Request.GetOwinContext().Authentication.Challenge() method seems to be working just fine.  I am prompted to navigate through the sign-in process, as expected.  **However, the OnAuthorizationCodeReceivedAsync() task/listener is never called.** Consequently, nothing is being stored in the session token cache.  Examining the contents of the Output window indicates the  Request.GetOwinContext().Authentication.Challenge() method is the last method to successfully execute.  Program execution hangs at this point.

Any assistance in resolving this issue would be greatly appreciated.

**Comment by NT-Christ** [comment]
Correct, if webforms you have to use the set marker to authenticate to even get Owin to work in your start up....however you can't have access to session at that point.  The MS samples use a session store which won't work in webforms because you don't have access to session.  The only workaround I found was not to store the tokens in a session cache, just make the MSAL client app static in a global class so you it will cache the tokens for you.  Its the same setup as using a memorycache but it does it for you with a static global.
