### ISSUE TITLE
OIDC authentication with google and fb in WebForm / MVC

### ISSUE THREAD

**Issue by Engineerumair** [aspnet/AspNetKatana#244]
Hi, can someone please guide me how to authenticate on asp.net MVC/Webform app with google provider using OIDC?

**Comment by Tratcher** [comment]
@Engineerumair I don't think they're compatible. See https://stackoverflow.com/questions/25423898/openidconnect-owin-login-with-google

Any reason you can't use the Google OAuth provider instead?
https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on#creating-a-google-app-for-oauth-2-and-connecting-the-app-to-the-project
https://cloud.google.com/dotnet/docs/getting-started/authenticate-users

**Comment by Engineerumair** [comment]
Hello I have implemented google authentication in webform app with the following app but the article doesn't include many features.
http://www.cloudidentity.com/blog/2014/07/24/protecting-an-asp-net-webforms-app-with-openid-connect-and-azure-ad/#comment-202460

**Comment by Tratcher** [comment]
Such as?

**Comment by Engineerumair** [comment]
such as authenticating API and using more than 1 IDP using different scopes and claims e.t.c

**Comment by Tratcher** [comment]
This will be possible in the next release due to https://github.com/aspnet/AspNetKatana/pull/297
