### ISSUE TITLE
".AspNet.Cookies" creates security vulnerability

### ISSUE THREAD

**Issue by prakashchidambaram** [aspnet/AspNetKatana#246]
We have azure ad authentication using owin  whereas its creating an client side cookie called ".AspNet.Cookies".

If any hacker tries to change the value through browser developer tools then its allowing the user to get authenticated.

How to get rid of this client side cookie ".AspNet.Cookies" ?

**Comment by Tratcher** [comment]
> We have azure ad authentication using owin whereas its creating an client side cookie called ".AspNet.Cookies".

Client side cookies are the standard mechanism for preserving the identity across requests.

> If any hacker tries to change the value through browser developer tools then its allowing the user to get authenticated.

The cookie is encrypted to prevent tampering. If you have a reliable mechanism for tampering with the cookie then please privately contact secure@microsoft.com.
