### ISSUE TITLE
Bad request - Request too long. the size of the request headers is too long, SignInMessage Cookie duplicated

### ISSUE THREAD

**Issue by rivkia** [aspnet/AspNetKatana#247]
I am using Katan, IdentityServer3 and OpenID Connect to authenticate user with DB, sometimes (not clearly when, couldn’t restore the problem manually) I get the message 'Bad request - Request too long. the size of the request headers is too long'.<br>
The issue now occurs on Google Chrome MF. After deleting the cookies, the site will work. I'm running version 4.0.0 of the OpenID Connect package.<br>
The issue is known and caused by the nonce cookies which are created by openid connect. When it shows the error, at that moment, more than 20 of those cookies exist in the browser (Chrome, Firefox and Edge). I tried different things, but still no solution:

 - Downgrading the package to version 3.0.0 didn't solved it either.
   Extra problems due to related package which were on newer
   versions.
 - Deleting old Nonce cookies as suggested in
   <br>https://github.com/IdentityServer/IdentityServer3/issues/1124
   helped with Nonce Cookies, but not with SignInMessage Cookies that is
   duplicated Number of times  when the issue is occurred
 - I configured [SignInMessageThreshold][1]  to 1, didn’t helped
 - I tried to add [Kentor.OwinCookieSaver][2]  but it didn’t help

 <br><br>

This is how the cookies seem when the error occurs:<br>

<img src="https://i.stack.imgur.com/UyJ4R.jpg"> 
After hours of searching and trying, I recognized that the path of the cookie is “/identity” and the nonce is “/”. <br>
I don’t know but maybe this is the problem: when I wrote the code that deletes Nonce, I tried to get the signInMessage cookies too, and I saw that only those that with the path “/” are in the list, but the signInMessage cookie wasn’t in the list of the cookies. <br>
if this is it the problem, can you give me clue why is it happen?<br>

  [1]:https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AuthenticationOptions.cs#L152
  [2]: https://github.com/Sustainsys/owin-cookie-saver

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
