### ISSUE TITLE
Microsoft.Owin.* 4.0.0

### ISSUE THREAD

**Issue by olegmkr** [aspnet/AspNetKatana#248]
I have update Microsoft.Owin.* packages:
Microsoft.Owin
Microsoft.Owin.Security
Microsoft.Owin.Security.Jwt
Microsoft.Owin.Security.OAuth

to 4.0.0 and now in 

```
public class AccessTokenProviderEx : AuthenticationTokenProvider
    {
        public override void Receive(AuthenticationTokenReceiveContext context)
        {
            try
            {
                //JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

                context.DeserializeTicket(context.Token);
            }
            catch (Exception exc)
            {
                var jwtHandler = new JwtSecurityTokenHandler();
                var jwtSecurityToken = jwtHandler.ReadToken(context.Token) as JwtSecurityToken;

                throw;
            }

            base.Receive(context);
        }
    }
```

 I get error:
```
Value cannot be null. 
Parameter name: source

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationTokenReceiveContext.DeserializeTicket(String protectedData)
   at Adform.AdPlatform.Infrastructure.WebApi.OWIN.Security.OAuthBearerAuthentication.AccessTokenProviderEx.Receive(AuthenticationTokenReceiveContext context) in XXXX
```
But jwtSecurityToken in catch block with all my claims as before. I think problem with my configuration or something else. Could someone help me, please

**Comment by Tratcher** [comment]
Can you provide a full project that reproduces this issue?

**Comment by olegmkr** [comment]
The problem is SecurityKeys and exception from there https://github.com/aspnet/AspNetKatana/blob/d95d857cecd648e05dccc334edef284212d139db/src/Microsoft.Owin.Security.Jwt/JwtFormat.cs#L209

Before update I have this class

`   /// <summary>
    ///     Reads certificate tokens from openid-configuration endpoint.
    /// </summary>
    public class OpenIdIssuerSecurityTokenProvider : IIssuerSecurityTokenProvider
    {
        private readonly ConfigurationManager<OpenIdConnectConfiguration> _configurationManager;

        /// <summary>
        ///     Initializes a new instance of the <see cref="T:System.Object" /> class.
        /// </summary>
        public OpenIdIssuerSecurityTokenProvider(string issuer)
        {
            Issuer = issuer;

            _configurationManager =
                new ConfigurationManager<OpenIdConnectConfiguration>(issuer + "XXXopenid-configuration",
                    new HttpClient(new RetryingHandler(new HttpClientHandler(), TimeSpan.FromSeconds(3)))
                    {
                        Timeout = TimeSpan.FromSeconds(10)
                    });
        }

        /// <summary>
        ///     Gets the issuer the credentials are for.
        /// </summary>
        /// <value>
        ///     The issuer the credentials are for.
        /// </value>
        public string Issuer { get; set; }

        /// <summary>
        ///     Gets all known security tokens.
        /// </summary>
        /// <value>
        ///     All known security tokens.
        /// </value>
        public IEnumerable<SecurityToken> SecurityTokens => from key in _configurationManager
            .GetConfigurationAsync()
            .Result
            .JsonWebKeySet
            .Keys
            select new X509SecurityToken(new X509Certificate2(Convert.FromBase64String(key.X5c.First())), key.Kid);

    }`

After update 

- IIssuerSecurityTokenProvider changed to IIssuerSecurityKeyProvider 
- public IEnumerable<SecurityToken> SecurityTokens changed to public IEnumerable<SecurityKey> SecurityKeys. 

I don't set SecurityKeys.

So, how can I set SecurityKeys properly according to new breaking changes?

**Comment by Tratcher** [comment]
Microsoft.IdentityModel.Protocol.Extensions is obsolete and can be removed. That's likely messing up your dependencies.
Update System.IdentityModel.Tokens.Jwt to 5.3 while you're at it.

**Comment by olegmkr** [comment]
Hi, I use it in my project as I wrote before -> https://github.com/olegmkr/MicrosoftIdentityModel
Question is how I have to change OWIN 3.0 OpenIdIssuerSecurityTokenProvider implementation to OWIN 4.0. 
I found some wikis https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x#katana-4x-doesnt-support-net-45-target but this part https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x#if-you-are-coding-to-identitymodel-or-derived-classes is not clear, could somebody have examples or more info about it

**Comment by olegmkr** [comment]
Looks like I found solution: I have use OpenIdConnectConfigurationRetriever.GetAsync instead of ConfigurationManager<OpenIdConnectConfiguration>. Tomorrow I will check it
