### ISSUE TITLE
Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0

### ISSUE THREAD

**Issue by leejeffr** [aspnet/AspNetKatana#249]
I am running asp.net v4.6. I am trying to get the oidc client runtime working.  I receive the following error. Can someone point me in the right direction? I read a another post about how I need to run Katana 3.x because I'm using asp.et 4.x but when I look at the dependencies for Microsoft.Owin.Protocols.OpenIdConnect (3.1.0) it depends on Microsoft.IdentityModel.Protocol.Extensions (1.0.0). I think that this library is deprecated? Plus all the other Microsoft.IdentityModel.* libs require 4.0. I'm lost. 

To top it all off I have another solution with a sample client that works just fine with the exact references packages below. 

```
<packages>
 <package id="IdentityModel" version="3.10.4" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Logging" version="5.2.1" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.2.1" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.2.1" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.2.1" targetFramework="net462" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.0.0" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="11.0.1" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.2.1" targetFramework="net462" />
  <package id="System.Text.Encodings.Web" version="4.5.0" targetFramework="net462" />
</packages>

```

Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

Assembly binding log:
Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  c:\windows\system32\inetsrv\w3wp.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Git/ATM/Applications/ATMWebApp/ATMWeb/
LOG: Initial PrivatePath = C:\Git\ATM\Applications\ATMWebApp\ATMWeb\bin
Calling assembly : Microsoft.Owin.Security.OpenIdConnect, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Git\ATM\Applications\ATMWebApp\ATMWeb\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/atm/1616314b/a77b38d3/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/atm/1616314b/a77b38d3/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Git/ATM/Applications/ATMWebApp/ATMWeb/bin/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by Tratcher** [comment]
The current versions you should use with ASP.NET 4.x are:
- Microsoft.Owin.* 4.0
- IdentityModel 5.3

And yes Microsoft.IdentityModel.Protocol.Extensions is obsolete.

**Comment by leejeffr** [comment]
I've tried your suggestion above but something is still looking for Microsoft.IdentityServer.Protocols.OpenIdConnect V5.2

Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

<packages>
  <package id="IdentityModel" version="3.10.4" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Logging" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.3.0" targetFramework="net462" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.0.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.0.0" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="11.0.1" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.3.0" targetFramework="net462" />
  <package id="System.Text.Encodings.Web" version="4.5.0" targetFramework="net462" />
</packages>

**Comment by Tratcher** [comment]
Edit your csproj file to make sure all of the references were updated correctly.

**Comment by Tratcher** [comment]
Oh, Microsoft.Owin.Security.OpenIdConnect did depend on Microsoft.IdentityModel.Protocols.OpenIdConnect 5.2.0. You'll need to use 5.2 or make sure your project has binding redirects. Nuget should have added the redirects for you.

**Comment by leejeffr** [comment]
When I look at nuget solution manager, I see options to install 5.2.1 but not 5.2.0.0. The previous version is 2.1.5. 

My original post used 5.2.1 and still got the same error. I tried using 5.2.4 but it's still complaining about wanting 5.2.0.0 but I don't know how to get that version of the dll.

**Comment by Tratcher** [comment]
They must have delisted it. Check your binding redirects instead.

**Comment by leejeffr** [comment]
I think the binding redirect that I have should work?
 oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" 



`<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocols.OpenIdConnect" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Protocols" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Logging" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>
      
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

**Comment by Tratcher** [comment]
You're going to need to check the binding logs then. See https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

**Comment by leejeffr** [comment]
So I am able to get the binding logs but unsure how to make sense of them.

*** Assembly Binder Log Entry  (1/2/2019 @ 1:33:17 PM) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  c:\windows\system32\inetsrv\w3wp.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Git/ATM/Applications/ATMWebApp/ATMWeb/
LOG: Initial PrivatePath = C:\Git\ATM\Applications\ATMWebApp\ATMWeb\bin
LOG: Dynamic Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\atm\1616314b
LOG: Cache Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\atm\1616314b
LOG: AppName = a77b38d3
Calling assembly : Microsoft.Owin.Security.OpenIdConnect, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Git\ATM\Applications\ATMWebApp\ATMWeb\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/atm/1616314b/a77b38d3/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/atm/1616314b/a77b38d3/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Git/ATM/Applications/ATMWebApp/ATMWeb/bin/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Git\ATM\Applications\ATMWebApp\ATMWeb\bin\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
LOG: Entering download cache setup phase.
LOG: Assembly Name is: Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Setup failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

*** Assembly Binder Log Entry  (1/2/2019 @ 1:33:17 PM) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  c:\windows\system32\inetsrv\w3wp.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Git/ATM/Applications/ATMWebApp/ATMWeb/
LOG: Initial PrivatePath = C:\Git\ATM\Applications\ATMWebApp\ATMWeb\bin
LOG: Dynamic Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\atm\1616314b
LOG: Cache Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\atm\1616314b
LOG: AppName = a77b38d3
Calling assembly : Microsoft.Owin.Security.OpenIdConnect, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Git\ATM\Applications\ATMWebApp\ATMWeb\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/atm/1616314b/a77b38d3/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/atm/1616314b/a77b38d3/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Git/ATM/Applications/ATMWebApp/ATMWeb/bin/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\Git\ATM\Applications\ATMWebApp\ATMWeb\bin\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
LOG: Entering download cache setup phase.
LOG: Assembly Name is: Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Setup failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by leejeffr** [comment]
I notice that there are two bindings for the same assembly. The first one is successful and the second one fails. 

![image](https://user-images.githubusercontent.com/5108841/50618222-807b7000-0e95-11e9-8dcf-9ce170d709c4.png)

**Comment by leejeffr** [comment]
I'm not clear on why Microsoft.Owin.Security.OpenIdConnect can only use 5.2.0.0? The documentation shows that any version equal to or greater than 5.2 should work. 

Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 5.2.0)

What else could affect the binding redirects? It seems like they are not working.
