### ISSUE TITLE
Websockets on Windows 7

### ISSUE THREAD

**Issue by GibbOne** [aspnet/AspNetKatana#25]
Does Katana support websockets for Windows 7?
Otherwise, will you add support in the future?
Thx

**Comment by davidfowl** [comment]
> Does Katana support websockets for Windows 7?
Nope. All of the Katana servers are built on top of http.sys (a windows component). WebSockets are only available on Windows 8+ (Server 2012).

> Otherwise, will you add support in the future?

Nope. Maybe look at Nowin? https://github.com/Bobris/Nowin

**Comment by GibbOne** [comment]
Thx
