### ISSUE TITLE
Bad request - Request too long. the size of the request headers is too long with Kerberos authentication

### ISSUE THREAD

**Issue by CedricInfeeny** [aspnet/AspNetKatana#250]
Hello,

We use Kerberos authentication for Owin Server (self hosting). We have set up a middleware: https://github.com/SteveSyfuhs/Kerberos.NET/blob/master/Samples/KerberosMiddlewareEndToEndSample/KerberosEndToEndMiddleware.cs

For some users who are part of many groups (~600) we have the HTTP Code 400 Bad Request error (browser or other client that requests to our server).
We had to check the cause of the problem with the script https://gallery.technet.microsoft.com/scriptcenter/Check-for-MaxTokenSize-520e51e5

The problem may occur with the following code in a client c# (executable) with SignalR connection to the server : _hubConnection.Headers.Add ("TEST", new string ('a', 18000));

We tested this article: https://support.microsoft.com/en-us/help/2020943/http-400-bad-request-request-header-too-long-response-to-http-request
It has no impact ...

How can we configure the Owin server to increase the max header size ? This is a blocking problem for us.

thank you so much

**Comment by Tratcher** [comment]
Do you have a sense for how big your headers are? Growing the header limit is not a good idea, it will have a significant impact on your site performance. Groups should not be listed in the headers.

Here's how you need to do it:
https://support.microsoft.com/en-us/help/820129/http-sys-registry-settings-for-windows
MaxRequestBytes
MaxFieldLength

**Comment by CedricInfeeny** [comment]
In the Kerberos authentication process, we do not control what is included in HTTP headers. It may not be the name of the groups that pass but the fact is that a user who is part of many groups, it causes a 400 error, bad request.

This may be related to the ticket-granting service-granting service (TGS)?
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc772815(v=ws.10)

**Comment by anurse** [comment]
Closing. @Tratcher 's comment indicated where maximum header size limits can be changed. We don't directly control those limits in Katana.
