### ISSUE TITLE
Could not load type System.Security.Cryptography.DpapiDataProtector from assembly System.Security, Version=4.0.0.0

### ISSUE THREAD

**Issue by YurasNazar** [aspnet/AspNetKatana#255]
```
var provider = new DpapiDataProtectionProvider("GtdTimer");
var protector = provider.Create("EmailConfirmation");
This code thow the exception:
  "Could not load type 'System.Security.Cryptography.DpapiDataProtector' from assembly 
  'System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```
-------------------------------------------------------------------------------------------------------------------
All source code:
Target platform - ASP.Net Core 2.1
```

using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security.DataProtection;
using Timer.DAL.Extensions;
using Timer.DAL.Timer.DAL.Entities;

namespace Timer.DAL.Timer.DAL.Repositories
{
    public class ApplicationUserManager : UserManager<User, int>, IApplicationUserManager<User,int>
    {
        public ApplicationUserManager(IUserStore<User, int> store) : base(store)
        {
            var provider = new DpapiDataProtectionProvider("GtdTimer");
            var protector = provider.Create("EmailConfirmation");
            this.UserTokenProvider = new DataProtectorTokenProvider<User, int>(protector);
        }
    }
}
```
-------------------------------------------------------------------------------------------------------------------
The reason why I do this is when I call GenerateEmailConfirmationTokenAsync method from my UserManager , this throw the exception "No IUserTokenProvider is registered". So as solution I find this code snippet. But the other exception thrown - Could not load type System.Security.Cryptography.DpapiDataProtector from assembly System.Security, Version=4.0.0.0.
Please help me! I try to resolve this for 2 weekends.

**Comment by Tratcher** [comment]
You shouldn't be using Microsoft.Owin components in ASP.NET Core applications. There should be an ASP.NET Core replacement for these.

**Comment by anurse** [comment]
Closing as per @Tratcher's comment. In particular, the `DpapiDataProtector` component is not available on .NET Core.

The replacement API in ASP.NET Core is [Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-2.2)
