### ISSUE TITLE
Supporting urn:ietf:wg:oauth:2.0:oob

### ISSUE THREAD

**Issue by mpramat** [aspnet/AspNetKatana#257]
I need to support native apps via the urn:ietf:wg:oauth:2.0:oob redirect_uri value. I was planning on letting ValidateClientRedirectUri change the redirect uri to a local page when the above value is detected, but the context does not validate if the redirect uri is changed.

Is there another way to support this scenario?

Thanks!

**Comment by Tratcher** [comment]
That's a new one. It looks like changing the uri was specifically blocked:
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Security.OAuth/Provider/OAuthValidateClientRedirectUriContext.cs#L67

Not sure why, and I wouldn't want to change it without more context.

**Comment by mpramat** [comment]
I think it is good design that it is blocked. It makes sure that the validation happens for the requested redirect_uri only. I would like to have this overridden only for the specific value.

The urn:ietf:wg:oauth:2.0:oob value is thought for native apps that cannot use the browser to obtain the authorization code. So, instead of performing a redirect, the auth server shows the code in the browser and the user can e.g. copy-paste to the other app. Not really cutting-edge, I know, but nevertheless a requirement for me.

I was thinking of a modification which extends the server options object with a local redirect URL which is used when the specific value is requested. That URL could e.g. point to a page which shows the code or similar. I would also pass the redirect_uri value to the page as well, so as to have some added capabilities, e.g. there is another similar value (urn:ietf:wg:oauth:2.0:oob:auto) which sets the title of the page to the code. It seems some apps can read that.

What do you think? I'll implement this, is this something worth sharing?

**Comment by Tratcher** [comment]
We're not adding features to the OAuth server at the moment. Let us know how it works for you though.

**Comment by mpramat** [comment]
OK, Thanks!
