### ISSUE TITLE
Unable to invalidate the Asp.Net cookies instantly after logout on Azure AD Cookies authentication,

### ISSUE THREAD

**Issue by RamakrishnanRamar** [aspnet/AspNetKatana#260]
We are using Azure AD open Id connect cookies based authentication, that is working fine. For log out purpose, We added single sign out and log out the both application and azure portal using below code.

```
// Sign a user out of both AAD and the Application
    public void Logout()
    {
        HttpContext.GetOwinContext().Authentication.SignOut(
            new AuthenticationProperties { RedirectUri = OwinStartup.PostLogoutRedirectUri },
            OpenIdConnectAuthenticationDefaults.AuthenticationType,
            CookieAuthenticationDefaults.AuthenticationType);
     }
      public void LogoutPage()
      {

           var redirectUrl = ConfigurationManager.AppSettings["ida:PostLogoutRedirectUri"].ToString() + "Account/Logout/";
           var logouturl = string.Format("https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri={0}", redirectUrl);
           Response.Redirect(logouturl);
       }
```

But this code sign out the application, not in azure portal. If I logout the application then cookies need to be invalidated, but not happening and it's not redirected to logout page. If I took Asp.Net.Cookies from the application before logout(after that logout this session using above code), the same asp.net.cookies validating the application after the logout on new session while replacing with existing new session asp.net.cookies. If I am not using that cookies for next one hour that time it's throwing logout page, with in one hour it's allowing to access the application.

StartUp.cs code

```

app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

                app.UseCookieAuthentication(new CookieAuthenticationOptions());

                app.UseOpenIdConnectAuthentication(

                    new OpenIdConnectAuthenticationOptions

                    {

                        ClientId = Globals.ClientId,

                        Authority = Globals.Authority,

                        AuthenticationType = "oidc",

                        SignInAsAuthenticationType = "Cookies",

                        ResponseType = "code id_token",

                        PostLogoutRedirectUri = Globals.PostLogoutRedirectUri,

                        RedirectUri = Globals.RedirectUri,

                        TokenValidationParameters = new TokenValidationParameters { SaveSigninToken = true },

                        Notifications = new OpenIdConnectAuthenticationNotifications()

                        {

                            AuthorizationCodeReceived = (context) =>

                                {

                                    //// Enforce the reference/redirect to be HTTPS

                                    var builder = HttpContext.Current.Request.Url.AbsoluteUri;

                                    context.AuthenticationTicket.Properties.RedirectUri = builder.ToString();

                                    return Task.FromResult(0);

                                },

                            RedirectToIdentityProvider = (context) =>

                        {

                            context.ProtocolMessage.DomainHint = "My Domain";

                            return Task.FromResult(0);

                        },

                            SecurityTokenValidated = (context) =>

                            {

                                context.AuthenticationTicket.Properties.AllowRefresh = true;

                                // context.AuthenticationTicket.Properties.IsPersistent = true;

                                return Task.FromResult(0);

                            }

                        }

                    });
```

How can I Make Asp.Net.Cookies expired after the logout instantly? Where I made the mistake? I struck due to this last 3 weeks, help me to resolve the issue with code sample.

**Comment by Tratcher** [comment]
You used OpenIdConnectAuthenticationDefaults.AuthenticationType for signout, but AuthenticationType = "oidc" for the middleware. Those values need to be the same.

If that doesn't fix your other issues then please capture and share a Fiddler trace file for your logout flow.

**Comment by RamakrishnanRamar** [comment]
@Tratcher Thanks for your comment, How Can I sign out OIDC on logout else which authentication need to use on Authenticaton type?

**Comment by Tratcher** [comment]
Start by changing `AuthenticationType = "oidc"` to `AuthenticationType = OpenIdConnectAuthenticationDefaults.AuthenticationType`.

**Comment by RamakrishnanRamar** [comment]
@Tratcher It's also accepting the session out cookies.

**Comment by Tratcher** [comment]
The security stamp should only be changed as a last resort.

> It's also accepting the session out cookies, That is also not working.

I don't know what you mean. Please capture and share a Fiddler trace file for your logout flow.

**Comment by RamakrishnanRamar** [comment]
How can I share Fiddle trace file, it's have confidential details?

**Comment by Tratcher** [comment]
You can e-mail it to the address in my profile.

**Comment by five-star-potato** [comment]
I am experiencing the same issue. Is there any solution to invalidating the ASPNET session cookie after I signed out from B2C? 

        [HttpGet]
        public IActionResult SignOut()
        {
            var callbackUrl = Url.Action(nameof(SignedOut), "Session", values: null, protocol: Request.Scheme);
            return SignOut(new AuthenticationProperties { RedirectUri = callbackUrl },
                CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
        }

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
