### ISSUE TITLE
Google Oauth with ASP.NET MVC

### ISSUE THREAD

**Issue by fxtrade** [aspnet/AspNetKatana#262]
Hello,

I've updated Microsoft.Owin.Security.Google to 4.0.1 on our website in order to fix the problem with Google+ API shutdown.

If I deactivate Google+ Api in Google's console, login on our website doesn't work anymore...
Authentication is made from App_start/Startup.Auth.cs with a small code like:

```
var googleOptions = new GoogleOAuth2AuthenticationOptions()
            {
                ClientId = "xxxxx.apps.googleusercontent.com",
                ClientSecret = "xxxx",
                CallbackPath = new PathString("/signin-google"),

                 //force refreshToken
                AccessType = "offline",
    
                Provider = new GoogleOAuth2AuthenticationProvider()
                {
                    OnAuthenticated = context =>
                    {

                        ......

                        }

                       

                        return Task.FromResult(0);
                    },

                },
                SignInAsAuthenticationType = DefaultAuthenticationTypes.ExternalCookie
            };
            googleOptions.Scope.Add("email");
            googleOptions.Scope.Add("profile");
            googleOptions.Scope.Add("openid");
            googleOptions.Scope.Add("https://mail.google.com/");

            try
            {
                app.UseGoogleAuthentication(googleOptions);
            }
            catch (Exception ex)
            {

                Elmah.ErrorSignal.FromCurrentContext().Raise(ex); StackifyLib.Logger.QueueException(ex);
            }
```

When I try to login, no error is logged, but it loops to the login page after the Google window, without successfull authentification.

Thanks for your help.

**Comment by Tratcher** [comment]
Please share a Fiddler trace file showing the redirect loop.

**Comment by fxtrade** [comment]
Hello Tratcher,

Here's the Fiddler SAZ file (ZIP formatted because SAZ is not supported).
Thank you!


[loop.zip](https://github.com/aspnet/AspNetKatana/files/2813839/loop.zip)

**Comment by Tratcher** [comment]
The request to /signin-google returns `Location: /Account/RegisterExternalLogin?providerName=Google&returnUrl=&error=access_denied` That means the request from your server to the token endpoint failed, usually because your client secret is wrong. You can turn on System.Net.Http logs to see that backchannel request and confirm its details.

**Comment by Tratcher** [comment]
Turn on System.Net.Http logs to see what happens on the backchannel.

**Comment by mavjt** [comment]
I am having the same issue after an upgrade to 401.  Here is my trace
[trace_owin.txt](https://github.com/aspnet/AspNetKatana/files/2816322/trace_owin.txt)

**Comment by Tratcher** [comment]
`System.Net.Http Verbose: 0 : [14636] Entering HttpClient#9886408::SendAsync(HttpRequestMessage#21127028: Method: GET, RequestUri: 'https://www.googleapis.com/plus/v1/people/me', Version: 1.1, Content: <null>, Headers:`

I don't think you successfully installed 4.0.1. That's the url 4.0.0 uses. See https://github.com/aspnet/AspNetKatana/commit/110f17f4bf561f14f9010e8eff0712981150a282. Double check your packages config to make sure all Microsoft.Owin packages were updated to 4.0.1. Failing that, uninstall and reinstall them.

**Comment by fxtrade** [comment]
Dear Tratcher,


I've unin stalled and reinstalled all owin packages, all packages with version 4.0.1, still the same behavior...

Please find attached 2 traces files during the login session: working.txt and notworking.txt
The first one is when Google+ API is activated in Google's console.
The second is when Google+ API is deactivated.

The same code is used in both case.

Thanks for your help.

[trace system.net.zip](https://github.com/aspnet/AspNetKatana/files/2818882/trace.system.net.zip)

**Comment by fxtrade** [comment]
Tratcher,

After further investigation it seems there's a problem with "Assembly's manifest definition does not match assembly reference". Don't work on this for now, it seems the issue is in my setup.

**Comment by fxtrade** [comment]
Tratcher, you were right, it was a dll conflict issue. With 4.0.1, it works perfectly in ASP.NET MVC website.
Sorry for the confusion and thank you for your time.
