### ISSUE TITLE
Owin with IIS host  fail to auto-start

### ISSUE THREAD

**Issue by WangFeng2333** [aspnet/AspNetKatana#263]
I have an Owin Web api service , and host it in IIS enviroment, but I found that the Startup method will not fire until there is a http request to the service , and the same case after IIS recyle. But I have some  message to listen by background task of this service, that means I need to set the Application Pool never recyle.

I try to add   <add key="owin:AutomaticAppStartup" value="false" /> to web.config,  but it doesn't work.
And of course ,the Application Pool  is configured as "AlwaysRunning".

Is it possible for owinstartup fired before any http request?

**Comment by Tratcher** [comment]
That's not something controlled by the Microsoft.Owin components, that's controlled by IIS. See https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization

**Comment by Tratcher** [comment]
@pakrym are you aware of better instructions for this feature?

**Comment by pakrym** [comment]
No, that's the only one I know of.

**Comment by WangFeng2333** [comment]
Thanks for the help.
It works after I restart the laptop.
