### ISSUE TITLE
Microsoft.Owin.Hosting.Engine.HostingEngine's HostingTraceListener causes problems

### ISSUE THREAD

**Issue by petsuter** [aspnet/AspNetKatana#266]
The `HostingTraceListener` in [Microsoft.Owin.Hosting.Engine.HostingEngine.EnableTracing](https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Hosting/Engine/HostingEngine.cs#L287) causes weird problems. E.g. `Debug.Writeline` messages get duplicated, tripled and more.

Various [other people](https://stackoverflow.com/questions/48208332/owin-webapp-leads-to-multiple-functions-calls) also [run into these problems](https://stackoverflow.com/questions/17948363/tracelistener-in-owin-self-hosting). The common suggestion to work around these problems seems to be removing `HostingTraceListener`: `Trace.Listeners.Remove("HostingTraceListener")`.

I'm unclear what this does exactly, since ASP.NET / Katana / OWIN doesn't seem to document `HostingTraceListener` anywhere. Is it advisable to remove it? What are the consequences? Why is it added in the first place?

**Comment by Tratcher** [comment]
It's documented here: https://github.com/aspnet/AspNetKatana/wiki/OWIN-Keys

You can remove it if you don't need it.

**Comment by Tratcher** [comment]
It's the first entry "host.TraceOutput". It's for app diagnostics. If you're not debugging then feel free to turn it off.

**Comment by anurse** [comment]
Closing as the question appears to be answered. Let us know if there is further feedback here!
