### ISSUE TITLE
Multiple Authentication middleware - last middleware always called ignoring previous ones.

### ISSUE THREAD

**Issue by NajeebMohammed** [aspnet/AspNetKatana#267]
I have an SSO scenario where user navigates between a sharepoint application and an MVC web app. A user can login to SharePoint application via AD FS (WSFed) using AD credentials or another set of users can login using accounts on an Azure AD tenant. Sharepoint does this pretty neatly.
I'm now looking to configure the MVC web app using OWIN middle layers to enable SSO to customers who are logged in both using WSFed and Openid. I have registered the two middle layers as below. However when the request reaches the web app, the request is always handled by the last middle layer registered (wsfed in this case) which is causing the SSO to work only if the user logged into SharePoint using WSFed and there after navigate to the web app. If the user however logged in to SharePoint using their Azure AD credentials and navigate to the web app, the wsfed auth middle layer is handling the request and presenting an AD FS login screen. Is there anything wrong with my configuration?
```
public void ConfigureAuth(IAppBuilder app)
{
app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);


        app.UseCookieAuthentication(new CookieAuthenticationOptions {
            CookieSecure = CookieSecureOption.SameAsRequest,
            CookieHttpOnly = true,
            SlidingExpiration = false,
            AuthenticationMode = AuthenticationMode.Active,
            
        });
        app.UseOpenIdConnectAuthentication(
             new OpenIdConnectAuthenticationOptions
             {
                 ClientId = clientId,
                 Authority = authority,
                 PostLogoutRedirectUri = postLogoutRedirectUri,
                 AuthenticationMode = AuthenticationMode.Active,
                 
             });
        app.UseWsFederationAuthentication(
       new WsFederationAuthenticationOptions
       {
           Wtrealm = realm,
           MetadataAddress = adfsMetadata,
           AuthenticationMode = AuthenticationMode.Active,
           
       });

}
```

**Comment by NajeebMohammed** [comment]
I have an SSO scenario where user navigates between a sharepoint application and an MVC web app. A user can login to SharePoint application via AD FS (WSFed) using AD credentials or another set of users can login using accounts on an Azure AD tenant. Sharepoint does this pretty neatly. 
I'm now looking to configure the MVC web app using OWIN middle layers to enable SSO to customers who are logged in both using WSFed and Openid. I have registered the two middle layers as below. However when the request reaches the web app, the request is always handled by the last middle layer registered (wsfed in this case) which is causing the SSO to work only if the user logged into SharePoint using WSFed and there after navigate to the web app. If the user however logged in to SharePoint using their Azure AD credentials and navigate to the web app, the wsfed auth middle layer is handling the request and presenting an AD FS login screen. Is there anything wrong with my configuration?

 public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            
            app.UseCookieAuthentication(new CookieAuthenticationOptions {
                CookieSecure = CookieSecureOption.SameAsRequest,
                CookieHttpOnly = true,
                SlidingExpiration = false,
                AuthenticationMode = AuthenticationMode.Active,
                
            });
            app.UseOpenIdConnectAuthentication(
                 new OpenIdConnectAuthenticationOptions
                 {
                     ClientId = clientId,
                     Authority = authority,
                     PostLogoutRedirectUri = postLogoutRedirectUri,
                     AuthenticationMode = AuthenticationMode.Active,
                     
                 });
            app.UseWsFederationAuthentication(
           new WsFederationAuthenticationOptions
           {
               Wtrealm = realm,
               MetadataAddress = adfsMetadata,
               AuthenticationMode = AuthenticationMode.Active,
               
           });
}

**Comment by Tratcher** [comment]
Having more than one middleware with `AuthenticationMode = AuthenticationMode.Active,` has never worked well. Your choices are:
A) When you Authorize/Challenge you specify openidconnect or wsfed.
B) You make cookies the only active one and have that redirect to a login page where the user selects openidconnect or wsfed. This is how the Individual Auth template works with external providers.

**Comment by anurse** [comment]
Closing as the question has been answered. We don't have plans to change this behavior.
