### ISSUE TITLE
Index was outside the bounds of the array. - owinContext.Environment.Add(X,Y)

### ISSUE THREAD

**Issue by olegmkr** [aspnet/AspNetKatana#268]
Hi,

With bigger load as usual we get error:

Message":"Index was outside the bounds of the array.","Data":{},"StackTrace":"   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)\r\n   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.Add(String key, Object value)\r\n   at Asdfgh.AddCurrentRouteName(IDictionary`2 environment, Guid requestId, String metricName) ....

We have extension with method

public static class HttpContextExtensions
{
	public static void AddCurrentRouteName(this IDictionary<string, object> environment, Guid requestId, string value)
        {
            environment.Add(requestId, value);
        }
}

And this method we call in ActionFilterAttribute

public class TestAttribute : ActionFilterAttribute
    {
        public override async Task OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
        {
            OwinContext ctx = null;

            if (actionContext.Request.Properties.ContainsKey("MS_OwinContext"))
            {
                ctx = actionContext.Request.Properties["MS_OwinContext"] as OwinContext;
            }

            if (ctx != null)
            {
                ctx.Environment.AddCurrentRouteName(actionContext.Request.GetRequestId(), "123456");
               
            }

            await base.OnActionExecutingAsync(actionContext, cancellationToken).ConfigureAwait(false);
        }
    }

Error happens because multithreaded environment and dictionary doesn't thread safe https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?redirectedfrom=MSDN&view=netframework-4.7.2

What's the best solution for this situation?

**Comment by Tratcher** [comment]
Do not multithread individual requests, it's not supported for exactly this reason.

**Comment by olegmkr** [comment]
We use DefaultHttpBatchHandler (https://books.google.lt/books?id=7aE8BAAAQBAJ&pg=PA187&lpg=PA187&dq=DefaultHttpBatchHandler+webapi&source=bl&ots=fwWaNUWsQH&sig=ACfU3U1H52fdI6b2UIJzV0t8uSAFmWyjxQ&hl=lt&sa=X&ved=2ahUKEwjZxvbxqKfgAhWJr6QKHSIKB0AQ6AEwB3oECAMQAQ#v=onepage&q=DefaultHttpBatchHandler%20webapi&f=false) for batch request - multipart/mixed. We want that every request has property which we can access in OWIN middleware.

How would you recommend to fix it? But the main problem is how to get inner request route template (actionContext.ControllerContext.RouteData.Route.RouteTemplate) in Middleware.
