### ISSUE TITLE
Domain not set for nonce cookie

### ISSUE THREAD

**Issue by kleinbiker** [aspnet/AspNetKatana#269]
When adding/deleting nonce cookies, the domain isn't being set. This causes a problem for our scenario with multiple sub-domains.

**Comment by Tratcher** [comment]
What sort of problems? The nonce cookies use unique names to avoid collisions.

**Comment by kleinbiker** [comment]
Sorry, my mistake, this isn't an issue.

**Comment by kleinbiker** [comment]
This may be an uncommon scenario and we are working around it. I just wanted to clarify why we would have preferred having the domain set on the nonce cookie.

Our domain structure:
accounts.mydomain.com
content1.mydomain.com
content2.mydomain.com....

accounts site handles all user/auth management. 

In CookieAuthenticationOptions:
CookieDomain=mydomain.com
In OpenIdConnectAuthenticationOptions
RedirectUri=http://accounts.mydomain.com/somedir/idprovidercallback.aspx

Now the issue is:
- user navigates to http://content1.mydomain.com/ 
this currently gets us a nonce cookie with no domain set i.e. browser will send it back only for content1.mydomain.com
- on the callback to http://accounts.mydomain.com/somedir/idprovidercallback.aspx, nonce cookie isn't supplied by the browser and we get an an invalid nonce exception - Exception type: OpenIdConnectProtocolInvalidNonceException.

We are working around this in the RedirectToIdentityProvider notification by tacking on the domain in OpenIdConnectMessage.Response.Headers.

Is there a different way of handling this scenario? Thx.

**Comment by Tratcher** [comment]
You could wrap the ICookieManager to add the domain.
https://github.com/aspnet/AspNetKatana/blob/58d945af6c40ac5d50b6a722efb52016cabdf572/src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs#L296

**Comment by kleinbiker** [comment]
Thanks, that's cleaner and also takes care of the cookie deletion on the post back to idprovidercallback.aspx. Have switched to that.
