### ISSUE TITLE
Support NetStandard 1.6

### ISSUE THREAD

**Issue by damianh** [aspnet/AspNetKatana#27]
Use case: easy porting of **lots** of existing code without having to rewrite entire applications.

Would be happy to attempt a PR.

**Comment by VictorBlomberg** [comment]
This is a really important issue. Would be able to try to help, too.

Any input from maintainers?

**Comment by Tratcher** [comment]
This is a non-starter due to at least three critical net45 dependencies:
1. Owin.dll
2. System.Web
3. HttpListener

There are discussions going for 1 and 3, but 2 isn't happening.

**Comment by MaximRouiller** [comment]
From what I heard... 2 is an absolute no go.

It would break so many backward compatibilities it wouldn't be funny.

**Comment by Tratcher** [comment]
If you got Owin.dll then you can port most of the libraries/middleware. If you get HttpListener then you can run self-hosted apps. System.Web isn't going to happen though, so you can't convert IIS hosted apps.

**Comment by MaximRouiller** [comment]
The future is .NET Core if I got it right. Katana and Owin is all fun but if you want to run everywhere and be where the investment is? Core is the way to go.

**Comment by damianh** [comment]
> There are discussions going for 1 and 3, but 2 isn't happening.

+ 1. 3 could be replaced with  Also the cookies middleware with its dependency on DPAPI is probably a no-go too.

(FYI I did this https://www.nuget.org/packages/KatanaNetStandard/ to unblock myself and team)

**Comment by panesofglass** [comment]
Why can you not merge the interfaces from Owin.dll into this package? Also, where is that discussion?

**Comment by panesofglass** [comment]
@Tratcher can we transfer the owin.dll project to the ASP.NET org? You would still have publishing, etc; it just wouldn't be owned by owin anymore. Wouldn't that resolve all the issues?

**Comment by Tratcher** [comment]
There hasn't been any progress and there are no plans to pursue this further. Closing.
