### ISSUE TITLE
id_token not supplied on logout

### ISSUE THREAD

**Issue by kleinbiker** [aspnet/AspNetKatana#270]
On logout we get an error from our idprovider that id_token wasn't supplied.

Looking through the Katana sources, I don't see the IdToken/IdTokenHint getting set anywhere in the code.

In the AspNet Core sources, I see the following in SignOutAsync:
// Attach the identity token to the logout request when possible.
            message.IdTokenHint = await Context.GetTokenAsync(Options.SignOutScheme, OpenIdConnectParameterNames.IdToken);

As a workaround, in the RedirectToIdentityProvider notification I am setting the ProtocolMessage.IdTokenHint on logout and it works fine.

Is that the best way to handle this? Thx.

**Comment by Tratcher** [comment]
Yes, that's a good solution.

**Comment by kleinbiker** [comment]
Got it, thanks.
