### ISSUE TITLE
HTTP Error 401.0 - open id connect nonce cookie not being set

### ISSUE THREAD

**Issue by kamranbashir** [aspnet/AspNetKatana#274]
This is intermittent issue coming on windows azure web app. When we restart web app and recycle app pool.
we get
**HTTP Error 401.0 - Unauthorised
You do not have permission to view this directory or page.**

in case of 401 we are not redirecting to IDP/ODIC login page (which is b2c login page in my case)

Some sample code here:
```
  public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            int index = 1000;
            foreach (var record in SystemKeys.AppSettings)
            {
                app.MapWhen(
                            context => (HttpContext.Current.Request.Url.BaseURL() == record.Key),
                            config =>  
                            {
                                var customer = record.Value;
                                config.UseOpenIdConnectAuthentication(CreateOptionsFromPolicy(index, customer.B2CPasswordResetPolicyId,
                                                        customer.B2CAadInstance, customer.B2CTenant, customer.B2CSignInPolicyId,
                                                        customer.B2CApplicationId, customer.WebUrl
                                    ));

                                config.UseOpenIdConnectAuthentication(CreateOptionsFromPolicy(index, customer.B2CSignInPolicyId,
                                                        customer.B2CAadInstance, customer.B2CTenant, customer.B2CSignInPolicyId,
                                                        customer.B2CApplicationId, customer.WebUrl
                                    ));
                            }
                        );
                index++;
            }


        }
```

**Comment by Tratcher** [comment]
How does the 401 relate to the nonce cookie? Do you just mean that you specified a 401 in the application and the expected middleware did not take over, set a 302, and add a nonce cookie?

**Comment by kamranbashir** [comment]
yes. middleware did not take over, set a 302, and add a nonce cookie

**Comment by Tratcher** [comment]
My first suspicion would be your custom routing `context => (HttpContext.Current.Request.Url.BaseURL() == record.Key)` I'd start by using an OrdinalIgnoreCase comparison. Also adding a log after all of your MapWhen's to make sure no requests fall through.

**Comment by kamranbashir** [comment]
Issue has been fixed. For a given url we were requesting b2c config data from API and some silly stuff was going there causing blockage. It is too long story i will end here. 

Thank you Tratcher
