### ISSUE TITLE
How to handle Owin Facebook and Twitter Cancel in Web API using 4.0.1.0 version of packages

### ISSUE THREAD

**Issue by faceoffers28** [aspnet/AspNetKatana#275]
I am using Owin in both my MVC 5 Web App and Web API 2. A Cancel seems to be handled correctly in my MVC Web App. The same can not be said for my Web API. When I Cancel a Twitter and Facebook login, I am presented with a dialogue box and an option to Return. Here are the resulting URL options.

TWITTER
https://api.domain.com/signin-twitter?denied=

FACEBOOK
https://api.domain.com/signin-facebook?error=access_denied&error_code=&error_description=

Ultimately, both requests end up here.

https://api.domain.com/#error=access_denied

I see that there used to be a OnRemoteFailure method in the Events handler for both FacebookAuthenticationOptions and TwitterAuthenticationOptions, but I can't find it in the version  4.0.1.0 version of the packages.

How can we redirect the user back to the original page after they cancel a Facebook or Twitter login request or when an error occurs?

Any help is much appreciated! Thanks!

**Comment by faceoffers28** [comment]
I'm not sure if this is the correct way to handle this, but here is what I did.

I added string redirect_uri to my GetExternalLogin method.

```
//Other attributes not listed
[Route("ExternalLogin", Name = "ExternalLogin")]
public async Task<IHttpActionResult> GetExternalLogin(string provider, string redirect_uri, string error = null)
{
       if (error != null)
            {
                //return Redirect(Url.Content("~/") + "#error=" + Uri.EscapeDataString(error));
                return Redirect(redirect_uri + "#error=" + Uri.EscapeDataString(error));

            } 
}
```
This will redirect the user back to the redirect_uri and adds the #error hash.

**Comment by Tratcher** [comment]
OnRemoteFailure is an AspNetCore API, it's not available here. That's not a bad workaround.
