### ISSUE TITLE
Connecting a logger to OAuthAuthorizationServerHandler

### ISSUE THREAD

**Issue by gjdownes** [aspnet/AspNetKatana#276]
I'm trying to debug `invalid_grant` errors I'm receiving in production, most of which appear to originate from the `OAuthAuthorizationServerHandler` class.

I'm just curious how do I connect the logger to my application logger. Would it be as simple as follows?

    app.SetLoggerFactory(ILoggerFactory);

I'm looking to troubleshoot log output like the following:

    _logger.WriteError("expired refresh token");
    validatingContext.SetError(Constants.Errors.InvalidGrant);

Any general tips on troubleshooting invalid_grant errors when refreshing OAuth tokens would also be appreciated.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/AspNetKatana/wiki/Debugging#logging for the standard logging system.

**Comment by anurse** [comment]
Closing as the question has been answered. Feel free to let us know if you have further feedback!
