### ISSUE TITLE
[Facebook] api version used 2.8 won't be supported after April 18, 2019

### ISSUE THREAD

**Issue by coronag** [aspnet/AspNetKatana#277]
https://developers.facebook.com/docs/graph-api/changelog
=> v2.8 is available until April 18, 2019 and is still used as the default one here:
https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.Facebook/Constants.cs

**Comment by Tratcher** [comment]
It will auto roll forward to 2.9 and there's no indication of any breaking changes. You can confirm by updating the endpoints directly:
https://github.com/aspnet/AspNetKatana/blob/58d945af6c40ac5d50b6a722efb52016cabdf572/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationOptions.cs#L36-L38

**Comment by astalegale** [comment]
https://developers.facebook.com/docs/graph-api/changelog
=> v2.9 is available until 22 July, 2019

**Comment by coronag** [comment]
@astalegale : you can update at your convenience the endpoint directly as said by Tratcher, to use the last api version for instance.
