### ISSUE TITLE
DefaultLoader.SearchForStartupAttribute get all assembly attribute instances during initialization

### ISSUE THREAD

**Issue by jinek** [aspnet/AspNetKatana#278]
Method DefaultLoader.SearchForStartupAttribute executes 
`customAttributes = referencedAssembly.GetCustomAttributes(false);`
Which means instantiating of all assembly attributes (that is not necessary and can bring problems)
Can be replaced by
`customAttributes = referencedAssembly.GetCustomAttributes<OwinStartupAttribute>(false);`
or similar.

**Comment by Tratcher** [comment]
This one? https://docs.microsoft.com/en-us/dotnet/api/system.reflection.customattributeextensions.getcustomattributes?view=netframework-4.7.2#System_Reflection_CustomAttributeExtensions_GetCustomAttributes__1_System_Reflection_Assembly_

**Comment by jinek** [comment]
Yes, or this https://docs.microsoft.com/en-us/dotnet/api/system.reflection.customattributeextensions.getcustomattributes?view=netframework-4.7.2#System_Reflection_CustomAttributeExtensions_GetCustomAttributes_System_Reflection_Assembly_System_Type_

If will be planned, let me do?

**Comment by Tratcher** [comment]
Feel free to send a PR.

**Comment by jinek** [comment]
I see you did it for some reason 6 years ago, you also introduced
Owin.Loader.Tests.OwinStartupAttribute with a comment // Alternate definition, used to confirm that there is not a direct type dependency.
But I can't find the reason, do we still want to be independent from type *Microsoft.Owin.OwinStartupAttribute* ?
Because logic here seems strange for me: if I introduced my own attribute with name OwinStartupAttribute it will work as a startup attribute.

**Comment by Tratcher** [comment]
I'd forgotten about that. Yes it was intentionally type decoupled but I don't remember the reasoning. Best not to break that at this point though.

What was your issue with loading the attributes?

**Comment by jinek** [comment]
That is fine, this still can be used: https://docs.microsoft.com/en-us/dotnet/api/System.Reflection.Assembly.GetCustomAttributesData?view=netframework-4.5
It should not break anything and won't instantiate all attributes.

My issue was that one assembly happened to be in bin folder does not have all dependencies, some of them were referenced in assembly level attributes. Thus trying to instantiate such an attribute will lead to AssemblyLoadException.
