### ISSUE TITLE
"No owin.Environment item was found in the context" in webapp when GAC "Microsoft.Owin.Host.SystemWeb.dll"

### ISSUE THREAD

**Issue by chatikul** [aspnet/AspNetKatana#28]
My web application work correctly when run with **Microsoft.Owin.Host.SystemWeb.dll** in local bin folder (private dll). But when I need to GAC this dll to Global Assembly Cache, web application show "No owin.Environment item was found in the context" error when I call HTTPContext.GetOwinContext() method. 

Note: I used **fuslogvw.exe** to check dll binding when web application startup. Difference is that for private dll, when web application startup, it load **Microsoft.Owin.Host.SystemWeb.dll** immediately, but GAC does not. 

And I use **Microsoft.Owin.Host.SystemWeb.dll** version 3.0.0.

Please advice me how to fix it if I need to GAC this dll.

Thanks,
Anucha T.

**Comment by damianh** [comment]
Curious as to why you are putting this in the GAC?

**Comment by chatikul** [comment]
Thanks for you reply, I putting this file to the GAC because I have many web applications use this file in single machine. And i need to control all applications use the same dll file and same version in one place (versioning control). Normally, I putting all shard files in the GAC. Ex. EntityFramework, OPD.NET dlls.

**Comment by damianh** [comment]
That doesn't really is say _why_. What is the actual benefit of that
approach? Version control is handled in source control.

A way to fix your problem, use xcopy deploy and stop using the GAC. There
is no GAC in .net core so you'll have to stop using it eventually anyway.

**Comment by chatikul** [comment]
The source control is a versioning of source file in your development environment. You can control file version before build of each application. In production, after build, If you have 30 applications on one machine use this file and would like to upgrade to use new version of this file with out recompile source code (Dll change with out affect method interface). How do you do? Copy of dll file to each application folder and configure each application configuration file to redirect assembly version? Or just use GAC feature and publisher policy to redirect assembly version (configure only one place)? 

You can see Oracle patch work. Each time when Oracle release new dll (OPD.NET), Oracle will GAC there dlls and use publisher policy to redirect all application reference to use new version of dlls.

And I have many other reasons to GAC shared dll. Ex. Faster performance at startup application with NGen. File Security of dll, etc.... (follow by GAC features)

By the way, I would like to know. Is **Microsoft.Owin.Host.SystemWeb.dll** support GAC? If yes, how should I do?  

Thanks,
Anucha T.

**Comment by damianh** [comment]
Your approach means one bad update can take out 30 applications and your
approiach is not (/no longer) standard practice in .net.

Instead, apply the practice of continous integration and deploy all 30
applications independently, but automated.

Oracle's drivers are available as nuget packages (which are not gac'd).

**Comment by MaximRouiller** [comment]
Exactly what @damianh just said.

If you are deploying a new sub dependency, your are effectively deploying a new version of your 30 applications. You may not want to face it, but you are. Every single application is going to depend on that DLL to work properly. Has it been tested in each apps? Has it been compiled against each apps?

What you are telling us is: "No. We'll see in production"

That, in itself, is very bad.

**Comment by Tratcher** [comment]
Microsoft.Owin.Host.SystemWeb.dll uses a PreApplicationStartMethod attribute to load itself into the web app. This may not work with assemblies in the GAC.  There are other ways to load SystemWeb into the app, such as specifying it in the web.config. Haven't tried this in a while... I think you can just add it to the module list.

https://github.com/aspnet/AspNetKatana/blob/f3a8d848b7548e62d52737efa0a4fc9cf6c6cedf/src/Microsoft.Owin.Host.SystemWeb/PreApplicationStart.cs#L11

**Comment by chatikul** [comment]
Thank a lot to @Tratcher. That is the good answer, point to the problem. Now, I leave only this file in private DLL. 

Thanks again.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
