### ISSUE TITLE
OAuth2.0 integration with Xamarin

### ISSUE THREAD

**Issue by thiruvenkadame** [aspnet/AspNetKatana#281]
OAuth2.0 integration with Xamarin

1. We build our own "OWIN OAuth 2.0 Authorization Server" using "Microsoft.AspNet.Identity.Owin" and "Microsoft.Owin" framework. Ref: https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-oauth-20-authorization-server 

2. We can be able to send a request to our custom OAuth2.0 server and get OAuth2.0 access token from web applications by using "DotNetOpenAuth.OAuth2.Client".

3. Also, we can be able to successfully integrate our custom OAuth2.0 server with Cortana bot channel and its working fine.

4. But while integrating our custom OAuth2.0 server with Xamarin mobile application we are facing issues related to redirect_uri. We get a response like invalid_grant.

4. We are using "Xamarin.Auth" framework in Xamarin to send the OAuth request.

5. Here is the redirect_uri, we used in Web and Mobile 
a. Xamarin app redirect_uri: com.Demo.Mobile:/oauth2redirect
 b. Web site redirect_uri: https://demowebsite.azurewebsites.net/

![image](https://user-images.githubusercontent.com/5037741/54964768-10d0ca80-4f44-11e9-9fd9-92673f07f919.png)

Thanks in advance for help on this :)

**Comment by Tratcher** [comment]
You're going to need more detail to debug that. Start by capturing and sharing a trace of the HTTP requests using a tool like Fiddler.

**Comment by thiruvenkadame** [comment]
We resolved the issue by using this redirect_uri pattern oauth2redirect:/com.company.package/
