### ISSUE TITLE
Unable to login to my azure website using Facebook external login via Microsoft.owin.security.facebook oauth library

### ISSUE THREAD

**Issue by dlwennblom** [aspnet/AspNetKatana#282]
It works when I use debug mode on my local machine.  However, when I publish the site to [https://seekerworksnet.azurewebsites.net](https://seekerworksnet.azurewebsites.net), go to the login page, click the (Continue with Facebook) button, all I see is "#=" appended to the address line.  I am able to login using Google, Twitter and Microsoft external logins, however.  I don't know what to do to resolve this.  I created a bug report on facebook and they said:

Thanks for reaching out. This issue could come from the third party library (Microsoft.owin.security.facebook oauth library), and so I'd recommend filing a bug report with the library directly.

Here's a link to the bug report: [https://developers.facebook.com/support/bugs/342100196416464/](https://developers.facebook.com/support/bugs/342100196416464/)

**Comment by Tratcher** [comment]
Please capture and share a Fiddler trace file. App logs may also be useful. https://github.com/aspnet/AspNetKatana/wiki/Debugging#logging

**Comment by dlwennblom** [comment]
How can I use fiddler with an Azure web app?  I’m not running a virtual machine.

 

Thanks.

Daniel Wennblom

 <mailto:daniel.wennblom@seekerworks.com> daniel.wennblom@seekerworks.com 

Tel: 763.262.0333

Cell: 763.367.0302

MCSD: Microsoft Certified Solutions Developer

**Comment by Tratcher** [comment]
You use it on the client, not the server. Make sure you enable HTTPS decryption.

**Comment by dlwennblom** [comment]
Sorry- it’s been a few years since I used it last.  Did I attach the right file?

 

Thanks.

Daniel Wennblom

 <mailto:daniel.wennblom@seekerworks.com> daniel.wennblom@seekerworks.com 

Tel: 763.262.0333

Cell: 763.367.0302

MCSD: Microsoft Certified Solutions Developer

**Comment by Tratcher** [comment]
No, I don't think you can do github attachments via e-mail.

**Comment by dlwennblom** [comment]
[Facebook login.zip](https://github.com/aspnet/AspNetKatana/files/3025039/Facebook.login.zip)
Is this better?

**Comment by Tratcher** [comment]
Better. Everything on the client looks fine, it comes back to /signin-facebook with the expected parameters. However it looks like the backchannel call between your server and facebook fails with a generic `error=access_denied`. That's trickier to debug.

Out of curiosity does it work if you remove these lines?
```
facebookOptions.AuthorizationEndpoint = "https://www.facebook.com/v3.2/dialog/oauth";
facebookOptions.TokenEndpoint = "https://graph.facebook.com/v3.2/oauth/access_token";
facebookOptions.UserInformationEndpoint = "https://graph.facebook.com/v3.2/me";
```

Also, double check the value of UseFacebookAuthenticationappSecret, that's only used on the backchannel.

**Comment by dlwennblom** [comment]
I added the lines above because I got a notice from Facebook:

Your App, SeekerWorksNET (localhost), is currently accessing Graph API v2.8 which will reach the end of its 2-year lifetime on 18 April, 2019. We estimate 1 endpoint that SeekerWorksNET (localhost) calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.9 or higher.

So, I changed everything to use 3.2  However, I got the same results with 2.8 as I did with 3.2, so it didn't fix anything as I'd hoped.  As for the secret, I copied and pasted from Facebook, rather than keying it in.

Doh!  I see I forgot to update the secret.  It was the same as my localhost secret.  Stupid error on my part.  IT WORKS NOW THAT I UPDATED IT.  Thank you so much for your assistance!
