### ISSUE TITLE
oauth2 How do I customize the message structure

### ISSUE THREAD

**Issue by LFDCC** [aspnet/AspNetKatana#283]
I tried oauth2 and found that the returned structure is {"error":" message"}. If I want to return the custom structure {"result":"000000"}, how can I do it?

I tried this method context.response.write ("{\"result\": "000000\"}"), but the default result will be appended, and it will be {"result":"000000"}{"error":" message"}

**Comment by Tratcher** [comment]
You're going to need to be more specific about which component and endpoint you're using.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
