### ISSUE TITLE
Manually validate token

### ISSUE THREAD

**Issue by polterguy** [aspnet/AspNetKatana#285]
Sorry, but I am bewildered within all the _"automagic middleware"_ in regards to a legacy project I am currently maintaining, and I could really need some help. My reasons is that I am using _two distinctly different authentication mechanisms_: One doing ActiveDirectory/SSO authentication for employees where I work, and another using a (legacy) authentication website, which again uses Katana. Hence, I'll need to manually parse the OWIN token in my .Net Framework code.

My own code (Active Directory), I have complete control over, and I am using JWT tokens, which works perfectly fine. The other (legacy parts) though, is like banging my head towards a wall ... :(

The (legacy) code that generates the token resembles the following (roughly).

```csharp
var foo = app.CreateDataProtector(typeof(OAuthAuthorizationServerMiddleware).FullName, "Access_Token", "v1");
    var atFormat = new TicketDataFormat(foo);
    AuthorizationOptions = new OAuthAuthorizationServerOptions {
        TokenEndpointPath = new PathString("/some-path/token"),
        Provider = new OAuthProvider("self", slFactory),
        AuthorizeEndpointPath = new PathString("/some-path/authorize"),
        AccessTokenFormat = atFormat,
        AccessTokenProvider = new AccessTokenProvider(),
        AccessTokenExpireTimeSpan = GetAccessTokenExpiration(),
        RefreshTokenProvider = new RefreshTokenProvider(slFactory)
    };
```

Since I have two different mechanisms to validate tokens, I can't use any of the _"automagic middleware"_, and I have to resort to manually validating my tokens ...

The closest I have come, is some code I found through StackOverflow, which looks like the following.

```csharp
private class MachineKeyProtector : IDataProtector
{
    private readonly string[] _purpose =
    {
        typeof(OAuthAuthorizationServerMiddleware).FullName,
        "Access_Token",
        "v1",
    };

    public byte[] Protect(byte[] userData)
    {
        throw new NotImplementedException();
    }

    public byte[] Unprotect(byte[] protectedData)
    {
        return MachineKey.Unprotect(protectedData, _purpose);
    }
}

private void VerifyOAuthToken(string token)
{
    var access_token = token;
    var secureDataFormat = new TicketDataFormat(new MachineKeyProtector());
    var ticket = secureDataFormat.Unprotect(access_token);
}
```

Now obviously, the `MachineKey.Unprotect` fails, since the token was not created with my `MachineKey`, it was created on another machine. However, I am not even sure what key was used to generate the thing ...!! :S

The way I have my basic architecture, is by having created my own `ActionFilterAttribute`, for then to wrap the actual token the client passes to the controller inside of a nested JSON object, base64 encoding it, ending up like the following (without base64 encoding).

```javascript

// AD token
{
  "AD": "some-token-goes-here"
}

// Legacy token
{
  "OAuth": "some-token-goes-here"
}
```

Then I base64 encode the whole thing, and adds it up in the `Authorization` HTTP header as a _"Bearer"_ token, for then during HTTP requests manually extract the Bearer content, base64 DE-code it, and validate it.

This allows me to transparently exchange my authenticate logic, depending upon the structure of the JSON. `{"AD":"xxx"}` ==> JWT and `{"OAUTH":"xxx"}` ==> Katana token ...

How can I manually validate the token Katana has created for me?

Obviously, I'll need the encryption key that was used to generate it in the first place, however I have no clues what so ever even what this is, or how to figure out which key was used to protect it, etc ...

Please advice :)

**Comment by Tratcher** [comment]
Most of the components should be available for you to call directly, but there are several layers you'll need to assemble.

Setting up the DataProtection/MachineKey is a good place to start. Are you running in IIS or in your own application (self-hosted)? For IIS the key sharing is configured in the Web.Config file.
https://stackoverflow.com/a/3855874/2588374

**Comment by polterguy** [comment]
I actually solved this, by simply completely bypassing it, since the OWIN endpoint will only return 200 status code if it successfully authenticates the user, at which point I (from the server) have everything I need to create a _"traditional"_ JWT token myself, using the same logic as I use for AD accounts ...

Hence, I don't need to validate the token, and can simply create my own JWT token, completely independent upon the OWIN endpoint ...

But thx :)

In fact, I should probably be punished for not considering this, before having spent 3 days Googling and reading before it dawned upon me ...!! :S
