### ISSUE TITLE
Customize 401 Unauthorized error message

### ISSUE THREAD

**Issue by lluismontero** [aspnet/AspNetKatana#286]
Hi,

Is there any way to customize the message returned when there is a 401 Unauthorized error? We want to provide more information about the error to our API consumers.

The message we are getting on any bearer token validation error is:
`{"message": "Authorization has been denied for this request."}`

We are using the OAuth bearer authentication and have implemented our "OAuthBearerAuthenticationProvider" to do some checks on the requesting access token. We are rejecting the request by using `context.SetError("unauthorized_client", "ERROR DESCRIPTION");`. The rejection works as expected but we could not find any way to send this message to the users.

**Comment by Tratcher** [comment]
No, not in the current design.

**Comment by lluismontero** [comment]
Could you point us to where this error message is generated so we can look to find any way to accomplish that? We haven't been able to find it.

**Comment by Tratcher** [comment]
Found it at the MVC/WebApi layer:
https://github.com/aspnet/AspNetWebStack/blob/749384689e027a2fcd29eb79a9137b94cea611a8/src/System.Web.Http/Properties/SRResources.resx#L385
https://github.com/aspnet/AspNetWebStack/blob/749384689e027a2fcd29eb79a9137b94cea611a8/src/System.Web.Http/AuthorizeAttribute.cs#L145-L156
