### ISSUE TITLE
Is Microsoft.Owin.Security.OpenIdConnect 4.0.1.0 compatible with Microsoft.IdentityModel.Protocols.OpenIdConnect 5.4.0.0

### ISSUE THREAD

**Issue by jordyvaneijk** [aspnet/AspNetKatana#287]
I keep getting the following exception over and over again after updating my asp.net (WebForms) "Website" not  "WebProject"

> `Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

this is comming from my Startup.cs

here is the full Assembly load trace:
> `=== Pre-bind state information ===
LOG: DisplayName = Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Jordy van Eijk/source/repos/EffyTool/webos_net/
LOG: Initial PrivatePath = C:\Users\Jordy van Eijk\source\repos\EffyTool\webos_net\bin
Calling assembly : Microsoft.Owin.Security.OpenIdConnect, Version=4.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Jordy van Eijk\source\repos\EffyTool\webos_net\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/webos_net/29fc6d5c/1c9d7ec/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/webos_net/29fc6d5c/1c9d7ec/Microsoft.IdentityModel.Protocols.OpenIdConnect/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
LOG: Attempting download of new URL file:///C:/Users/Jordy van Eijk/source/repos/EffyTool/webos_net/bin/Microsoft.IdentityModel.Protocols.OpenIdConnect.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.`

And here the full stacktrace:
> `[FileLoadException: Could not load file or assembly 'Microsoft.IdentityModel.Protocols.OpenIdConnect, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   EffyTool.Startup.Startup.ConfigureAuth(IAppBuilder app) in C:\Users\Jordy van Eijk\source\repos\EffyTool\webos_net\App_Code\cs\Startup\Startup.Auth.cs:101
   EffyTool.Startup.Startup.Configuration(IAppBuilder app) in C:\Users\Jordy van Eijk\source\repos\EffyTool\webos_net\App_Code\cs\Startup\Startup.cs:57`

> `[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +142
   Owin.Loader.<>c__DisplayClass18_1.<MakeDelegate>b__0(IAppBuilder builder) +93
   Owin.Loader.<>c__DisplayClass9_0.<LoadImplementation>b__0(IAppBuilder builder) +212
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +870
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +51
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +101
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +135
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +160
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +580
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +165
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +267
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +341`

> `[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +523
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +107
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +688`

I added all the following packages through nuget
packages.config (only relevant packages):
`<packages>
  <package id="IdentityModel" version="1.9.2" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.4.0" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Logging" version="5.4.0" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.4.0" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.4.0" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.4.0" targetFramework="net45" />
  <package id="Microsoft.Owin" version="4.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security" version="4.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.0.1" targetFramework="net45" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.0.1" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net471" />
  <package id="Owin" version="1.0" targetFramework="net45" />
</packages>`

I hope someone can shed some light on this issue, and what i'm doing wrong.
For me the question is is `Microsoft.IdentityModel.* v5.4.0` compatible with `Microsoft.Owin.* v4.0.1`

**Comment by Tratcher** [comment]
https://www.nuget.org/packages/Microsoft.Owin.Security.OpenIdConnect/4.0.1 depends on Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 5.3.0).

You should be able to use it with IdentityModel 5.4 but you'll have to ensure your application has binding redirects from 5.3 to 5.4. Also, ensure you update all of the identity model packages to the same version.

Microsoft.IdentityModel.Logging (>= 5.3.0)
Microsoft.IdentityModel.Protocols (>= 5.3.0)
Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 5.3.0)
Microsoft.IdentityModel.Tokens (>= 5.3.0)
System.IdentityModel.Tokens.Jwt (>= 5.3.0)
