### ISSUE TITLE
Problem with State received URLEncoded

### ISSUE THREAD

**Issue by alexliard** [aspnet/AspNetKatana#288]
We are using Microsoft.Owin.Security.OpenIdConnect.OpenidConnectAuthenticationHandle in order to do OpenID Authentication into our application.
One of our client is using Siteminder as their OpenId platform. When Siteminder redirects to our application the POST request contains the state URLEncoded. This cause the library to fail with an error saying that the state is missing or invalid. This is caused by the state being encoded on their end and having "%3F" instead of "=" in the state.
Is there a way to workaround this?

**Comment by Tratcher** [comment]
Can you show the whole state field in the OIDC message / form POST for context? Is it like this?
`state=OpenIdConnect.AuthenticationProperties%3FSomeBase64Blob`
That state is created here:
https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L151
And read here:
https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L242
You should be able to intercept it at the OnMessageReceived notification and fix up the state field in the ProtocolMessage.
https://github.com/aspnet/AspNetKatana/blob/0f6dc4bf2722fb08759da3eacaf38f2a098771bd/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L226-L230
