### ISSUE TITLE
Wiki links still point to Codeplex which is dead

### ISSUE THREAD

**Issue by IanKemp** [aspnet/AspNetKatana#289]
E.g. https://github.com/aspnet/AspNetKatana/wiki and https://github.com/aspnet/AspNetKatana/wiki/Hello-World link to long-dead http://aspnet.codeplex.com/ - not sure if these should rather go to https://github.com/aspnet/AspNetCore

**Comment by Tratcher** [comment]
Updated. Let me know if you find any others.
