### ISSUE TITLE
CookieAuthenticationHandler, in case using SessionStore, cookieOptions.Expires is not set on renewal

### ISSUE THREAD

**Issue by JaapMosselman** [aspnet/AspNetKatana#29]
I think I found an issue in Microsoft.Owin.Security.Cookies.CookieAuthenticationHandler class, method ApplyResponseGrantAsync. There is a line (within "else if (_shouldRenew)" block) of where cookieOptions.Expires property is set if model.Properties.IsPersistent is true. The problem is that, in case of using a SessionStore, model.Properties.IsPersistent is always false, because in that case model is assigned a new instance with clean options. 
So the cookie send to the browser is now a session cookie and when the browser is closed and reopened, the user must login again.

See also the ASP.NET core repository: https://github.com/aspnet/Security/issues/973
There they have already fixed the issue. But that does not help me, as I am still using this library.
Hopyfully it will be fixed here also

**Comment by JaapMosselman** [comment]
Great. Any idea when 3.1.0 will be released?

**Comment by Tratcher** [comment]
@JaapMosselman Likely next week.

**Comment by MaximRouiller** [comment]
No release today with that wonderful cowboy hat @Tratcher ? 😉
