### ISSUE TITLE
Customizing Authorization header

### ISSUE THREAD

**Issue by glaydersen** [aspnet/AspNetKatana#292]
Hi,
Is there a way to customize the "Authorization" header key?
We are moving our app to a server that is behind a Basic authentication, so I have to send "Authorization: Basic XXX" in the header.
We are thinking about changing our "Authorization: Bearer XXX" to something like "X-Authorization: Bearer X" so it won't conflict with the firewall basic authentication.

Any help is welcome!
Thanks!

**Comment by Tratcher** [comment]
You want every request to be authenticated using Basic and Bearer? That seems redundant.

There is an event that lets you override the header:
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Security.OAuth/OAuthBearerAuthenticationHandler.cs#L37-L42

**Comment by glaydersen** [comment]
@Tratcher Our API uses oAuth only. The problem is that we need to add the basic authentication to pass our firewall.
I will check your example. Thanks.
