### ISSUE TITLE
Identity(claims) property for External User

### ISSUE THREAD

**Issue by santhoshbomma9** [aspnet/AspNetKatana#293]
Identity property in Microsoft.Owin.Security.AuthenticationTicket class doesn’t contain the UPN claim for External users in the Azure AD B2C but for internal users it’s fine. Is this expected behaviour?

**Comment by Tratcher** [comment]
There's nothing in this repo that targets Azure AD B2C. What components are you using?

**Comment by santhoshbomma9** [comment]
Hi Chris,
Thanks for your reply. Let me explain a bit more clearer. 
We have an ASP.NET application which is listed in Azure AD app registrations. Azure AD contains both directory users (eg: internaluser@azuredomain.onmicrosoft.com) and also External users(like external@gmail.com). 
We have UseOpenIdConnectAuthentication in our Startup.Auth.cs. On AuthorizationCodeReceived we read the context.AuthenticationTicket.Identity which returns the claims. In the list of Claims, UPN claim exists for internaluser@azuredomain.onmicrosoft.com but not for external@gmail.com. I would guess all the users listed in an Azure AD would have a UPN(for the external user it would be external_gmail.com#EXT#@azuredomain.onmicrosoft.com). 

Issue: This UPN claim is not returned in context.AuthenticationTicket.Identity for the external user but for the internal user it is returned. I hope I have explained it right.

**Comment by Tratcher** [comment]
UseOpenIdConnectAuthentication wouldn't be treating them any differently, it has no awareness of the internals of B2C. This is a question you should ask B2C about.

**Comment by santhoshbomma9** [comment]
Sure thanks Chris! 
Could you please help me point in the right direction? Do we have B2C on git hub?

**Comment by Tratcher** [comment]
Try https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=WindowsAzureAD&brandIgnore=True&sort=relevancedesc&searchTerm=
