### ISSUE TITLE
How to configure multiple WS-Federation endpoints with single callback(Wreply)?

### ISSUE THREAD

**Issue by SeminDM** [aspnet/AspNetKatana#294]
I want to configure ADFS endpoints in my asp.net app at runtime with further app restart (for pipeline construction). There is a problem: if I declare **single callback method** for multiple endpoints then I have exception:

_Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match keys:
kid: '[PII is hidden]',
token: '[PII is hidden]'._

If I will **hard-code callbacks for each endpoint** then all works, but this is not my case.

Startup.cs

```
public class Startup
   {
       public void Configuration(IAppBuilder app)
       {
           var federationEndpoints = Service.ListActiveFederationEndpoints();
           if (federationEndpoints.Any())
           {
               app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
               app.UseCookieAuthentication(new CookieAuthenticationOptions());

               var endpointOptions = new List<WsFederationAuthenticationOptions>();
               foreach (var endpoint in federationEndpoints)
               {
                   string metadata = endpoint.ServerUri;
                   string wtrealm = endpoint.RelyingPartyIdentifier;

                   endpointOptions.Add(new WsFederationAuthenticationOptions
                   {
                       Wtrealm = wtrealm,
                       MetadataAddress = metadata,
                       AuthenticationType = endpoint.Name
                   });
               }
               app.Map("/FederationAuth", configuration =>
               {
                   endpointOptions.ForEach(o => app.UseWsFederationAuthentication(o));
               });
           }
           AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.Name;
       }
   }
```
Login and common callback in FederationAuthController

```
        [AllowAnonymous]
        public void ExternalLogin(string endpointName)
        {
            var ctx = Request.GetOwinContext();
            ctx.Authentication.Challenge(
                new AuthenticationProperties { RedirectUri = Url.Action("LoginCallbackAdfs", "FederationAuth") },
                endpointName);
        }

        public ActionResult LoginCallbackAdfs()
        {
            var ctx = System.Web.HttpContext.Current;
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var sessionIdentity = Service.LoginByClaims(claimsIdentity);
            return this.RedirectToAction("Index", "SinglePage");
        }
```
I've read many answers for configuring hard-coded multiple ADFS endpoints in Web.config but is there possibility to configure enpoints at runtime with further app restart?

Thank you!

**Comment by Tratcher** [comment]
Multiple instances on the same callback path is not possible with the current implementation. In the AspNetCore version of this component there's a new SkipUnrecognizedRequests option that supports this, but using unique callback paths is always better.

**Comment by Tratcher** [comment]
Wait, web.config? That's not required. Set WsFederationAuthenticationOptions.CallbackPath to unique values.

**Comment by SeminDM** [comment]
@Tratcher thank you for answer!
If I'll set WsFederationAuthenticationOptions.CallbackPath to unique value then I should create unique callback for each endpoint as well?

**Comment by Tratcher** [comment]
> then I should create unique callback for each endpoint as well?

No, CallbackPath refers to a path handled directly by the auth handler, you don't implement that elsewhere in the app.

**Comment by SeminDM** [comment]
@Tratcher I've set CallbackPath and all ADFS endpoints work correctly. But I'm a little confused about this.
New code:

```
var federationChannels = ChannelService.ListActiveFederationChannels();
                if (federationChannels.Count > 0)
                {
                    app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
                    app.UseCookieAuthentication(new CookieAuthenticationOptions());

                    foreach (var channel in federationChannels)
                    {
                        string metadata = channel.ServerUri;
                        string wtrealm = channel.RelyingPartyIdentifier;

                        app.UseWsFederationAuthentication(new WsFederationAuthenticationOptions
                        {
                            Wtrealm = wtrealm,
                            MetadataAddress = metadata,
                            AuthenticationType = channel.Name,
                            CallbackPath = new PathString($"/Home/LoginByFederationService/channelName={channel.Name}"),
                            Wreply = $"https://myhost:44315/Home/LoginByFederationService/channelName={channel.Name}"
                        });
                    }
}
```

1. Why did you say: "Multiple instances on the same callback path is not possible with the current implementation"? Multiple ADFS instances have the same callback and work correctly now.
2. I set both Wreply and CallbackPath the same value (despite host address). Why is need? what a purpose of CallbackPath? what a difference between Wreply and CallbackPath?
3. Why I need to set RedirectUri for AuthenticationProperties the same value as for WsFederationAuthenticationOptions before the challenge? 
```
 HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = wreply },
                            channel.Name);
```
Thank you for help!

**Comment by Tratcher** [comment]
> 1. Why did you say: "Multiple instances on the same callback path is not possible with the current implementation"? Multiple ADFS instances have the same callback and work correctly now.

You're using channelName to make the paths unique.

> 2. I set both Wreply and CallbackPath the same value (despite host address). Why is need? what a purpose of CallbackPath? what a difference between Wreply and CallbackPath?

That's not needed. CallbackPath is "An optional constrained path on which to process the authentication callback. Computed from Wreply if not provided."
https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.WsFederation/WsFederationAuthenticationOptions.cs#L195

> 3. Why I need to set RedirectUri for AuthenticationProperties the same value as for WsFederationAuthenticationOptions before the challenge?

That's not correct. AuthenticationProperties.RedirectUri gives the value you want the application to be redirected to after all authentication has completed. wreply is only for an intermediate redirect. The default value for RedirectUri is the URL that initiated the challenge. It's common for people to redirect back to their app home page instead. ("/")

**Comment by SeminDM** [comment]
@Tratcher Think I understand you. 
1. Unique Wreply should be set in WsFederationAuthenticationOptions due to middleware registration.
2. Callback path is not required.
3. Single FederationAuthController callback with channelName as parameter will receive redirections for multiple ADFS channels.
4. RedirectUri for Authentication.Challenge is just "<..>/HomePage" in common case

Is it correct?

**Comment by Tratcher** [comment]
Yes.

> Single FederationAuthController callback with channelName as parameter will receive redirections for multiple ADFS channels.

This one is misleading. This is just a pattern to generate unique paths (see 1), cannelName has no meaning to the auth handler.

**Comment by SeminDM** [comment]
Ok, thank you! You really help me!
