### ISSUE TITLE
Expose ClientCertificate in IOwinRequest

### ISSUE THREAD

**Issue by kostrse** [aspnet/AspNetKatana#30]
For convenience. please expose the `ssl.ClientCertificate` as a property in IOwinRequest interface.
This is a common property which used for implementation of ClientCertificateAuthenticationHandler.

**Comment by anurse** [comment]
We don't have plans to add this property. It would be a breaking change to add it as a property, so it would have to be an extension method and at that point the value we can add is fairly minimal.

**Comment by kostrse** [comment]
Then implement the extension method as part of the library, so consumers wouldn't have to implement it in each project.
