### ISSUE TITLE
How to handle unauthorized requests to avoid redirect to an Identity Server?

### ISSUE THREAD

**Issue by laura-rodriguez** [aspnet/AspNetKatana#300]
I'm working with ASP.NET MVC and OpenId Connect. Everything's working fine right except for one issue. When users hit actions decorated with the `Authorize` attribute, if the user is not authenticated or doesn't have a role that matches, the browser is redirected to the identity server login page instead of the custom one.

In ASP.NET Core, this is easy to handle thanks to the `CookieMiddleware` and the `LoginPath` and `AccessDeniedPath` properties available in the `CookieAuthenticationOptions`. However, I'm not sure what's the best way to do this in ASP.NET MVC 4.x.

I found this related issue [#336](https://github.com/aspnet/Security/issues/336) so based in that thread my best option would be overwriting the `OnRedirectToIdentityProvider` method:

```
 private static Task OnRedirectToIdentityProviderAsync(RedirectToIdentityProviderNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> n)
{
...
                    if (n.OwinContext.Authentication.User.Identity.IsAuthenticated)
                    {
                        n.HandleResponse();
                        n.Response.Redirect(Uri.EscapeUriString("/Home/Unauthorized"));
                    }
                    else
                    {
                        n.HandleResponse();
                        n.Response.Redirect(Uri.EscapeUriString("/Account/Login"));
                    }
                   return Task.FromResult(0);
}
```
Is this the recommended approach for this issue? 

Thanks in advance.

**Comment by Tratcher** [comment]
LoginPath also exists here.
https://github.com/aspnet/AspNetKatana/blob/40de8011dab132b020e8d6e89239f4a0bda7d82c/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationOptions.cs#L89-L99

To prevent OIDC from challenging you should set OIDCOptions.AuthenticationMode = Passive.
https://github.com/aspnet/AspNetKatana/blob/40de8011dab132b020e8d6e89239f4a0bda7d82c/src/Microsoft.Owin.Security/AuthenticationOptions.cs#L38-L43

**Comment by laura-rodriguez** [comment]
Thanks for your prompt response @Tratcher ! 
What about `AccessDeniedPath`, do you guys have any plan to add this property as well?

**Comment by Tratcher** [comment]
No, we don't have plans to change the design here. You'll have to hook cookie auth's notifications similar to how you tried to hook OnRedirectToIdentityProviderAsync. I forget if the status code was set to 403 for those scenarios.

**Comment by laura-rodriguez** [comment]
I see, so in the end, overwriting `OnRedirectToIdentityProviderAsync` is necessary. 
Thank you so much for your help @Tratcher.

**Comment by Tratcher** [comment]
No, you should be able to use this event instead:
https://github.com/aspnet/AspNetKatana/blob/40de8011dab132b020e8d6e89239f4a0bda7d82c/src/Microsoft.Owin.Security.Cookies/Provider/CookieAuthenticationProvider.cs#L52

**Comment by laura-rodriguez** [comment]
Ok, I'll take a look at that 👍
