### ISSUE TITLE
Unable to debug Owin Startup class under IIS

### ISSUE THREAD

**Issue by slishnevsky** [aspnet/AspNetKatana#301]
Hello, I tried to google for several days but was unable to find why Startup class doesn't fire in Debug mode under IIS, unable to debug, no breakpoints get hit inside Configuration method. Executing debugging from VS2017, the API runs against IIS. This is a fully functional production code.
Is this some sort of a bug? I can't even tell if the code if firing at all since I am unable to debug it.

Here is a fragment of the code.

```
[assembly: OwinStartup(typeof(Startup))]

namespace Asgl.Core.Owin.Base
{
    public class Startup {
        public void Configuration(IAppBuilder app)
        {       //<-- I put a breakpoint here and it doesnt get hit
            var loggerFactory = new LibLogLoggerFactory();
            app.SetLoggerFactory(loggerFactory);
            // removed the rest for simplicity
        }
}
```

**Comment by Tratcher** [comment]
> the API runs against IIS

Does debugging work with IIS Express?

**Comment by slishnevsky** [comment]
No

**Comment by Tratcher** [comment]
Tried the following and it worked fine:
VS 2017 15.9.14
New project, ASP.NET Web Application (.NET Framework) (4.7.2)
MVC, Change Authentication, Individual User Accounts
Set a break point in Startup.Configure
F5 debug in IIS Express, breakpoints are hit.

Can you reproduce this with a new project? If so please give your steps.

**Comment by slishnevsky** [comment]
New project created with these settings doesn't have any Startup class

**Comment by Tratcher** [comment]
You need to select Individual User Accounts for it to add a Startup class.

**Comment by Peperud** [comment]
I typically have to work with parts of a large app, comprised of different projects etc., so I usually keep a whole proper installation in IIS and drop there the pieces I need to debug. 
I might be doing it the hard way, but this works for me.
If I want to debug OWIN startup stuff in IIS:
1. Have the app installed and configured under IIS. 
2. Add a delay/wait (say 15 sec) at the beginning of startup class class configuration routine.
3. Build and copy the dll & pdb to the mapped IIS location.
4. Add a breakpoint somewhere after the delay/wait statement.
5. Access the app in a browser.
6. Within the delay/wait period attach to the (appropriate) w3wp process. Make sure the "Attach to" code type is managed code

**Comment by anurse** [comment]
Closing this as we haven't heard from the original author and generally close issues with no response after some time. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
