### ISSUE TITLE
OWIN OPenIDConnect is not working with Keycloak, throws an error "PII Data is hidden " 

### ISSUE THREAD

**Issue by umesh-swami07** [aspnet/AspNetKatana#302]
OWIN OPenIDConnect is not working with Keycloak, throws an error "PII Data is hidden " , whenever i am running OIDC plugin to provide single sign on with keycloak using OWIN , it throws error either PII data is hidden or unable to load "keycloak URL/welknown/configuration."  

same configuration is working with ASPNET.security.OpenIDConnect with ASPNET CORE.  but i dont want to migrate my project to ASPNET CORE. 

Please advise.

**Comment by Tratcher** [comment]
Start with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII to get the full error. Also please share the stack trace.

**Comment by umesh-swami07** [comment]
I have set ShowPII= true in cofigure method of startup.cs. 
 here the stack trace 
_[WebException: The remote name could not be resolved: '<<keyclaokurl.com>>']_
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +628
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +64

[HttpRequestException: An error occurred while sending the request.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Net.Http.<FinishSendAsync>d__58.MoveNext() +948
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__8.MoveNext() +362

[IOException: IDX20804: _Unable to retrieve document from: '<<keyclaokurl.com>>/.well-known/openid-configuration'.]_
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__8.MoveNext() +666
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.IdentityModel.Protocols.OpenIdConnect.<GetAsync>d__3.MoveNext() +291
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) +25
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__24.MoveNext() +1129

[InvalidOperationException: IDX20803: Unable to obtain configuration from: _'<<keyclaokurl.com>>/.well-known/openid-configuration'.]_
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__24.MoveNext() +1586
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.OpenIdConnect.<ApplyResponseChallengeAsync>d__c.MoveNext() +575

**Comment by Tratcher** [comment]
That's not an Owin issue, that's a configuration or environment issue. You should be able to put that full url into the browser to verify it's correct.

**Comment by umesh-swami07** [comment]
I figured it out, its about proxy setting, i have enabled default proxy and credentials in web.config then it started working fine. 
  <system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true"> 
    </defaultProxy>
  </system.net>

this has resolved my problem.
