### ISSUE TITLE
set wsFederationMessage.Wreply = properties.RedirectUri when challenging

### ISSUE THREAD

**Issue by nmocruz** [aspnet/AspNetKatana#303]
I was expecting to have something like this on the challange request method

```
AuthenticationProperties properties = signout.Properties;
if (properties != null && !string.IsNullOrEmpty(properties.RedirectUri))
{
        wsFederationMessage.Wreply = properties.RedirectUri;
}
```

does it makes sense or I need to do it the RedirectToIdentityProvider ??

**Comment by Tratcher** [comment]
That's not how we prefer to use wreply and RedirectUri. wreply is intended to point at the middleware so it can handle the request, generate an auth cookie, and then redirect to the final RedirectUri.

https://github.com/aspnet/AspNetKatana/blob/569f1c872e86e57155d7865f4b3d627949cfcba2/src/Microsoft.Owin.Security.WsFederation/WsFederationAuthenticationHandler.cs#L130-L135
https://github.com/aspnet/AspNetKatana/blob/569f1c872e86e57155d7865f4b3d627949cfcba2/src/Microsoft.Owin.Security.WsFederation/WsFederationAuthenticationHandler.cs#L194-L197

**Comment by nmocruz** [comment]
Ok.
Makes sense, I saw it in the apply grant method so I believed that the same

**Comment by Tratcher** [comment]
No, Grant is just for sign-out and we don't intercept the callback url.
