### ISSUE TITLE
AuthenticationHandler called regardless of authorization requirement

### ISSUE THREAD

**Issue by ryno1234** [aspnet/AspNetKatana#307]
This undoubtedly comes down to some ignorance around the inner workings of the authorization, but I'm having an issue with my custom authentication middleware.

I have 2 controller route functions. One is decorated with `[Authorize]` and the other `[AllowAnonymous]`.

No matter which route I hit, my `AuthenticationHandler` has its "Apply" functions called, i.e. `AuthenticationHandler.ApplyResponseChallengeAsync()`, etc. 

At what point is the Authorize attribute taken into account in regards to enacting a _challenge_, _authenticate_ or otherwise? If the route allows anonymous, then I would think we wouldn't need to perform some of these actions.

In my specific case, I'm redirecting the user to a 3rd party authentication page for the challenge. Because this challenge method is called regardless of the route being decorated with the `AuthorizeAttribute` the user is redirected no matter what even on anonymous pages.

Any guidance would be appreciated.

**Comment by Tratcher** [comment]
ApplyResponseChallengeAsync is called at the start of each response so you can check if you need to challenge. See https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin.Security.OAuth/OAuthBearerAuthenticationHandler.cs#L104-L120

**Comment by ryno1234** [comment]
Thank you.
