### ISSUE TITLE
Session time out

### ISSUE THREAD

**Issue by kamranbashir** [aspnet/AspNetKatana#309]
Hi All,
hope you are doing great.
It seems referesh token does not expire on in active session time out.
I am using azure b2c sign in policy v1. i explain the issue below.
1. Let suppose when we sign in 10:00 am time the UTC time was 9:00 am.

2. Framework set session cookie expiry time to 9:15 UTC time.

3.After 15 mins user inactive session on user interaction we redirect to sign in page. (as expected,)

4. But if you try to load index page url its let you sign you in and extend the session cookie expiry time which is totally weird!

if you can suggest any thing in this matter would be highly appreciated. 😊

thanks,
kam

MSFT thread page : https://social.msdn.microsoft.com/Forums/en-US/b1606030-f478-40a6-8df9-80c450056538/azure-b2c-userinactive-need-to-signout-after-15-mins?forum=windowsazurewebsitespreview

**Comment by Tratcher** [comment]
I don't know if it's related, but this is a big problem:
`HttpContext.Current.Session["access_token"] = notification.ProtocolMessage.IdToken;`

HttpContext.Current.Session is a browser session, not an authentication session. You should not store sensitive data in Session, especially not authentication data.

> 3.After 15 mins user inactive session on user interaction we redirect to sign in page. (good)

> 4. But if you try to load index page url its let you sign you in and extend the session cookie expiry time which is totally werid.

Can you privately share a Fiddler trace showing these steps?

Even after the app auth session expires, you're still logged into b2c and could be silently re-authenticated with the app via a few redirects.

**Comment by kamranbashir** [comment]
My code is changing, new code is here

public partial class Startup
    {
        public void ConfigureAuth(IAppBuilder app)
        {
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationMode = AuthenticationMode.Active,
                CookieName = ".id",
                SlidingExpiration = true,
                ExpireTimeSpan = TimeSpan.FromMinutes(15), // this might be overriden,                    
                LogoutPath = PathString.FromUriComponent("/Account/LogOff"),
                LoginPath = PathString.FromUriComponent("/Account/LogIn"),
                CookieHttpOnly = true,
                CookieSecure = CookieSecureOption.Always
            });

            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            int index = 1000;
            foreach (var record in SystemKeys.AppSettings)
            {
                app.MapWhen(
                            context => (HttpContext.Current.Request.Url.BaseURL() == record.Key),
                            config =>
                            {
                                var customer = record.Value;
                                config.UseOpenIdConnectAuthentication(CreateOptionsFromPolicy(index, customer.B2CPasswordResetPolicyId,
                                                        customer.B2CAadInstance, customer.B2CTenant, customer.B2CSignInPolicyId,
                                                        customer.B2CApplicationId, customer.WebUrl
                                    ));

                                config.UseOpenIdConnectAuthentication(CreateOptionsFromPolicy(index, customer.B2CSignInPolicyId,
                                                        customer.B2CAadInstance, customer.B2CTenant, customer.B2CSignInPolicyId,
                                                        customer.B2CApplicationId, customer.WebUrl
                                    ));
                            }
                        );
                index++;
            }
        }

        // Used for avoiding yellow-screen-of-death TODO
        private Task AuthenticationFailed(AuthenticationFailedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            notification.HandleResponse();

            if (notification.ProtocolMessage.ErrorDescription != null && notification.ProtocolMessage.ErrorDescription.Contains("AADB2C90118"))
            {
                // If the user clicked the reset password link, redirect to the reset password route
                notification.Response.Redirect(notification.Options.RedirectUri + "/Account/ResetPassword");
            }
            else if (notification.Exception.Message == "access_denied")
            {
                // If the user canceled the sign in, redirect back to the home page
                notification.Response.Redirect("/Account/Unauthorised");
            }
            else
            {
                notification.Response.Redirect("/Errors/Index?message=" + notification.Exception.Message);
            }

            return Task.FromResult(0);
        }

        private Task OnRedirectToIdentityProvider(RedirectToIdentityProviderNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
            if (notification.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
            {
                var idToken = notification.OwinContext.Authentication.User.FindFirst("identity_token");
                if (idToken != null)
                {
                    notification.ProtocolMessage.IdTokenHint = idToken?.Value;
                }                
            }

            var policy = notification.OwinContext.Get<string>("Policy");
            var key = notification.Request.Scheme + "://" + notification.Request.Host.Value + notification.Request.PathBase + "/";

            if (SystemKeys.AppSettings.TryGetValue(key, out var value) &&
                !string.IsNullOrEmpty(policy) && !policy.Equals(value.B2CSignInPolicyId))
            {
                notification.ProtocolMessage.Scope = OpenIdConnectScopes.OpenId;
                notification.ProtocolMessage.ResponseType = OpenIdConnectResponseTypes.IdToken;
                notification.ProtocolMessage.IssuerAddress = notification.ProtocolMessage.IssuerAddress.ToLower().Replace(value.B2CSignInPolicyId.ToLower(), policy.ToLower());
            }

            return Task.FromResult(0);
        }

        private Task OnSecurityTokenValidated(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> notification)
        {
          

            HttpContext.Current.Session["access_token"] = notification.ProtocolMessage.IdToken;
            notification.AuthenticationTicket.Properties.IssuedUtc = DateTime.UtcNow;
            notification.AuthenticationTicket.Properties.ExpiresUtc = DateTime.UtcNow.AddMinutes(15);
            notification.AuthenticationTicket.Properties.IsPersistent = true;          

            return Task.FromResult(0);
        }

        private OpenIdConnectAuthenticationOptions CreateOptionsFromPolicy(int index, string b2cPolicyName,
                                                string b2cInstance, string b2cTenant, string b2cSignInPolicy,
                                                string b2cApplicationId, string b2cRedirectUrl)
        {

            return new OpenIdConnectAuthenticationOptions
            {

                // For each policy, give OWIN the policy-specific metadata address, and
                // set the authentication type to the id of the policy

                MetadataAddress = string.Format(b2cInstance, b2cTenant, b2cSignInPolicy),
                AuthenticationType = string.Format("{0}_{1}", b2cPolicyName, index),
                AuthenticationMode = AuthenticationMode.Passive,
                // These are standard OpenID Connect parameters, with values pulled from web.config
                ClientId = b2cApplicationId,
                RedirectUri = b2cRedirectUrl,
                PostLogoutRedirectUri = b2cRedirectUrl,
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    RedirectToIdentityProvider = OnRedirectToIdentityProvider,
                    AuthenticationFailed = AuthenticationFailed,
                    SecurityTokenValidated = OnSecurityTokenValidated,

                },
                Scope = "openid",
                ResponseType = "id_token",

                //// This piece is optional - it is used for displaying the user's name in the navigation bar.
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    //SaveSigninToken = true
                },
                UseTokenLifetime = false,                
            };
        }

    }

**Comment by Tratcher** [comment]
My comments above still apply: https://github.com/aspnet/AspNetKatana/issues/309#issuecomment-531825622

**Comment by kamranbashir** [comment]
thanks for reply.
waiting for vsts build, above mentioned code in deplyment process.
I will send you traces  :) thanks.

**Comment by kamranbashir** [comment]
since i made code like below mentioned cannot default microsoft sign in page!
 app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationMode = AuthenticationMode.Active,
LoginPath = PathString.FromUriComponent("/Account/LogIn"),...
}

return new OpenIdConnectAuthenticationOptions
            {
                AuthenticationMode = AuthenticationMode.Passive
}

AccountController : Controller....

public void LogIn()
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge();
                return;
            }

            Response.Redirect("/"); // TODO: Maybe this should redirect me back to original route MyModel/Index in some way
        }

**Comment by Tratcher** [comment]
When calling Challenge, pass in the authentication scheme name for OpenIdConnect. The default is OpenIdConnectAuthenticationDefaults.AuthenticationType.

**Comment by kamranbashir** [comment]
fixed that, but still getting 'ERR_TOO_MANY_REDIRECTS'
public void LogIn(string ReturnUrl = "/")
        {
            // Send an OpenID Connect sign-in request.
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = ReturnUrl },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);

            }
        }

**Comment by Tratcher** [comment]
Can you share a Fiddler trace file showing the issue?

**Comment by kamranbashir** [comment]
hi Tratcher,
how can i share fiddler trace?

**Comment by Tratcher** [comment]
You can zip or rename it.
You can also send it to the e-mail in my github profile.

**Comment by kamranbashir** [comment]
i sent you.
thanks

**Comment by kamranbashir** [comment]
current problem is that i am unable to bring microsoft login page.

cookieauth.AuthenticationMode =active
openidconnect.AuthenticationMode =passive

if i change to 

cookieauth.AuthenticationMode =passive
openidconnect.AuthenticationMode =active

then i get microsoft login page.
but issue i have auto renewal of cookie

**Comment by Tratcher** [comment]
Interesting, I haven't seen complaints around passive affecting cookie renewal.
And setting them both to active causes a conflict, right?

**Comment by kamranbashir** [comment]
i havent tired that

**Comment by kamranbashir** [comment]
just going to try

**Comment by kamranbashir** [comment]
"but issue i have auto renewal of cookie" 
i meant cookie get auto renwed even after timeout by going to index page, like you said it seems b2c never signed out, it stayed signed in.

**Comment by Tratcher** [comment]
That's not a local app configuration issue, that's a feature of single-sign-on.

**Comment by kamranbashir** [comment]
okay, i emailed you couple of files of the code. 
i am goign to test both 'setting them both to active' case.
deployment take 20 mins... ahh

**Comment by kamranbashir** [comment]
when we set bot active
cookieauth.AuthenticationMode =active
openidconnect.AuthenticationMode =active
so far able to redirect and login to into micrsoft page. lets see after 15 mins logout what happens!

**Comment by kamranbashir** [comment]
result is same as
cookieauth.AuthenticationMode =pasive
openidconnect.AuthenticationMode =active
