### ISSUE TITLE
Sign in with Apple external provider

### ISSUE THREAD

**Issue by tmezzena** [aspnet/AspNetKatana#310]
Is there an intention to implement "Sign in with Apple" or an "Apple" external provider on this project?

Reference:
https://developer.apple.com/documentation/signinwithapplerestapi

Thanks,

**Comment by Tratcher** [comment]
No. One was recently created for AspNetCore contrib that you may be able to adapt:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/343/files
