### ISSUE TITLE
Reversal of WindowsIdentity.Impersonate does not always work

### ISSUE THREAD

**Issue by avivanoff** [aspnet/AspNetKatana#312]
Originally, I posted the issue [https://github.com/aspnet/AspNetWebStack/issues/260](https://github.com/aspnet/AspNetWebStack/issues/260) in [AspNetWebStack](https://github.com/aspnet/AspNetWebStack) repository, but I am almost sure the problem is in  `OwinHttpListener`.

**Comment by Tratcher** [comment]
Closing this as it looks like you've narrowed it down to a runtime issue:
https://developercommunity.visualstudio.com/content/problem/753482/windowsidentityimpersonate-in-some-async-schenario.html
