### ISSUE TITLE
When will the version 4.1 be released?

### ISSUE THREAD

**Issue by HaroldliGC** [aspnet/AspNetKatana#318]
I want to use "Microsoft.Owin.Security.OpenIdConnect", but I find the 4.0.1 version not support openid connect code flow. So, when will the version 4.1 be released?

**Comment by Tratcher** [comment]
Soon, we're waiting for a few .NET patches we depend on to be released first. For now you can use the packages from the myget feeds. https://github.com/aspnet/AspNetKatana#nightly-build-feeds

**Comment by HaroldliGC** [comment]
@Tratcher thank you very much

**Comment by JaredShaver** [comment]
@Tratcher are the .NET Patches going to be in a reliability update as optional updates or part of a security update?

**Comment by Tratcher** [comment]
We're still confirming that. We'll let you know.

**Comment by Tratcher** [comment]
The .NET patches we need have been delayed for an unknown amount of time. We'll follow up when we have a confirmed publish date.

**Comment by dherr** [comment]
We're also anxiously waiting for the code-flow support in this update, for use with Apple Sign-in.  Is there a rough ETA estimate (weeks, months, longer)?

**Comment by babubhare** [comment]
Please let us know the ETA time for the release. For the code flow support. We are also waiting for it.

**Comment by Tratcher** [comment]
> The .NET patches we need have been delayed for an unknown amount of time. We'll follow up when we have a confirmed publish date.

**Comment by babubhare** [comment]
Thanks for the comments. 
I used the dev copy of Microsoft.Owin.Security.OpenIdConnect component only. 
Setting the 
SameSite = SameSiteMode.None,

The Code flow works fine, Does it make sense to have a copy of Microsoft.Owin.Security.OpenIdConnect library for Code Flow; instead of waiting for 4.1.0.0 version of Owin.

**Comment by Tratcher** [comment]
I'd suggest continuing to use the dev package. It has the same code we plan to ship, only the versions are different.

**Comment by Tratcher** [comment]
For reference, the patches we're waiting for are the ones that update SameSite support in System.Web. You'll need these if you're going to use 4.1 with the SystemWebCookieManager. There are 4 variations of the patch based on Windows and .NET Framework versions. Two of these patches are now available.
Win7,2008,2008R2 for .NET 4.7.2 - https://support.microsoft.com/en-us/help/4524421/kb4524421
Win7,2008R2 for .NET 4.8 - https://support.microsoft.com/en-us/help/4531182/kb4531182
Note to use Microsoft.Owin with these patches does not require retargeting your application to those .NET Framework versions, they only need to be installed on the machine.

Now that these patches are available we'll start the release process for Microsoft.Owin 4.1.0. We'll let you know when the other patches are available later.

**Comment by babubhare** [comment]
Thank you very much for providing the information.!!!

**Comment by JaredShaver** [comment]
The original announcement stated the SameSite fix is only for .NET 4.7.2 and 4.8 https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

> SystemWebCookieManager will need the .NET 4.7.2 or later SameSite patch installed to work correctly.

But the KB https://support.microsoft.com/en-us/help/4524421/kb4524421 and blog post https://devblogs.microsoft.com/dotnet/net-framework-november-2019-preview-of-quality-rollup/ do not have any qualifying details saying the cookie fix only applies to .NET 4.7.2 and newer.

Did the cookie change get backported all the way to 4.6 or is the KB and blog post missing this information?

**Comment by Tratcher** [comment]
> Did the cookie change get backported all the way to 4.6 or is the KB and blog post missing this information?

No, the SameSite APIs only exist in 4.7.2 and later, it's not possible to patch them into earlier versions. That patch also included other fixes for 4.6.

**Comment by Tratcher** [comment]
The Microsoft.Owin 4.1.0 packages are now published to nuget.org. It may take a few hours for the indexes to update.
https://www.nuget.org/packages/Microsoft.Owin/4.1.0

I'll leave this open until the remaining .NET patches are available.

**Comment by Tratcher** [comment]
New docs and the remaining patches are now available.
https://docs.microsoft.com/en-us/aspnet/samesite/owin-samesite
https://docs.microsoft.com/en-us/aspnet/samesite/kbs-samesite
