### ISSUE TITLE
Use License Expression and embedded package Icons

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetKatana#319]
The `licenseUrl` and `iconUrl` elements in the nuspec are deprecated.

We should move to the [`<license>` element](https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) and [embedded package icons](https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon) before the next release.

**Comment by KalleOlaviNiemitalo** [comment]
The v4.1.0 NuGet packages mention v4.0.1 in `<licenseUrl>https://raw.githubusercontent.com/aspnet/AspNetKatana/v4.0.1/LICENSE.txt</licenseUrl>`. Moving to `<license>` will also prevent this inconsistency from recurring.

**Comment by anurse** [comment]
Yep, that's definitely part of the justification for switching!

**Comment by Tratcher** [comment]
I don't see any usages of iconUrl. I'll fix licenseUrl.
