### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by miksh7** [aspnet/AspNetKatana#321]
Please add and support changelog.md or add info into readme.md where to find the release changelog.

**Comment by Tratcher** [comment]
Is there something you're looking for beyond the list of resolved issues?
https://github.com/aspnet/AspNetKatana/issues?q=is%3Aissue+milestone%3A4.1.0+is%3Aclosed

**Comment by miksh7** [comment]
Yes, thank you. At least, it would be nice to have this info or this link in the release info, e.g. as SignalR team does it.

**Comment by Tratcher** [comment]
This is standard github issue management. We do post the highlights at https://github.com/aspnet/AspNetKatana/wiki/Roadmap#410-release-november-2019.

**Comment by miksh7** [comment]
"Standard" doesn't always mean convenient. Honestly, I didn't figure out that Roadmap contains the release history highlights and nothing to be done in future. 
I leave it to you but as a user I need quickly find "what's new" information in each release.

**Comment by Tratcher** [comment]
We're standardizing on using "releases" for this information: https://github.com/aspnet/AspNetKatana/releases
