### ISSUE TITLE
"Sign in with Apple": The user's name is not used by the Microsoft.Owin.Security.OpenIdConnect package

### ISSUE THREAD

**Issue by bedane** [aspnet/AspNetKatana#323]
On the first time a user signs in with Apple onto our app, Apple provides the email (or a generated one) and the name of the user. However the Identity created by the OpenIdConnect middleware never exposes the user's name(neither as a claim nor in the ExternalLoginInfo from the Microsoft.AspNet.Identity.Owin package our app uses too). 
Is this an issue in the Microsoft.Owin.Security.OpenIdConnect package?

**Comment by Tratcher** [comment]
Not that I know of, but I haven't tried Apple yet. The only similar [implementation](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs) of an Apple login provider I've seen is for AspNetCore, and it doesn't seem to do anything special except request the [name and email scopes](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/53d23133c07b311c088dd05ae8cd8d76ce18a164/src/AspNet.Security.OAuth.Apple/AppleAuthenticationOptions.cs#L31-L32).

How have you configured it?

**Comment by CameronWills** [comment]
So the very first time a Apple user allows/permits access to your application (the same time the user can select to make their email address private), along with the `code` and `id_token` apple also posts a `user` JSON that contains the user's first name, last name and email address. So you probably want to hook into the `OpenIdConnectAuthenticationNotifications.SecurityTokenValidated` event to capture these values and insert them into the ClaimsIdentity. Something like:

```
        public static Task OnTokenValidatedApple(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> context)
        {
            if (context.ProtocolMessage.Parameters.TryGetValue("user", out string userJson) && !string.IsNullOrEmpty(userJson))
            {
                var user = JsonConvert.DeserializeObject<AppleUser>(userJson);
                var identity = context.AuthenticationTicket.Identity;

                if (!string.IsNullOrWhiteSpace(user.Name.FirstName))
                    identity.AddClaim(new Claim(ClaimTypes.GivenName, user.Name.FirstName));

                if (!string.IsNullOrWhiteSpace(user.Name.LastName))
                    identity.AddClaim(new Claim(ClaimTypes.Surname, user.Name.LastName));
            }

            return Task.CompletedTask;
        }
```

The equivalent of this logic in the AspNetCore implementation is here:
https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/8e4c19008f518f3730bab90a980e01347ba6f3d3/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L167
