### ISSUE TITLE
openidconnect 4.1 support authorization code flow, should it requests id_token, access_token, and set user's claims?

### ISSUE THREAD

**Issue by hooblix** [aspnet/AspNetKatana#329]

**Comment by Tratcher** [comment]
Please show how you configured it.

**Comment by hooblix** [comment]
Looking into openidconnect source core, I figure that if I don't do anything with AuthorizationCodeReceived and set RedeemCode = true. openidconnect will request id_token, access_token, and set user's claims. But claims does not contain id_token and access_token. The logout with Okta fail, because it expects id_token for logout. How to retrieve id_token and access_token if application needs to use it to call other OAuth protected API?

        public void ConfigureAuth(IAppBuilder app)
        {                   
           app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions());
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = _clientId,
                ClientSecret = _clientSecret,
                Authority = _authority,
                RedirectUri = _redirectUri,
                //ResponseType = OpenIdConnectResponseType.CodeIdToken,
                ResponseType = OpenIdConnectResponseType.Code,
                RedeemCode = true,
                Scope = OpenIdConnectScope.OpenIdProfile,
                PostLogoutRedirectUri = postLogoutRedirectUri,
                TokenValidationParameters = new TokenValidationParameters { NameClaimType = "name" },
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    RedirectToIdentityProvider = n =>
                    {
                        // If signing out, add the id_token_hint
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
                        {
                            var idTokenClaim = n.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idTokenClaim != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenClaim.Value;
                            }
                        }
                        return Task.CompletedTask;
                    }
                },
            });
        }

**Comment by Tratcher** [comment]
See the SaveTokens option.

**Comment by hooblix** [comment]
I tried this option too, tokens didn't show in user's identity claims.

**Comment by hooblix** [comment]
find a solution: add tokens to claim by processing SecurityTokenValidated notification

    public void ConfigureAuth(IAppBuilder app)
    {                   
       app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
        app.UseCookieAuthentication(new CookieAuthenticationOptions());
        app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
        {
            ClientId = _clientId,
            ClientSecret = _clientSecret,
            Authority = _authority,
            RedirectUri = _redirectUri,
            //ResponseType = OpenIdConnectResponseType.CodeIdToken,
            ResponseType = OpenIdConnectResponseType.Code,
            RedeemCode = true,
            Scope = OpenIdConnectScope.OpenIdProfile,
            PostLogoutRedirectUri = postLogoutRedirectUri,
            TokenValidationParameters = new TokenValidationParameters { NameClaimType = "name" },
            Notifications = new OpenIdConnectAuthenticationNotifications
            {
                SecurityTokenValidated = n =>
                {
                    n.AuthenticationTicket.Identity.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                    n.AuthenticationTicket.Identity.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));
                    return Task.CompletedTask;
                },
                RedirectToIdentityProvider = n =>
                {
                    // If signing out, add the id_token_hint
                    if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
                    {
                        var idTokenClaim = n.OwinContext.Authentication.User.FindFirst("id_token");
                        if (idTokenClaim != null)
                        {
                            n.ProtocolMessage.IdTokenHint = idTokenClaim.Value;
                        }
                    }
                    return Task.CompletedTask;
                }
            },
        });
    }

**Comment by Tratcher** [comment]
Ah, that's because they're not saved as claims, they're saved in the AuthProperties collection that's returned with the ClaimsPrincipal:
https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L725

Calling AuthenticateAsync will get you back the auth properties.
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin/Security/AuthenticationManager.cs#L154

**Comment by hooblix** [comment]
Not able to get tokens from AuthenticateAsync call. OpenIdConnect AutherticationType returns null. I use Cookies AuthenticationType in the following code, but not able to get tokens.

RedirectToIdentityProvider = async n =>
{
    // If signing out, add the id_token_hint
    if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
    {
        //string authenticationType = OpenIdConnectAuthenticationDefaults.AuthenticationType;
        string authenticationType = CookieAuthenticationDefaults.AuthenticationType;
        var task = await n.OwinContext.Authentication.AuthenticateAsync(authenticationType);
        if (task != null)
        {
            n.ProtocolMessage.IdTokenHint = task.Identity.FindFirst("id_token").Value;
        }
    }
    return; 
}

**Comment by Tratcher** [comment]
Because they're not claims. Look in `task.Properties`
https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L732-L735
