### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by secovel** [aspnet/AspNetKatana#33]
Is this the official repository for Microsoft.Owin.Host.HttpListener? 
https://www.nuget.org/packages/Microsoft.Owin.Host.HttpListener/

Can you clarify the license?  The NuGet repository shows this license file:  http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm

The Git repository shows an Apache license:  http://www.apache.org/licenses/LICENSE-2.0

As an aside, NuGet package also points to an old repository on CodePlex, that should be fixed too.  I'm not 100% comfortable that the Git site IS the correct repository.

**Comment by Tratcher** [comment]
Yes, this is the new official home for Microsoft.Owin packages.

Yes, the sources and the pre-built packages intentionally have different licences. You're allowed to do much more with the raw source, as opposed to the packages/dlls are built and signed by MS. Right @Eilon? 

Note we just did a new release (https://www.nuget.org/packages/Microsoft.Owin.Host.HttpListener/3.1.0-rc1) so the links should be updated soon.

**Comment by Eilon** [comment]
Right, the source code in this repo has a particular license, and the final NuGet package and DLLs on NuGet.org have a different license.
