### ISSUE TITLE
Unable to Login via facebook using Microsoft.owin

### ISSUE THREAD

**Issue by LumaiRashad** [aspnet/AspNetKatana#330]
It works when I use localhost but on the live site (https://www.elbeit.me) it gives me /Account/ExternalLoginCallback?error=access_denied
I am using Microsoft.owin.security.facebook v4.1.0 and yet it works 1 time successfully but several times the AuthenticationManager.GetExternalLoginInfoAsync(); return null object.

Fiddler trace of the flow:
![image](https://user-images.githubusercontent.com/15093585/72721030-d2b42f80-3b83-11ea-946b-1f5bcd37db65.png)
(302)
https://www.facebook.com/login/reauth.php?app_id=257643325150752&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.8%2Fdialog%2Foauth%3Fresponse_type%3Dcode%26client_id%3D257643325150752%26redirect_uri%3Dhttp%253A%252F%252Fwww.elbeit.me%252Fsignin-facebook%26scope%3Dpublic_profile%252Cemail%252Cemail%26state%3DsqiY1NzCQWkBL9NTlWwBTeWwIB6fvWRXkmtCsXuvEC9Sz_qXG42abGJhHgaQD4Jbvo1zBZ1V2P3yXpxVURNkM5dqsbEOoYBWg7vvJsXJ2aB1WhcvToR7AdBPkgU37ETotXEKsp-vqYIQYXW5N_E-GB_XTivZIrZ0_CJeMsd6CqYGFdeyqq2hBxRSHCnx9Fupt3VztG9uCG7Q3-_biNwp6hM6ZKGJO7pkjaOXMXmAqvw%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3D1bb5c8c6-f962-498c-adac-170d946857da%26cbt%3D1579516888854&cancel_url=https%3A%2F%2Fwww.elbeit.me%2Fsignin-facebook%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3DsqiY1NzCQWkBL9NTlWwBTeWwIB6fvWRXkmtCsXuvEC9Sz_qXG42abGJhHgaQD4Jbvo1zBZ1V2P3yXpxVURNkM5dqsbEOoYBWg7vvJsXJ2aB1WhcvToR7AdBPkgU37ETotXEKsp-vqYIQYXW5N_E-GB_XTivZIrZ0_CJeMsd6CqYGFdeyqq2hBxRSHCnx9Fupt3VztG9uCG7Q3-_biNwp6hM6ZKGJO7pkjaOXMXmAqvw%23_%3D_&display=page&locale=en_GB&pl_dbl=0

(302)
https://www.facebook.com/v2.8/dialog/oauth?response_type=code&client_id=257643325150752&redirect_uri=http%3A%2F%2Fwww.elbeit.me%2Fsignin-facebook&scope=public_profile%2Cemail%2Cemail&state=sqiY1NzCQWkBL9NTlWwBTeWwIB6fvWRXkmtCsXuvEC9Sz_qXG42abGJhHgaQD4Jbvo1zBZ1V2P3yXpxVURNkM5dqsbEOoYBWg7vvJsXJ2aB1WhcvToR7AdBPkgU37ETotXEKsp-vqYIQYXW5N_E-GB_XTivZIrZ0_CJeMsd6CqYGFdeyqq2hBxRSHCnx9Fupt3VztG9uCG7Q3-_biNwp6hM6ZKGJO7pkjaOXMXmAqvw&ret=login&fbapp_pres=0&logger_id=1bb5c8c6-f962-498c-adac-170d946857da&cbt=1579516888854&ext=1579520878&hash=AebBW5xKpWglyB-2

(302)
https://www.elbeit.me/signin-facebook?code=AQDVcLs6MrDPaTjvbkw_HaVVMR2CW8TXZCeynXSHzf5EpFxpEMXvFUlbEE61vK4UNC9RS8ej9IPRd-sL-WIjNS0HS5rM_1M7U8CZiEhDdLGXFOCd9wCiW8BdAhee2Fyx1tFsbcX8elx4eQ9BF2ghtyHYW2aAGTh2aT-fVENAKxoWAdOLQo53tZ7KTonYwUjth2_biLxZlxMDCRO-NIQcx5OzqFU99LPAVOMmDd27CtQq9nErAtZEELufVQGI7cXTaj1kKZIyXJtF2qQHrio6ocEcshPBGSjEOSZ3gxlPM6v0MY-T8jx9WfubPXKjQ0y9YawxvzHyG0HKYD_U1srpKS7T&state=sqiY1NzCQWkBL9NTlWwBTeWwIB6fvWRXkmtCsXuvEC9Sz_qXG42abGJhHgaQD4Jbvo1zBZ1V2P3yXpxVURNkM5dqsbEOoYBWg7vvJsXJ2aB1WhcvToR7AdBPkgU37ETotXEKsp-vqYIQYXW5N_E-GB_XTivZIrZ0_CJeMsd6CqYGFdeyqq2hBxRSHCnx9Fupt3VztG9uCG7Q3-_biNwp6hM6ZKGJO7pkjaOXMXmAqvw

(302)
https://www.elbeit.me/Account/ExternalLoginCallback?error=access_denied

(200)
https://www.elbeit.me/?ExternalLoginCallback=loginInfoNull

Code Snippets:
![image](https://user-images.githubusercontent.com/15093585/72719890-6f290280-3b81-11ea-89df-2857961e52de.png)

![image](https://user-images.githubusercontent.com/15093585/72721117-02fbce00-3b84-11ea-8467-e458c245fc93.png)

**Comment by Tratcher** [comment]
`error_reason=user_denied` Looks like the user hit cancel on the facebook permissions page?

Side note: When sharing code please do so as text, not screen shots. And for Fiddler, sharing the saz file is more useful.

**Comment by LumaiRashad** [comment]
No cancellation happened, When I try login it redirects me to facebook login then after logging with fb, it redirects me to my website throw ExternalLoginCallback action, check calls GetExternalLoginInfoAsync() returning null object, the weird thing that it works sometimes and other times it does not work.

Startup.Auth.cs:
`            var facebookOptions = new FacebookAuthenticationOptions()
            {
                AppId = ConfigHelper.GetConfigSettingValue("FBAppID"),
                AppSecret = ConfigHelper.GetConfigSettingValue("FBAppSecret"),
                UserInformationEndpoint = "https://graph.facebook.com/v3.2/me?fields=id,name,email,first_name,last_name",
                AuthorizationEndpoint = "https://www.facebook.com/v3.2/dialog/oauth",
                Scope = { "email" }
            };
            app.UseFacebookAuthentication(facebookOptions);`

` [AllowAnonymous]
        public async Task<ActionResult> ExternalLoginCallback(string returnUrl)
        {
            var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                return RedirectToAction("Index", "Home", new { ExternalLoginCallback = "loginInfoNull" });
            }
}`

Fiddler saz file: [bit.ly/2GdDfE9](url)

**Comment by Tratcher** [comment]
Interesting, it comes back to /signin-facebook with a code, but after that you end up here:
https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs#L260

Probably due to an exception when exchanging the code.
https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs#L156-L157

You can confirm by enabling [logs](https://github.com/aspnet/AspNetKatana/wiki/Debugging) or attaching a debugger and checking for first chance exceptions.

**Comment by LumaiRashad** [comment]
I used Owin logger, added the below lines in my config file, and nothing being logged
```c#
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="Microsoft.Owin">
        <listeners>
          <add name="KatanaListener"/>
        </listeners>
      </source>
    </sources>
    <sharedListeners>
      <add
       name="KatanaListener"
       type="System.Diagnostics.TextWriterTraceListener"
        initializeData="Logs/Katana.trace.log"
       traceOutputOptions = "ProcessId, DateTime"/>
    </sharedListeners>
    <switches>
      <add name="Microsoft.Owin" value="Verbose" />
    </switches>
  </system.diagnostics>
```
What am I missing?

**Comment by Tratcher** [comment]
Make sure `initializeData="Logs/Katana.trace.log"` refers to a location that your app pool id has write permissions to. You can also make it an absolute path to make sure it's the right place.

**Comment by LumaiRashad** [comment]
I did giving it full permissions, yet when I try owin logger in any place in my app is logs, so I made sure that this path is correct, but when I wait for the logger mechanism inside security.facebook, nothing is being logged.
side note, login via facebook works only one just after I recycle the website, then it returns to keep failing.

**Comment by Tratcher** [comment]
Ok, how about attaching a debugger instead?

**Comment by LumaiRashad** [comment]
Okay, i changed newtonsoft version 10.0.1 then the logger worked fine,
We are hosting our website on 2 servers,
In the first server we got the following:
```
 Microsoft.Owin.Security.Facebook.FacebookAuthenticationMiddleware Error: 0 : Authentication failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Owin.Security.Facebook.FacebookAuthenticationHandler.<AuthenticateCoreAsync>d__4.MoveNext()
    ProcessId=5436
    DateTime=2020-01-21T16:48:20.0694489Z
Microsoft.Owin.Security.Facebook.FacebookAuthenticationMiddleware Error: 0 : Authentication failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Owin.Security.Facebook.FacebookAuthenticationHandler.<AuthenticateCoreAsync>d__4.MoveNext()
    ProcessId=5436
    DateTime=2020-01-21T16:48:26.2411353Z

```
and on the second one we got:
```
Microsoft.Owin.Security.Facebook.FacebookAuthenticationMiddleware Warning: 0 : .AspNet.Correlation.Facebook cookie not found.
    ProcessId=2320
    DateTime=2020-01-21T16:55:02.2536361Z
Microsoft.Owin.Security.Facebook.FacebookAuthenticationMiddleware Warning: 0 : .AspNet.Correlation.Facebook cookie not found.
    ProcessId=2320
    DateTime=2020-01-21T16:55:41.9116726Z

```

**Comment by Tratcher** [comment]
The first one implies there's something wrong with your facebook credentials such as your AppSecret. If you intercept that backchannel request via Wireshark, Fiddler, or an in-memory DelegatingHandler you should be able to get more information.

Can you share a Fiddler trace for the second server?

**Comment by LumaiRashad** [comment]
Both AppId & AppSecret are right, how can I know the credential problem then from Fiddler?

**Comment by Tratcher** [comment]
Check that the backchannel request to Facebook is well formed and see if they provided any details in the 500 response.

**Comment by im-adrianlewis** [comment]
FYI: This issue seems to be a Facebook issue. Facebook endpoint is supposed to return a JSON response for the token handler and instead returns the auth tokens in URL format (ampersand separated) and this breaks the JSON deserialization (obviously)
See more below;
https://developers.facebook.com/support/bugs/1762499877225601/

Not that FB think they have a problem...

**Comment by Tratcher** [comment]
I've just tested the Microsoft.Owin and ASP.NET Core Facebook auth handlers and am not seeing any issues. Maybe they fixed it?

**Comment by im-adrianlewis** [comment]
Just tested in our release environment and it's still broken...

Our implementation (IdentityServer3 based .NET Framework 4.7.2 solution using the latest OWIN components) still fails. I even pulled the source for the OWIN Facebook library into our solution so I could see what was going on in the debugger.
The issue manifests inside FacebookAuthenticationHandler.cs at line 91 - the call to the Facebook token handler is assumed to return JSON and it seems to be returning something else which causes an exception at line 91 where the response body is parsed by JObject.Parse.
The exception is bubbled and is eventually converted into an "access_denied" error and shown in our login form.
I have tried changing the SDK version for the graph API but it makes no difference. I even tried adding an accept header to the request to force the API to return JSON but it is ignored.

**Comment by Tratcher** [comment]
Ok, you're going to have to take that to Facebook's support team then. Since you have the debugger working you should be able to see the `text` field on line 90 and what format it's in. [3 years ago](https://github.com/aspnet/AspNetKatana/commit/b32efb31da8834a6877a354c7d49ef6190873f0a) Facebook always returned a form formatted response, maybe someone started up an old server 😁.

**Comment by LumaiRashad** [comment]
In my case I don't think it's a facebook's issue, as I pulled the Microsoft.Owin.Security.Facebook then placed logger to check for the returned [https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs#L90](text) value at line 91 and got the following: `2/4/2020 3:38:03.333 Owin Facebook Log: {"access_token":"EAADqU0Lf1iABAHIK64k1SUDYmykG6MHDk7Ax0rr7gC8cXoRyxcNSZAD2M9zZCRx7ZBTsILNXsOs6N32SWsBp0NTRJ2N2ZCFwD7yKbJpy9dNox5ZALuclPhJZA2j7dD63wqwZCTBURSjifE8AFm18Eq9ePb9evfGEFTj7vsfSj9KzQZDZD","token_type":"bearer","expires_in":5178382}` 
also logged text value at [https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs#L114](text) at line 114
and got the right data:
`2/4/2020 3:38:03.443 Owin Facebook Log User data: {"name":"Lumai H. Rashad","email":"lumai_rashad\u0040outlook.com","first_name":"Lumai","last_name":"Rashad","id":"2554325621247460"}`.

Yet, when I return to account.cs and call AuthenticationManager.GetExternalLoginInfoAsync(); the returned object is null.

**Comment by Tratcher** [comment]
@LumaiRashad that looks completely different from the 500 errors you were getting last. https://github.com/aspnet/AspNetKatana/issues/330#issuecomment-576793336

Since you have the debugger working, does the rest of AuthenticateCoreAsync execute normally? What does the browser or Fiddler show for the response headers from that /sigin-facebook request? Is the External cookie there?

Another user reported issues (https://github.com/aspnet/AspNetKatana/issues/331) with their external cookie after the December .NET patch  where they had to override UseExternalSignInCookie so they could add the SystemWebCookieManager.

**Comment by LumaiRashad** [comment]
The rest of AuthenticateCoreAsync is completed fine with no exceptions, there is no 500 errors popping up any more, in fiddler trace, whenever it fails there is no .ASPNet.ExternalCookie being set or created.
You can check Fiddler's trace when is succeeds & fails below:
Successful Login trace: http://bit.ly/2UthwRk
Failed Login trace: http://bit.ly/2GRnD9X

**Comment by LumaiRashad** [comment]
I applied the following in the Startup.Auth.cs
```c#
using System;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.Google;
using Owin;
using RealStateIdentity.Models;
using Microsoft.Owin.Security.Facebook;
using LOLHelpers;
using Microsoft.Owin.Security;

namespace RealStateIdentity
{
    public partial class Startup
    {
        private const string CookiePrefix = ".AspNet.";
        // For more information on configuring authentication, please visit https://go.microsoft.com/fwlink/?LinkId=301864
        public void ConfigureAuth(IAppBuilder app)
        {
            // Configure the db context, user manager and signin manager to use a single instance per request
            app.CreatePerOwinContext(ApplicationDbContext.Create);
            app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);
            app.CreatePerOwinContext<ApplicationSignInManager>(ApplicationSignInManager.Create);

            // Enable the application to use a cookie to store information for the signed in user
            // and to use a cookie to temporarily store information about a user logging in with a third party login provider
            // Configure the sign in cookie
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/Login"),
                Provider = new CookieAuthenticationProvider
                {
                    // Enables the application to validate the security stamp when the user logs in.
                    // This is a security feature which is used when you change a password or add an external login to your account.  
                    OnValidateIdentity = SecurityStampValidator.OnValidateIdentity<ApplicationUserManager, ApplicationUser>(
                        validateInterval: TimeSpan.FromMinutes(30),
                        regenerateIdentity: (manager, user) => user.GenerateUserIdentityAsync(manager))
                }
            });

            //app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);
            app.SetDefaultSignInAsAuthenticationType(DefaultAuthenticationTypes.ExternalCookie);
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ExternalCookie,
                AuthenticationMode = AuthenticationMode.Passive,
                CookieName = CookiePrefix + DefaultAuthenticationTypes.ExternalCookie,
                ExpireTimeSpan = TimeSpan.FromMinutes(5),
            });

            // Enables the application to temporarily store user information when they are verifying the second factor in the two-factor authentication process.
            app.UseTwoFactorSignInCookie(DefaultAuthenticationTypes.TwoFactorCookie, TimeSpan.FromMinutes(5));

            // Enables the application to remember the second login verification factor such as phone or email.
            // Once you check this option, your second step of verification during the login process will be remembered on the device where you logged in from.
            // This is similar to the RememberMe option when you log in.
            app.UseTwoFactorRememberBrowserCookie(DefaultAuthenticationTypes.TwoFactorRememberBrowserCookie);

            var googleOptions = new GoogleOAuth2AuthenticationOptions
            {
                ClientId = ConfigHelper.GetConfigSettingValue("GoogleAppID"),
                ClientSecret = ConfigHelper.GetConfigSettingValue("GoogleAppSecret"),
                Provider = new GoogleOAuth2AuthenticationProvider()
            };
            app.UseGoogleAuthentication(googleOptions);

            var facebookOptions = new FacebookAuthenticationOptions()
            {
                AppId = ConfigHelper.GetConfigSettingValue("FBAppID"),
                AppSecret = ConfigHelper.GetConfigSettingValue("FBAppSecret"),
                UserInformationEndpoint = "https://graph.facebook.com/v3.2/me?fields=id,first_name,last_name,email,name",
                AuthorizationEndpoint = "https://www.facebook.com/v3.2/dialog/oauth"
            };
            app.UseFacebookAuthentication(facebookOptions);
        }
    }
}
```

Still did not work, no exceptions or errors and yet 
```c#
var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();
```
returns null object

**Comment by Tratcher** [comment]
The fix in #331 was to set `CookieManager = new SystemWebCookieManager()` on each CookieAuthenticationOptions, and FacebookAuthenticationOptions and GoogleOAuth2AuthenticationOptions while you're at it.

**Comment by LumaiRashad** [comment]
Okay thanks, It's working fine now, I have been testing since yesterday and finally working fine :')

**Comment by LumaiRashad** [comment]
Okay thanks, It's working fine now, I have been testing since yesterday and finally working fine :')

**Comment by LumaiRashad** [comment]
Okay thanks, It's working fine now, I have been testing since yesterday and finally working fine :')
