### ISSUE TITLE
Cookies get blocked when applications are hosted behind proxy/gateway with SSL/TLS offloading -> SameSite Cookie Changes

### ISSUE THREAD

**Issue by d4devblog** [aspnet/AspNetKatana#332]
Hi, I am currently hacking my way around an issue with an application that uses the Microsoft.Owin.Security packages to authenticate with Azure B2C.

When hosted in our production infrastructure, multiple webservers sit behind an Azure Application Gateway. The gateway performs TLS offloading which results in traffic hitting the webservers with an HTTP connection and not HTTPS.

Part of the authentication flow requires the creation of a cookie labelled 'OpenIdConect.nonce....' which is blocked when testing in Chrome v80 with the new same-site cookie values enabled.

I believe the cookie creation is happening here...
https://github.com/aspnet/AspNetKatana/blob/9e9c44d0b0027cb58a3252a10ea93f25ccab32af/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L620

...and the issue is due to the use of Request.IsSecure
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin/OwinRequest.cs#L87

The IsSecure property only checks the request _scheme_ to determine if a connection is considered 'secure', so behind our gateway, this returns false -> resulting in a cookie that isn't flagged as secure.

Without the secure flag it is blocked by Chrome 80, and the behaviour will roll out to additional browsers soon, breaking logins for our applications.

Would it be feasible to modify the 'IsSecure' property to include checks against request headers found in many gateway/proxy solutions? Such as '**X-Forwarded-Proto: https**'

Or... can the 'Cookie Secure' option for 'Always/Never/SameAsRequest' be respected for this cookie?

**Comment by Tratcher** [comment]
See: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

We recommend adding a middleware to read the X-Forwarded-* headers and update the request fields. That way the request of the app components don't need to be proxy aware. Without this kind of update even your link generation is wrong.

Katana doesn't have a pre-built middleware for this, but reading X-Forwarded-Proto and setting Request.Scheme is just a few lines.

**Comment by d4devblog** [comment]
Thanks for the quick response. I will look into this and feedback as soon as possible.

**Comment by d4devblog** [comment]
Thanks again @Tratcher - Your suggestion has worked a treat!
A much cleaner solution compared to where I was headed -> Trying to fix the cookie after it had been created. 

For anyone else hitting this issue, pseudo middleware code is as below...

`

    var proxyProtocol = context.Request.Headers["X-Forwarded-Proto"];
    if (proxyProtocol.Equals("https", StringComparison.OrdinalIgnoreCase))
    {
        context.Request.Scheme = "https";
    }
    await Next.Invoke(context);`

**Comment by Tratcher** [comment]
Props for actually checking the value before asigning it. :-)
