### ISSUE TITLE
OIDC issues with .NET 4.5

### ISSUE THREAD

**Issue by brcomsto** [aspnet/AspNetKatana#335]
One of my customers is having some issues with OpenID Connect and .NET 4.5 apps.

Here is an overview:

"looking to build Open ID Connect into a nuget package that we can re-use with our .NET applications. We have one compiled for dotnet 2.2 and almost 3.1 already, but .NET 4.5 had a few hiccups.

We got it to work using OWIN middleware, but we have to capture the events and manually validate the state as well as leave an empty string in session.

Without the empty string it loops through redirection like it swallowed an exception and retried, then eventually fails.

As far as I can tell, the state can’t be validated with the nuget package Microsoft.Owin.Securtiy.OpenIdConnect 4.1.0. I decompiled it and state is never passed into the function that requires it for validation. However, this nuget package has shown up on every guide to implement OIDC in .NET Framework 4.5”

Not sure if there is this is a bug / issue with 4.5 - is there some guidance we can provide?  Will also search within this issues list for any pointers.  Thank you.

**Comment by Tratcher** [comment]
The most common issue related to Session is having the cookies get overridden if Session is established at the wrong time. See https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues for the mitigation.

If that doesn't help, the next step to investigate would be sharing Fiddler traces, code samples, and/or a repro app.

**Comment by brcomsto** [comment]
Thank you.  will research with customer and see if mitigation applies.
