### ISSUE TITLE
How do we handle when put Microsoft.Owin.Host.HttpListener to the GAC?

### ISSUE THREAD

**Issue by huangjinshe** [aspnet/AspNetKatana#337]
We project need to put Microsoft.Owin.Host.HttpListener to the GAC. But This will keep throw exception:

`The server factory could not be located for the given input: Microsoft.Owin.Host.HttpListener`

I don't want to be rude, but who is idea of design it like this? on the development machine it will also throw exception if the main program not also reference it, (It was put in my middle class library, the library already referenced it, but it's not enough.....)

The design about this class let us too busy, really....

**Comment by Tratcher** [comment]
What are you accomplishing by putting it in the GAC?

You should be able to replace the `IServerFactoryLoader`, but honestly the Dependency Injection scenario here has rarely been used and is lightly documented so I don't have a good example on how to replace this. I see a few generic examples online for working with Autofac and other containers. There are also a few hints in the unit tests.
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/tests/Microsoft.Owin.Hosting.Tests/Containers/ReplaceDefaultServiceWithTextFileTests.cs#L16
https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/tests/Microsoft.Owin.Hosting.Tests/Containers/TinyIoCContainerTests.cs#L17

**Comment by huangjinshe** [comment]
Sorry, it's for let multiple app share it together. but currently design let me copy every `Microsoft.Owin.Host.HttpListener.dll` to everywhere, other component don't needed like:
```
Microsoft.Owin.Hosting.dll
Microsoft.Owin.Security.dll
Owin.dll
Microsoft.Owin.dll
Microsoft.Owin.Cors.dll
Microsoft.AspNet.SignalR.Core.dll
```
They all can be put in gac.

If hope someone could tell me how exactely replace `IServerFactoryLoader` to fix it. I would be very appreciated.

**Comment by huangjinshe** [comment]
@Tratcher  For the second problem, I didn't see Microsoft signalR document said that the main reference must be also include like:
```
Microsoft.Owin.Host.HttpListener.dll
Microsoft.Owin.Security
Microsoft.Owin
```
It never mentioned it, I could only search from google when the problem shows.([Tutorial: SignalR Self-Host](https://docs.microsoft.com/en-us/aspnet/signalr/overview/deployment/tutorial-signalr-self-host)) never mentioned about if the library needed SignalR, the main assembly need to reference the SignalR too  which use that library.
The problem shows when I'm using A assembly references B, and B use SignalR.  It would let A assembly also need to references these to use it, I've never saw design like that, dont't use but still need to reference.

**Comment by Tratcher** [comment]
Microsoft.Owin.Host.HttpListener.dll is 84kb, you're not saving yourself much for your hassle.

SignalR can run on a variety of servers so they don't spend a lot of time on the details of each. The tutorial does tell you to add a package dependency on Microsoft.AspNet.SignalR.SelfHost which pulls in Microsoft.Owin.Host.HttpListener and the other Microsoft.Owin dlls transitively.

I do see several related posts on StackOverflow. This one looks the most promising for you:
https://stackoverflow.com/a/30263543/2588374

**Comment by huangjinshe** [comment]
@Tratcher Manually load souds like a good idea, I'll try.
