### ISSUE TITLE
Does Owin samesite support Chrome v80  Rigorous mode?  

### ISSUE THREAD

**Issue by wangzhengdao** [aspnet/AspNetKatana#339]
Does Owin samesite support Chrome v80  Rigorous mode?  
Chrome.exe --enable-features=SameSiteDefaultChecksMethodRigorously

https://www.chromium.org/updates/same-site/test-debug

**Comment by Tratcher** [comment]
Yes, we asked chrome to add that mode.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/410

**Comment by Tratcher** [comment]
Capturing and sharing a decrypted Fiddler trace is the best way to debug this.

**Comment by jhorsman** [comment]
Thank you for confirming @Tratcher.
