### ISSUE TITLE
Does SameSite cookie support work with Owin 4.1 on .NET Framework 4.7.1 ?

### ISSUE THREAD

**Issue by wangzhengdao** [aspnet/AspNetKatana#340]

**Comment by anurse** [comment]
It should work, as far as I know. Newer versions of the .NET Framework are generally compatible with code written for earlier versions.

Are you seeing errors or problems using it?

**Comment by wangzhengdao** [comment]
I changed my question title to make it  more clear.

**Comment by Tratcher** [comment]
The answer is pretty subtle. I assume you're running in IIS? (Most but not all apps using Microsoft.Owin do). A) it's the version of the runtime installed on the machine that matters, not the version targeted by the app at compile time. B) It depends on if you're using the SystemWebCookieManager mitigation outlined here: https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues

Microsoft.Owin supports SameSite on all versions of .NET 4.X unless you're using SystemWebCookieManager. SystemWebCookieManager requires 4.7.2 be installed on the machine to support SameSite in IIS.
