### ISSUE TITLE
Unexpected error handling behavior for RefreshOnIssuerKeyNotFound = true

### ISSUE THREAD

**Issue by rpannekoek** [aspnet/AspNetKatana#342]
We are observing  exceptions of type `SecurityTokenSignatureKeyNotFoundException` after a signing key rollover.
This exception occurs once after the rollover; the next request is fine.
We have already set `OpenIdConnectAuthenticationOptions.RefreshOnIssuerKeyNotFound` to `true` and this indeed causes a refresh of the OIDC metadata when the exception occurs, but it doesn't prevent the exception from being thrown.
It would be better if signature validation is retried immediately when the OIDC metadata has been refreshed, but that doesn't happen in the current implementation.

**Comment by Tratcher** [comment]
This is intended for several reasons.
- The refresh happens in the background, it doesn't block the current request. We don't know how long the refresh will take nor how many signins will be attempted in that time frame.
- The refresh is throttled, it will only try to refresh once in a given time period (5 min?) even if there are multiple failures.
- The refresh is suppose to happen automatically every 24 hours. The guidance is to introduce new keys, let them propagate, and then remove the old ones. That would prevent a request from ever coming in with bad keys.
