### ISSUE TITLE
Twitter Authentication

### ISSUE THREAD

**Issue by suencien** [aspnet/AspNetKatana#343]
After Twitter external authentication is successful, the user is returned to https://iluvrun.com/signin-twitter. I can grab the user's user id (urn:twitter:userid) and screenname (urn:twitter:screenname). How do we extract their email and first name? How do we extract the access token and access token returned from Twitter?

Can someone please help?

**Comment by Tratcher** [comment]
Twitter uses a very outdated OAuth1a protocol that requires additional steps to get the e-mail and other profile data. That was never implemented in Microsoft.Owin.Security.Twitter, but you can wire it up in the provider events. Last I checked you also had to request explicit permission from Twitter via support to get e-mail addresses enabled.
https://github.com/aspnet/AspNetKatana/blob/e001fcf245ba4b6b2eb09ef410d398527882dc1a/src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationOptions.cs#L99
https://github.com/aspnet/AspNetKatana/blob/e001fcf245ba4b6b2eb09ef410d398527882dc1a/src/Microsoft.Owin.Security.Twitter/Provider/TwitterAuthenticationProvider.cs#L28

We have implemented this logic in Microsoft.AspNetCore.Authentication.Twitter if you can move to AspNetCore, or if you want to use it as a guide:
https://github.com/dotnet/aspnetcore/blob/cc79bcc67b2399bbfbdd33754de1876cf7c8ba1d/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L283-L300

**Comment by suencien** [comment]
Hi Chris,

Thank you for your responding.

Yes I’ve opted to request email address from users as well. However I don’t know how to retrieve it at the old ASP.NET Web Forms.

Hey, I’d like to get access to the oauth_token and oauth_verifier Request.Query. I’m .NET Core blind however. Do you know how to get access to them on .NET Web Forms?

Thanks so so much for your help!

Cheers,

Andry

**Comment by Tratcher** [comment]
The auth middleware processes the oauth_verifier and returns an access token (oauth_token). You can get the access token in the events I linked above using TwitterAuthenticatedContext.AccessToken. You shouldn't need the oauth_verifier after you've gotten the access token.

If you need the access token later for API calls then you hook the same OnAuthenticated and add the access token to the ClaimsIdentity or AuthenticationProperties.

**Comment by suencien** [comment]
Hi Chris,

Awesome!! I got it working! Thanks so much for your help!

Cheers,

Andry
