### ISSUE TITLE
OpenIdConnect Get claims from user info endpoint

### ISSUE THREAD

**Issue by laura-rodriguez** [aspnet/AspNetKatana#344]
Hi,

In ASP.NET Core, it's possible to configure `GetClaimsFromUserInfoEndpoint` to [get additional claims from user info endpoint](https://github.com/dotnet/aspnetcore/blob/2e0cf080dffa957fa0a665da5ec87d2be1b402ee/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L728).  Are you guys planning to implement this here?

**Comment by Tratcher** [comment]
No, we don't plan any additional feature expansion in this code base. You can fetch additional claims in the various events like SecurityTokenValidated.

**Comment by anurse** [comment]
Closing, as we don't plan to add this feature in Katana.

**Comment by laura-rodriguez** [comment]
Thanks for your prompt response @Tratcher . That was my intention, adding this logic in the SecurityTokenValidated event. However, I noticed this event is not being triggered after I changed my OIDC configuration to use the code flow. I can successfully subscribe to other events such as `TokenResponseReceived` or `RedirectToIdentityProvider`, but not `SecurityTokenValidated`. Am I missing something here? I'd appreciate any help. This is my configuration:

```
var oidcOptions = new OpenIdConnectAuthenticationOptions
            {
                ClientId = options.ClientId,
                ClientSecret = options.ClientSecret,
                Authority = issuer,
                RedirectUri = options.RedirectUri,
                ResponseType = OpenIdConnectResponseType.Code,
                RedeemCode = true,
                Scope = scopeString,
                PostLogoutRedirectUri = oktaMvcOptions.PostLogoutRedirectUri,
                TokenValidationParameters = tokenValidationParameters,
                SecurityTokenValidator = new StrictSecurityTokenValidator(),
                SaveTokens = true,
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenReceived = OnTokenReceivedAsync,
                    RedirectToIdentityProvider = notifications.RedirectToIdentityProvider,
                    TokenResponseReceived = OnTokenResponseReceivedAsync,
                    SecurityTokenValidated = OnTokenValidatedAsync,
                },
            };
```

**Comment by laura-rodriguez** [comment]
Disregard my previous question, I found the issue in my code. Thank you!
