### ISSUE TITLE
SameSite changes break some cookie updates

### ISSUE THREAD

**Issue by Peperud** [aspnet/AspNetKatana#349]
Watched the following scenario (server with latest updates and .NET frameworks): 
1. A ```.NET 4.52``` built application creates a cookie. Browser receives the cookie **without** a  _SameSite_ setting.
2. On a post back, a cookie is pulled from the request, and its value is updated. The cookie is then added back to the response. Browser receives the cookie with _SameSite_=**None**.
3. Browser ignores the new cookie, because it now has _SameSite_=**None**, but is not marked as _secure_.

The problem appears to be that when the request's cookies collection is made, the cookie is created with _SameSite_=**None**. When the cookie is pulled out, (its value) updated and set on the response, it continues to carry this setting. 

All while the ```.NET 4.52``` code doesn't even see the property.  

This breaks an application that would have otherwise be unaffected by whether or not same site rules are enforced (will be fine with the assumed **Lax** value).

Doesn't it make more sense to default the _SameSite_  to **Unset / -1** instead of **None** when creating the request's cookie collection?

**Comment by Tratcher** [comment]
I've seen this issue with System.Web request cookies, but not Microsoft.Owin request cookies. You're using System.Web's HttpRequest directly correct?

**Comment by Peperud** [comment]
Yes. System.Web's HttpRequest. 
I'm sorry for the post in the wrong repo (though there doesn't seem to be an active one for System.Web).

In your opinion, do you consider that to be a bug (that I should submit)?

**Comment by Tratcher** [comment]
Yeah, it's a bug we're aware of, though I'll remind them again. Can you give a code sample of your usage for me to show them? This hasn't been a common scenario.

**Comment by Peperud** [comment]
Here you go. Thanks.

[UpdateCookieProblem.zip](https://github.com/aspnet/AspNetKatana/files/4519744/UpdateCookieProblem.zip)

**Comment by Tratcher** [comment]
Thanks, I've forwarded this to the relevant team. Closing this issue.
