### ISSUE TITLE
How can I access "scope" property in refresh_token flow?

### ISSUE THREAD

**Issue by metallserge** [aspnet/AspNetKatana#35]
Hi all!

in OAuth2 https://tools.ietf.org/html/rfc6749#section-6 we may pass optional "scope" property

But in Microsoft.Owin.Security.OAuth 3.0.1 there is no way to detect this property, except ValidateTokenRequest/OnValidateTokenRequest in OAuthAuthorizationServerProvider (IOAuthAuthorizationServerProvider).
See  https://github.com/aspnet/AspNetKatana/blob/2d41a5c057d877cd921a8675d7b5e12095d25997/src/Microsoft.Owin.Security.OAuth/OAuthAuthorizationServerHandler.cs#L610 . tokenEndpointRequest.RefreshTokenGrant.RefreshToken has this property Scope, but it is not used

But this method is common for any request, while for refresh_token there are:
- RecieveAsync in IAuthenticationTokenProvider
and
- GrantRefreshToken in IOAuthAuthorizationServerProvider

which, I assume, are more related to refresh workflow

Thanks

**Comment by Tornhoof** [comment]
In ReceiveAsync I use: ``var scope = context.OwinContext.Get<IEnumerable<string>>("scope");``
I never needed the scope in GrantRefreshToken
HTH

**Comment by metallserge** [comment]
Thanks for reply,
good to know there is a simple workaround, I'll try it

but it's a workaround

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
