### ISSUE TITLE
Clarification on OpenIdConnect.nonce cookie issuing expectations?

### ISSUE THREAD

**Issue by Peperud** [aspnet/AspNetKatana#352]
Scenario:
======
All servers in our production environment are behind **SSL terminating proxies**.
Same application version (at least as it pertains to openid/owin with latest available dependencies as of Feb 2020) is installed on different servers. 
The servers are not far behind on updates, though not all are necessarily on the same level.
Chrome 81.

Observation:
=========
On some servers the _nonce_ cookie comes down _without_ being marked anything for **_samesite_** and _without_ being marked as **secure**.
On other servers however, the _nonce_ cookie is marked as **samesite**=_None_, but it is still _not_ **secure**.

Expectations:
=========
Looks to me that both cases are incorrect.
Given the latest development in the **samesite** cookie handling requirements, it seems there's no reason to issue the **nonce** cookie any other way but _with_ **samesite**=**None** _and_ **secure** regardless of the environment.

The question is - what should be expected an up to date system to look like in respect to the **openidconnect** **nonce** cookie issuing?

**Comment by Tratcher** [comment]
For the secure attribute:

When running behind a reverse proxy the recommendation is to forward fields like the original request scheme via x-forwarded-* headers and updating the request structure so that individual components don't have to be aware of the proxy.

We have a doc for this in AspNetCore.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

We don't have that middleware available for Katana, but the basics are pretty easy:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1#scenarios-and-use-cases

For the samesite attribute:
Yes, a server with updated .NET and Microsoft.Owin libraries should be emitting `samesite=None` for the nonce cookies.

There's a writeup on SameSite available here: https://docs.microsoft.com/en-us/aspnet/samesite/owin-samesite

**Comment by Peperud** [comment]
@Tratcher Thanks! I'll do something about it.
I agree with the part where components should not be aware of proxies. 

However, one could argue, that there's no point of issuing a cookie with ```samesite=None```, but not secure (regardless of the request scheme) as this is a requirement now (even if not fully enforced yet). 
Even more so for the openid _nonce_, where _https_ is a must.

Or am I missing something?

**Comment by Tratcher** [comment]
> However, one could argue, that there's no point of issuing a cookie with `samesite=None`, but not secure (regardless of the request scheme) as this is a requirement now (even if not fully enforced yet).
> Even more so for the openid _nonce_, where _https_ is a must.

It does complicate the back compat story though. Better to have the whole system agree if the request is really HTTPS or not. Lots of other things in your site break when this is out of sync like link and redirect generation.

> BTW - since we have to use the _SameSiteCookieManager_ to deal with older browsers, wouldn't it be a better place to add the _secure_ flag to the `samesite=None` cookies too?

You could do that, but see my earlier comment about keeping the request HTTPs state in sync. If it's right then you don't have to work around it in multiple places.

**Comment by Peperud** [comment]
> It does complicate the back compat story though. Better to have the whole system agree if the request is really HTTPS or not. Lots of other things in your site break when this is out of sync like link and redirect generation.

Understood. Thanks!

I'm sure I'm missing things, but just thinking out loud...

...existing systems have been running behind SSL terminating proxies for long time. So they must have the other issues sorted out by now. 

However, the _"samesite=None_ and not _secure_" will force them to change code (instead of just update dependencies). Doesn't seem backwards compatible either.

**Comment by Tratcher** [comment]
Very little about the samesite=None spec was backwards compatible, most apps have had to make code changes such as adding SameSiteCookieManager.

Yes there were a few other choices we could have made here, but we don't plan any further changes at the moment so we'll primarily give guidance for the time being.

**Comment by Peperud** [comment]
Thanks again, Chris. Appreciate it your help!

Closing.
