### ISSUE TITLE
Seeing a login loop

### ISSUE THREAD

**Issue by gurua** [aspnet/AspNetKatana#353]
We are seeing a login loop when accessing our site but we are unable to determine what is wrong. We are using 4.1.0 and have tried the workaround suggested here: https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues but it hasn't helped. Is there any debugging that we can add to determine what is happening?

**Comment by Tratcher** [comment]
A decrypted Fiddler trace is the first tool. You can share the trace file here or via the e-mail in my profile.

**Comment by PascoFNS** [comment]
I experienced this as well and was able to work around by downgrading to 4.0.1.

**Comment by Tratcher** [comment]
A decrypted Fiddler trace is the first tool. You can share the trace file here or via the e-mail in my profile.
