### ISSUE TITLE
Could not load file or assembly 'Microsoft.SharePoint.Client.ServerRuntime, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by bwong199** [aspnet/AspNetKatana#354]
Hi, 

When I install Microsoft.Owin.Host.SystemWeb, I get the following error:

Could not load file or assembly 'Microsoft.SharePoint.Client.ServerRuntime, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c' or one of its dependencies. The system cannot find the file specified.

When I uninstall it, my solution runs fine. 

Kindly advise. 

Thanks.

**Comment by Tratcher** [comment]
What's the stack trace of the exception?

This may be caused by the Startup auto-discovery feature. There are a few ways to specify the location of your Startup class to skip this step. See https://github.com/aspnet/AspNetKatana/wiki/Configuration
