### ISSUE TITLE
Integrated Security - Logging

### ISSUE THREAD

**Issue by MrGrando** [aspnet/AspNetKatana#356]
I'm using Katana in a Self-Hosted set-up with Integrated security enabled, and everything works fine!
Except that I whould like to log if a user have provided faulty credentials (e.g. a 401 return).
I have tried various things (MiddleWare, custom exception handler etc) but I cannot trap when authenttication fails..
Can logging be done in my set-up and if so how?

Thanks.

//G

**Comment by Tratcher** [comment]
The windows authentication isn't handled at the Katana layer, it's handled down in the HttpListener server. See System.Net.HttpListener at https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing

**Comment by MrGrando** [comment]
I somewhat anticipated this anwser, since a carefully constructed design flaw is hard to distinguish from a feature.  For my current project point of view this flaw (re-use comes at a prices) makes self-hosted Katana totally utterly useless.. not beeing able provide a **full** accesslog and errorlog rules out Katana, and as I suspect any solution that is used somewhat at scale (at least with serious security people involved).  It's a pitty, I kinda liked the self hosted minimalistic approach.

**Comment by Tratcher** [comment]
The components we do have with this level of control are in AspNetCore, using Kestrel + Negotiate. https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#kestrel
