### ISSUE TITLE
OpenIdConnect and ASPNET

### ISSUE THREAD

**Issue by juanan** [aspnet/AspNetKatana#358]
Hi,

I want to include in my ASPNET project (.Net Framework 4.7.2) the protocol OpenIdConnect to authenticate against an Identity Server using a code authorization flow with Pkce.

My question is if I can use your Protocols.OpenIdConnect nuget package because all examples are with ASPNET Core or MVC.

Many thanks.

**Comment by Tratcher** [comment]
PKCE has not yet been implemented. See #334
