### ISSUE TITLE
It doesn't support HTTP/2 when using .net framework 4.x

### ISSUE THREAD

**Issue by ddan320** [aspnet/AspNetKatana#365]
Windows version: 2016 server
.net framework: 4.6.2
Client receive error: net::ERR_HTTP2_PROTOCOL_ERROR

**Comment by Tratcher** [comment]
That error is the server claiming the client has violated the protocol.

HTTP/2 should work regardless of the .NET Framework version, it's implemented by the underlying OS libraries.

What client are you using? How did you reproduce the error?

Or capture an ETW trace of the repro?
```
netsh trace start overwrite=yes report=dis correlation=dis traceFile=http.etl provider={20F61733-57F1-4127-9F48-4AB7A9308AE2} level=0x5 keywords=0x7fffffff
```
Run the repro, and then:
```
netsh trace stop
```
And then share the http.etl file.

**Comment by ddan320** [comment]
Thanks for the quick reply, I think you are right, I found my code can't get the response but postman works well, so there must have some other bugs in my code, thanks for your time, I will close the issue.
