### ISSUE TITLE
.net core migration from 1.1 to 2.1 using Microsoft.Owin.Security.WsFederation 

### ISSUE THREAD

**Issue by koraded** [aspnet/AspNetKatana#367]
Hello Team,
I am migrating my .net core application to 2.1 from 1.1 but during migration i am getting "No authenticationScheme was specified, and there was no DefaultChallengeScheme found" error.I am using Microsoft.Owin.Security.WsFederation  library.After seraching on internet found this link https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-3.1
where we need to set  DefaultChallengeScheme  but i am not sure how to set DefaultChallengeScheme  using this Microsoft.Owin.Security.WsFederation  package.

Please provide some input if i am missing something here
Regards,
Dhananjay

**Comment by Tratcher** [comment]
None of the Microsoft.Owin packages are supported on .NET Core. The Microsoft.Owin.Security.WsFederation package was replaced by Microsoft.AspNetCore.Authentication.WsFederation. Here are the docs for that scenario:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-3.1
