### ISSUE TITLE
How implements Authorization Code Flow ?

### ISSUE THREAD

**Issue by CharlyIQar** [aspnet/AspNetKatana#369]
Hello,

Have you an example of authorization code flow implementation for OpenId connection ?

I use implicit flow and I want migrate to code flow.

Thanks !

Charly

**Comment by Tratcher** [comment]
1. Use package version 4.1
1. Set the normal properties like client id, authority, etc.
1. Also set the client secret
1. Set ResponseType = OpenIdConnectResponseType.Code,
1. Set RedeemCode = true

**Comment by CharlyIQar** [comment]
Thanks @Tratcher , it's ok !
