### ISSUE TITLE
DefaultFilesMiddleware does not find default file if path contains percent-escaped characters

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [aspnet/AspNetKatana#371]
In Microsoft.Owin.StaticFiles 3.0.1, if the request URI is `http://localhost:8080/merkinn%C3%A4t/`, and a `merkinnät\index.html` file exists, then DefaultFilesMiddleware does not find it. Process Monitor shows it tries to open `merkinn%C3%A4t\index.html` instead.

The bug seems to be here: <https://github.com/aspnet/AspNetKatana/blob/24aa43641adac57cb5bd523b77bdc0ced9f0455d/src/Microsoft.Owin.StaticFiles/DefaultFilesMiddleware.cs#L72>

`subpath` is a PathString whose PathString.Value is `"/merkinnät/"`, and `defaultFile` is `"index.html"` as a string. The expression `subpath + defaultFile` calls PathString.ToString, which calls PathString.ToUriComponent, which returns `"/merkinn%C3%A4t/"`. DefaultFilesMiddleware then calls IFileSystem.TryGetFileInfo with `"/merkinn%C3%A4t/index.html"`, which is wrong. Before that, DefaultFilesMiddleware had called IFileSystem.TryGetDirectoryContents with `"/merkinnät/"`, which was correct.

This bug affects `docfx serve` in DocFX 2.45.1.0. I have not tested later versions of Microsoft.Owin.StaticFiles but it looks like the last code change to `DefaultFilesMiddleware` was in Microsoft.Owin.StaticFiles 3.0.0.

**Comment by Tratcher** [comment]
Looks like we fixed this in AspNetCore 2.2 but not Katana.
https://github.com/dotnet/aspnetcore/commit/a43587290fecff5a1229d8cb7f26603c01c7ab1d
