### ISSUE TITLE
Steam Provider

### ISSUE THREAD

**Issue by danielvieira43** [aspnet/AspNetKatana#372]
Hi, 

I'm not abble to login with Steam anymore in debug sessions with chrome using Visual Studio 2017 after update to 4.1.0 version.
Using version 4.0.1 it is working fine. Or using other browsers to debug, but this is not desirable right now.

Any help please?

Thanks!

**Comment by Tratcher** [comment]
We don't provide a Steam login component. What Microsoft.Owin libraries are you using? OAuth? OpenIdConnect?

The most likely change you're having issues with in 4.1.0 is SameSite.
https://docs.microsoft.com/en-us/aspnet/samesite/owin-samesite

Can you share a Fiddler trace showing the issue?
