### ISSUE TITLE
Request.IsAuthenticated is false after sign in was success in Azure Active Directory

### ISSUE THREAD

**Issue by ameenurrahman36** [aspnet/AspNetKatana#381]
After successfully signing in AAD which redirects to my localhost in IIS with 302 status POST from AAD which has the form data and immediately after that there is 200 status GET which doesn't have the form data and the Request.IsAuthenticated is false.

Am using VS 2017, IIS and .Net Framework 4.6.1 ASP.NET Web Forms

**Comment by Tratcher** [comment]
Please share a fiddler trace of these requests. It sounds like a cookie isn't getting sent or returned.

**Comment by ameenurrahman36** [comment]
Hi Tratcher,
                  Thanks for your response, I am facing some issue with fiddler system proxy so am not able to capture data with fiddler but I did with chrome browser network tab and am pasting the same over here for your perusal


[Response 302.txt](https://github.com/aspnet/AspNetKatana/files/5185578/Response.302.txt)
[Response 200.txt](https://github.com/aspnet/AspNetKatana/files/5185579/Response.200.txt)

**Comment by Tratcher** [comment]
I'd need to see the initial request that redirected to AAD to get the complete picture. From what I can see it is returning with a code and the right cookies, but then you don't get the local cookies issued.

The usual issue at that state is a conflict in System.Web issuing the cookies. There's a mitigation here:
https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues#workarounds

**Comment by ameenurrahman36** [comment]
Thanks for your reply, I have attached the initial requests, I did use the workaround but it gives nonce not there error.
[Login.aspx.txt](https://github.com/aspnet/AspNetKatana/files/5186377/Login.aspx.txt)
[login.microsoftonline.com.txt](https://github.com/aspnet/AspNetKatana/files/5186379/login.microsoftonline.com.txt)

**Comment by Tratcher** [comment]
Why is the OpenIdConnectAuthenticationOptions.RedirectUri set to `https://localhost:/linkone3/ExternalLogin/RegisterExternalLogin.aspx`? It should be set to a unique path like `https://localhost:/linkone3/signin-oidc` to avoid conflicts with other pages.

That still doesn't explain why it's not returning any of the cookies. Can you share the Startup code where you applied the SystemWebCookieManager?

**Comment by ameenurrahman36** [comment]
Hi,
    Thanks for your response, I am using the RegisterExternalLogin.aspx as the redirect url from AAD to process the response from AAD. I have attached the StartUp.cs and when I use the SystemWebCookieManager, I get the following error:

IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.

[Startup.Auth.cs.txt](https://github.com/aspnet/AspNetKatana/files/5192127/Startup.Auth.cs.txt)

**Comment by Tratcher** [comment]
The SystemWebCookieManager should be used with both UseCookieAuthentication and UseOpenIdConnectAuthentication. 

You also seem to be mixing OpenIdConnect and Asp.Net Identity. Do you want those to work together or are they supposed to be two separate systems? If you want to integrate them then OpenIdConnect should be using DefaultAuthenticationTypes.ExternalCookie as its SignInAsAuthenticationType. Only Identity should be setting the DefaultAuthenticationTypes.ApplicationCookie.

OpenIdConnectAuthenticationOptions.RedirectUri really should not be set to the same path as another page, it should be a unique path for the OIDC middleware. The OIDC middleware will redirect back to the path specified in the original Challenge when it's done.

Also, you shouldn't need to copy the SystemWebCookieManager, that's shipped with the packages since 3.1 (and you should be using the 4.1 packages by now).

**Comment by ameenurrahman36** [comment]
Hi,
    Thanks for your response, I have modified the changes you have suggested but it's not authenticated, the flow is as follows:
Login.aspx -> AAD -> RegisterExternalLogin.aspx

Is there something am missing, waiting for your comments to fix this issue because am trying since last week.

**Comment by ameenurrahman36** [comment]
Forgot to attach the modified Startup.Auth.cs for your perusal.

[Startup.Auth.cs.txt](https://github.com/aspnet/AspNetKatana/files/5206798/Startup.Auth.cs.txt)

**Comment by Tratcher** [comment]
Does the updated fiddler trace show the nonce cookie now?

Unfortunately UseExternalSignInCookie might also need the CookieManager, but it's not directly modifiable. You may have to copy this code to add it.

https://github.com/aspnet/AspNetIdentity/blob/a24b776676f12cf7f0e13944783cf8e379b3ef70/src/Microsoft.AspNet.Identity.Owin/Extensions/AppBuilderExtensions.cs#L101-L126

**Comment by ameenurrahman36** [comment]
It does have the nonce cookie in the attachment below, where exactly do I need to add the UseExternalSignInCookie in the attachment I have sent in the previous comment of Startup.Auth.cs

[Response 302.txt](https://github.com/aspnet/AspNetKatana/files/5216844/Response.302.txt)

**Comment by Tratcher** [comment]
You already have UseExternalSignInCookie in your code, but it won't let you set its CookieManager. Try copying the code from [here](https://github.com/aspnet/AspNetIdentity/blob/a24b776676f12cf7f0e13944783cf8e379b3ef70/src/Microsoft.AspNet.Identity.Owin/Extensions/AppBuilderExtensions.cs#L101-L126) into your app so you can modify it to set the CookieManager. You should be able to directly replace UseExternalSignInCookie with [this](https://github.com/aspnet/AspNetIdentity/blob/a24b776676f12cf7f0e13944783cf8e379b3ef70/src/Microsoft.AspNet.Identity.Owin/Extensions/AppBuilderExtensions.cs#L118-L125) code. 

Also, I see that you're OIDC nonce cookie isn't marked with SameSite=None, which means you're using a version older than 4.1. You should update if you want this to keep working in Chrome. https://docs.microsoft.com/en-us/aspnet/samesite/owin-samesite

**Comment by ameenurrahman36** [comment]
Here is the package file and tell me whether am using the latest versions:

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="log4net" version="2.0.8" targetFramework="net461" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.AspNet.Identity.Owin" version="2.2.1" targetFramework="net45" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net461" />
  <package id="Microsoft.Owin" version="4.1.1" targetFramework="net461" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.1.1" targetFramework="net461" />
  <package id="Microsoft.Owin.Security" version="4.1.1" targetFramework="net461" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.1.1" targetFramework="net461" />
  <package id="Microsoft.Owin.Security.OAuth" version="4.1.1" targetFramework="net461" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="3.1.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net45" />
  <package id="NuGet.CommandLine" version="4.6.2" targetFramework="net45" developmentDependency="true" />
  <package id="Owin" version="1.0" targetFramework="net45" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.4.403061554" targetFramework="net461" />
</packages>

Am still getting Request.IsAuthenticated as false after modifying the Startup.Auth.cs to include the code you have mentioned and please let me know whether it's correct which you can find in the attachment.

[Startup.Auth.cs.txt](https://github.com/aspnet/AspNetKatana/files/5229571/Startup.Auth.cs.txt)

**Comment by Tratcher** [comment]
Microsoft.Owin.Security.OpenIdConnect should also be version 4.1.1. That will also raise your System.IdentityModel.Tokens.Jwt dependency.

If you're still having trouble after that then please share an updated Fiddler trace.

**Comment by ameenurrahman36** [comment]
I have added the latest versions of dlls and included the SameSite code as well please see attachment, still not Request.IsAuthenticated, please the trace also from chrome.
[Response 302.txt](https://github.com/aspnet/AspNetKatana/files/5231759/Response.302.txt)
[packages.xml.txt](https://github.com/aspnet/AspNetKatana/files/5231760/packages.xml.txt)
[Startup.Auth.cs.txt](https://github.com/aspnet/AspNetKatana/files/5231761/Startup.Auth.cs.txt)

**Comment by Tratcher** [comment]
You didn't apply the CookieManager to the ExternalCookie, and that's the cookie that's missing in the network trace.

```
                    app.UseCookieAuthentication(new CookieAuthenticationOptions
                    {
                        AuthenticationType = DefaultAuthenticationTypes.ExternalCookie,
                        AuthenticationMode = AuthenticationMode.Passive,
                        CookieName = ".AspNet." + DefaultAuthenticationTypes.ExternalCookie,
                        ExpireTimeSpan = TimeSpan.FromMinutes(5),
                        CookieManager = new SameSiteCookieManager(
                                     new SystemWebCookieManager())
                    });
```

**Comment by ameenurrahman36** [comment]
I have added that too and still the Request.IsAuthenticated is false, see the attachment for the trace and code.
[Startup.Auth.cs.txt](https://github.com/aspnet/AspNetKatana/files/5255586/Startup.Auth.cs.txt)
[Response 302.txt](https://github.com/aspnet/AspNetKatana/files/5255587/Response.302.txt)

**Comment by Tratcher** [comment]
According to the traces it's working. The OIDC request set the .AspNet.ExternalCookie and it was returned on the next request. The only question left is how you read that cookie. The template code for RegisterExternalLogin.aspx.cs looks like this:

```
using System;
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Owin;
using WebApplication14.Models;

namespace WebApplication14.Account
{
    public partial class RegisterExternalLogin : System.Web.UI.Page
    {
        protected string ProviderName
        {
            get { return (string)ViewState["ProviderName"] ?? String.Empty; }
            private set { ViewState["ProviderName"] = value; }
        }

        protected string ProviderAccountKey
        {
            get { return (string)ViewState["ProviderAccountKey"] ?? String.Empty; }
            private set { ViewState["ProviderAccountKey"] = value; }
        }

        private void RedirectOnFail()
        {
            Response.Redirect((User.Identity.IsAuthenticated) ? "~/Account/Manage" : "~/Account/Login");
        }

        protected void Page_Load()
        {
            // Process the result from an auth provider in the request
            ProviderName = IdentityHelper.GetProviderNameFromRequest(Request);
            if (String.IsNullOrEmpty(ProviderName))
            {
                RedirectOnFail();
                return;
            }
            if (!IsPostBack)
            {
                var manager = Context.GetOwinContext().GetUserManager<ApplicationUserManager>();
                var signInManager = Context.GetOwinContext().Get<ApplicationSignInManager>();
                var loginInfo = Context.GetOwinContext().Authentication.GetExternalLoginInfo();
                if (loginInfo == null)
                {
                    RedirectOnFail();
                    return;
                }
                var user = manager.Find(loginInfo.Login);
                if (user != null)
                {
                    signInManager.SignIn(user, isPersistent: false, rememberBrowser: false);
                    IdentityHelper.RedirectToReturnUrl(Request.QueryString["ReturnUrl"], Response);
                }
                else if (User.Identity.IsAuthenticated)
                {
                    // Apply Xsrf check when linking
                    var verifiedloginInfo = Context.GetOwinContext().Authentication.GetExternalLoginInfo(IdentityHelper.XsrfKey, User.Identity.GetUserId());
                    if (verifiedloginInfo == null)
                    {
                        RedirectOnFail();
                        return;
                    }

                    var result = manager.AddLogin(User.Identity.GetUserId(), verifiedloginInfo.Login);
                    if (result.Succeeded)
                    {
                        IdentityHelper.RedirectToReturnUrl(Request.QueryString["ReturnUrl"], Response);
                    }
                    else
                    {
                        AddErrors(result);
                        return;
                    }
                }
                else
                {
                    email.Text = loginInfo.Email;
                }
            }
        }        
        
        protected void LogIn_Click(object sender, EventArgs e)
        {
            CreateAndLoginUser();
        }

        private void CreateAndLoginUser()
        {
            if (!IsValid)
            {
                return;
            }
            var manager = Context.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var signInManager = Context.GetOwinContext().GetUserManager<ApplicationSignInManager>();
            var user = new ApplicationUser() { UserName = email.Text, Email = email.Text };
            IdentityResult result = manager.Create(user);
            if (result.Succeeded)
            {
                var loginInfo = Context.GetOwinContext().Authentication.GetExternalLoginInfo();
                if (loginInfo == null)
                {
                    RedirectOnFail();
                    return;
                }
                result = manager.AddLogin(user.Id, loginInfo.Login);
                if (result.Succeeded)
                {
                    signInManager.SignIn(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // var code = manager.GenerateEmailConfirmationToken(user.Id);
                    // Send this link via email: IdentityHelper.GetUserConfirmationRedirectUrl(code, user.Id)

                    IdentityHelper.RedirectToReturnUrl(Request.QueryString["ReturnUrl"], Response);
                    return;
                }
            }
            AddErrors(result);
        }

        private void AddErrors(IdentityResult result) 
        {
            foreach (var error in result.Errors) 
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}
```

**Comment by ameenurrahman36** [comment]
It's working thanks for your support.
