### ISSUE TITLE
IDX21323: RequireNonce is 'System.Boolean'. OpenIdConnectProtocolValidationContext.Nonce was null

### ISSUE THREAD

**Issue by SpeakOutLoud** [aspnet/AspNetKatana#383]
Hi hello,

Currently I am facing the open id error IDX21323 where Nonce is null, and I am unable to continue forward!
Currently the project is on net framework 4.7.2 while I have tried SameSiteCookieManager as cookie manager in OpenIdConnect and even used app.UseKentorOwinCookieSaver(); on Startup.cs, sometimes the nonce is found and sometimes not.

I have read that this is a Katana bug, and have yet not found any solutions to this problem. 

Please guide me forward on this bug!
Thank you!

**Comment by Tratcher** [comment]
Please share your Startup code and a fiddler trace showing the issue.

Remove UseKentorOwinCookieSaver, SameSiteCookieManager should be adequate.
