### ISSUE TITLE
Handling of the "state" parameter value seems to be inconsistent (OpenID Connect)

### ISSUE THREAD

**Issue by sgryt** [aspnet/AspNetKatana#384]
When constructing the URL where the browser is redirected to for authentication, the `state` value is URL-encoded. Example (omitting the part of the value after the URL-encoded `=` character) : 
  `state=OpenIdConnect.AuthenticationProperties%3D...`

But when the response comes back with the exact same `state` value, the middleware rejects the response, because `OpenidConnectAuthenticationHandler.GetPropertiesFromState` (see https://github.com/aspnet/AspNetKatana/blob/2c68ecff843266b852328e07626a97450b19d27a/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L814) returns null. The comment at the top of this function implementation, (and the implementation itself) assumes that the `state` value passed in has been URL-decoded (it looks explicitly for an `=` sign after the `OpenIdConnectAuthenticationDefaults.AuthenticationPropertiesKey` string constant.

But the OAuth2 specification explicitly requires that any state value received must be passed back unmodified (https://tools.ietf.org/html/rfc6749#section-4.1.2).
Perhaps I have misread the spec, and please correct me if I have - but if not, then it seems that the OWIN middleware must do the decoding itself, if it sends encoded values ? (since the OpenID Provider is not permitted to do any changes to the value whatsoever).

**Comment by Tratcher** [comment]
Have you seen a request rejected for this reason, or are you reading code and anticipating an issue? 

If you have a repro, please share a fiddler trace with the whole request and the library versions used.

I tested the basic flow last week and it was working. Note in the default flow the state is returned in a form post field and unescaped when parsing the form.

**Comment by sgryt** [comment]
Hi @Tratcher I have just helped a customer troubleshoot this. They use Sitecore (v 9.3) towards my company's OpenID Provider service.

**Comment by sgryt** [comment]
Here is a Fiddler trace:


[Sitecore-and-Criipto-Verify.zip](https://github.com/aspnet/AspNetKatana/files/5224423/Sitecore-and-Criipto-Verify.zip)

**Comment by sgryt** [comment]
Flow starts in session #39 (the Location header has a state value which is URL encoded), and session #41 is the request to our service.

The response is in session #68 (based on an auto-submitting form returned in session #66).

**Comment by sgryt** [comment]
They tried with both Microsoft.Owin.Security.OpenIdConnect.dll with FileVersion 4.0.4677.103 and the most recent version of the codebase from GitHub. Both behave the same.

**Comment by sgryt** [comment]
I should add that they also tried debugging this (hooked into the MessageReceived event), where it was clear that the `state` value was the same as sent in session #39. 

The following workaround in the MessageReceived event made `OpenidConnectAuthenticationHandler.GetPropertiesFromState` accept the state value and proceed with a succesful login:

```
var prefix = "OpenIdConnect.AuthenticationProperties";
var encodedPrefix = prefix + "%3D";
if (!String.IsNullOrWhiteSpace(pm.ProtocolMessage.State) && pm.ProtocolMessage.StartsWith(encodedPrefix, StringComparison.OrdinalIgnoreCase))
{
    pm.ProtocolMessage.State =  prefix + "=" + pm.ProtocolMessage.State.Substring(encodedPrefix.Length);
}
```

**Comment by Tratcher** [comment]
I replayed back the request with fiddler and see that the state arrives double escaped:
```
OpenIdConnect.AuthenticationProperties%253DcSO0vHYCD3hLLuMY9t-kvibruMCsOtYT5CQwHDV1QhmW0TfVgQ2Jis22kVnjJK4f5lgzt1kxKWaZBFYhXH552IvTx387kka2hVEdFmCkenAfNzC72Kebc4eaK3_pLmJJsw3_iy9wnF4RKIhU31Q2tqJjrEq5OwmA4X6nDQ26bGuyQFH80HojwQvtluL99MCFa4SoShspl8u05gPyA-s5o2cYp4LriVaP_TyPhZq4fe7-T7Lq3rDuf1q8awTanb0orMPsce5Y4n5tHzJARItEMV8Hg9hO6GYVkxvTKnHMw1T4qm_FF3b0oPDV62pg2C1EISPyaSG7w39dMcjHn5Ya1r3zF9ppZ1sF1_CK8VU8E0oLuN5K81QLrcCAt0tlafV9MCVvJ3n6cOVw7pGNToSiQQ
```
Note the `%253D`. When the form parser un-escapes it the result is `%3D`. I see the same thing if I look in the raw request view in Fiddler. This indicates a client bug when composing the form, it shouldn't need to escape the value as it's already escaped.

**Comment by sgryt** [comment]
If you look at the raw response (not using composer) in session #66, the state is not doubly encoded:

```
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Getting there...</title>
    <script defer type="text/javascript" src="/Scripts/wsFedSubmit.js"></script>
</head>
<body>
    <form action="https://dev.local.alka-dk/api/authenticate/nemidloginpartner" method="post" name="hiddenform">
            <input name="id_token" value="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjQ3QjI0NkQ3RjU0OTJDQjlGQ0U0QjE0MUREODFGNDg1M0I4MDgwOTQifQ.eyJpc3MiOiJodHRwczovL25lbWlkLXRlc3QuYWxrYS5kayIsImF1ZCI6InVybjphbGthOmRldjo1MDUwIiwibm9uY2UiOiI2MzczNTY4NTU3NDE2MTA1MjguTldJek5qWTNOVGt0WkdVNU1pMDBPVEJoTFdFd1lUTXRaV0ZrTXpsbU5HRm1ZalEyTVRoaE5EYzJNRFF0TWpnM055MDBaR1U0TFRnMlltWXRZMlZtTmpCbE5URXhZMll4IiwiaWRlbnRpdHlzY2hlbWUiOiJka25lbWlkIiwiYXV0aGVudGljYXRpb250eXBlIjoidXJuOmdybjphdXRobjpkazpuZW1pZDpwb2NlcyIsImF1dGhlbnRpY2F0aW9ubWV0aG9kIjoidXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFjOmNsYXNzZXM6U29mdHdhcmVQS0kiLCJhdXRoZW50aWNhdGlvbmluc3RhbnQiOiIyMDIwLTA5LTE0VDEzOjA2OjQ2LjU3MloiLCJuYW1laWRlbnRpZmllciI6ImI1ZTgzZjJjNDNjMzQ1YzJhMjJiZmZjYTNiOTUyNjI3Iiwic3ViIjoie2I1ZTgzZjJjLTQzYzMtNDVjMi1hMjJiLWZmY2EzYjk1MjYyN30iLCJzZXNzaW9uaW5kZXgiOiI0NWY4YmUyYy1jYjc2LTRkMTYtODFkNi04MDQwYmRiNzhlOWQiLCJwaWROdW1iZXJJZGVudGlmaWVyIjoiOTIwOC0yMDAyLTItNDQ3NDIzODU4MzUwIiwiaXNZb3V0aENlcnQiOiJmYWxzZSIsImNwck51bWJlcklkZW50aWZpZXIiOiIwNTAzNjQyNTU3IiwibmFtZSI6IkJvIEhlc3NuZXIiLCJjb3VudHJ5IjoiREsiLCIyLjUuNC41LjEiOiJQSUQ6OTIwOC0yMDAyLTItNDQ3NDIzODU4MzUwIiwiMi41LjQuNSI6IjVDRTg4MjQ4IiwiMi41LjI5LjI5IjoiQ049VFJVU1QyNDA4IFN5c3RlbXRlc3QgWFhYSVYgQ0EsIE89VFJVU1QyNDA4LCBDPURLIiwiaWF0IjoxNjAwMDg4ODA2LCJuYmYiOjE2MDAwODg4MDYsImV4cCI6MTYwMDA5MDAwNn0.NiygLdW4s61PQ8ofMzjslZFfQd2092tvLsXiZV3-ESyoDm0By-OTs5t2NuQXrLWhQ7Gvjs_txl-lS01xQBF7OvZ220VyvuZzjPORnox6zSQecK9mNowa9c-NZG6Jd2Z8xhFJy7oRBTw0xDip1jzaT_TlWbB7D8nNDge5V0DGjQ3nbCV5bNKjgdeIuiesNtEuZ7PtxblwCCvZF4MMQq1zr1Xk_sWsfXwujicA_VDh-I3ax_nGD9bYJhgjZ9r9PQtogzoFJ1vPMqYMThWyp4RBKS3RKEfdcmrCfPZGF8OG-U_kUUTk2ZSRWsLI3vngaM9PcJ9EGYhwHmN02o22CYeXOA" type="hidden" />
    <input name="state" value="OpenIdConnect.AuthenticationProperties%3DcSO0vHYCD3hLLuMY9t-kvibruMCsOtYT5CQwHDV1QhmW0TfVgQ2Jis22kVnjJK4f5lgzt1kxKWaZBFYhXH552IvTx387kka2hVEdFmCkenAfNzC72Kebc4eaK3_pLmJJsw3_iy9wnF4RKIhU31Q2tqJjrEq5OwmA4X6nDQ26bGuyQFH80HojwQvtluL99MCFa4SoShspl8u05gPyA-s5o2cYp4LriVaP_TyPhZq4fe7-T7Lq3rDuf1q8awTanb0orMPsce5Y4n5tHzJARItEMV8Hg9hO6GYVkxvTKnHMw1T4qm_FF3b0oPDV62pg2C1EISPyaSG7w39dMcjHn5Ya1r3zF9ppZ1sF1_CK8VU8E0oLuN5K81QLrcCAt0tlafV9MCVvJ3n6cOVw7pGNToSiQQ" type="hidden" />

    </form>
</body>
</html>
```

I am not entirely sure what to make of this ?

**Comment by Tratcher** [comment]
When I ran my working scenario in Firefox and looked at the raw output this is what I see:
```
<input type='hidden' name='state' value='OpenIdConnect.AuthenticationProperties=7e-y8DMeci9GXqx4X-MWnzc6fsAvbjywifsPVEbVlfjm9wBoaNQzfOqZGVfvOS1SHJQf6EeBRayQsGojiFexmlDVzKaNAgPdgtRieiiqWJoH6svOmUJNeh72vF3SH2d69Tcx7awWNplvubZ77kUsCpKgY9fD53idzyZErhkIzLtdvc68VYj7UBFI1sSDc4n45P1B7Zdt6B7OJslSd_FuQw' />
```
The html form value is in its decoded state, presumably because the browser is going to encode it on submission. So in your example the issue is with the identity provider over-escaping that value when generating the HTML form. More precisely, the flow is like this:
1. State is url encoded in the query string to the idp.
1. the idp (should) url decode the state query string parameter 
1. the idp generates an html form containing state value, which should be url decoded.
1. the browser submits the form and url encodes the values
1. the app server parses the form and url decodes the values

Yours is breaking down on step 2 or 3.

**Comment by sgryt** [comment]
If the client sends a url encoded value to the OP (step 1.), shouldn't it expect to get back exactly the same value no matter how the app server may pre-process the response (step 5.) from the OP ?

**Comment by Tratcher** [comment]
> If the client sends a url encoded value to the OP (step 1.), shouldn't it expect to get back exactly the same value no matter how the app server may pre-process the response (step 5.) from the OP ?

The field passes through several different representations along the way (query, html form, form post) and they each have their own mechanics, values aren't just passed through as-is. The important thing is that the underlying value round trip correctly.

**Comment by sgryt** [comment]
`The underlying value` - I assume that you mean the exact value that the middleware generates in-memory before putting in on the wire? Which in this case is `OpenIdConnect.AuthenticationProperties%3D...` ?

And shouldn't it then expect to have that exact same value back in-memory, regardless of which representations, user-agents and web-server-technologies it passes through along the way?

**Comment by Tratcher** [comment]
Right, but it looks like the identity provider is messing that up when generating the html form. At least you have a workaround. 

One alternate workaround you may try is switching to ResponseMode=query, but that will require using ResponseType=code and a client secret.
https://github.com/aspnet/AspNetKatana/blob/7aa465d56878b43409a603cf5384e7614cc35e19/tests/Katana.Sandbox.WebServer/Startup.cs#L146-L153

As I said, this works fine with other providers. It's probably a corner case for your provider due to how we chose to structure the content of the state field. I'm happy to say this has improved in the AspNetCore version simply by using a different format for the state field.
