### ISSUE TITLE
这个如何支持.net core 吗   以前用.net framework4.6写得OAuth2.0 AuthorizeCode第三方认证，现在如何使用？？

### ISSUE THREAD

**Issue by wyz629871** [aspnet/AspNetKatana#391]

**Comment by Tratcher** [comment]
These libraries have all been replaced on ASP.NET Core. See the new [OAuthHandler](https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/OAuth/src/OAuthHandler.cs) base class.

See also https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers for many pre-written third-party providers.
