### ISSUE TITLE
Sign out by Azure AD doesn't work correctly in Chrome.

### ISSUE THREAD

**Issue by SeminDM** [aspnet/AspNetKatana#396]
Hello!
I use OWIN and Azure AD for authentication in my app. 
Code is quite usual and simple but if need I can expose it.
Problem is beginning here:

    // doesn't work in Chrome but works in Edge
    private const string AzureADOAuth2EndPoint_1 = "https://login.microsoftonline.com/{0}/v2.0";
    // works correctly both in Chrome and Edge
    private const string AzureADOAuth2EndPoint_2 = "https://login.microsoftonline.com/{0}";
    var endpoint = string.Format(System.Globalization.CultureInfo.InvariantCulture, AzureADOAuth2EndPoint, authority);
    
Logout doesn't work correctly with **v2.0** endpoint: Azure AD vanishes cookies, redirects to specified PostLogoutURI, but Microsoft logout page remains.

![image](https://user-images.githubusercontent.com/23192926/107388093-84fbc380-6b06-11eb-8fa2-17f10fbe6fce.png)

Azure AD redirects to \Home\AzureADPostLogout correctly but result of the next redirect to \Home\Login is not rendered.
![image](https://user-images.githubusercontent.com/23192926/107389165-9abdb880-6b07-11eb-8b0b-1e917090cdbc.png)

I suggest that problem is related to SameSite cookie flag but I configured chrome://flags/#same-site-by-default-cookies as Disabled and it doesn't help.

What does mean v2.0 and why it breaks logout?
Thank you!

**Comment by Tratcher** [comment]
Can you share the fiddler trace files for both scenarios?

**Comment by SeminDM** [comment]
It is fiddler trace for logout from Edge
![image](https://user-images.githubusercontent.com/23192926/107402346-e62a9380-6b14-11eb-86d4-c0c31338f824.png)

**Comment by Tratcher** [comment]
Please export and share the trace files, the screen shots don't have the details I need to see.

**Comment by SeminDM** [comment]
[trace.zip](https://github.com/aspnet/AspNetKatana/files/5953201/trace.zip)

**Comment by SeminDM** [comment]
@Tratcher let me know if you need additional information or other trace files.

**Comment by SeminDM** [comment]
@Tratcher I encountered this problem on portal.azure.com. If I try to sign out from this portal then I see "sign-out" page with address: https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=https%3A%2F%2Fportal.azure.com%3A443%2F&client_id=c44b4083...53cbdf3c&redirect_uri=https%3A%2F%2Fportal.azure.com%2Fsignin%2Findex%2F&site_id=501430&prompt=select_account&client-request-id=2e6505d9-ce54-4aac-9f59-95743b5aed04&x-client-SKU=ID_NET45&x-client-ver=5.3.0.0

It seems problem in AzureAD but not in the OWIN.

**Comment by Tratcher** [comment]
That makes sense. I didn't find anything obvious when I looked at the traces. I'll close this until we find out otherwise.
