### ISSUE TITLE
How to perform sign-out from Google using OWIN?

### ISSUE THREAD

**Issue by SeminDM** [aspnet/AspNetKatana#402]
Hello!
I try to support authentication by Google in my app.

First time I called [GoogleOAuth2AuthenticationMiddleware ](https://github.com/aspnet/AspNetKatana/blob/78c8866a16d781446d2a9eac949bf737847564da/src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationMiddleware.cs#L22) but [GoogleOAuth2AuthenticationHandler](https://github.com/aspnet/AspNetKatana/blob/78c8866a16d781446d2a9eac949bf737847564da/src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationHandler.cs#L18) doesn't override parent method which performs sign-out.

I try to use [OpenIdConnectAuthenticationMiddleware](https://github.com/aspnet/AspNetKatana/blob/78c8866a16d781446d2a9eac949bf737847564da/src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs#L20). Sign-in works fine but sign-out doesn't work.
Configuration manager doesn't set [EndSessionEndpoint](https://github.com/aspnet/AspNetKatana/blob/78c8866a16d781446d2a9eac949bf737847564da/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L82) property for `OpenIdConnectConfiguration` and therefore [redirectUri ](https://github.com/aspnet/AspNetKatana/blob/78c8866a16d781446d2a9eac949bf737847564da/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L107) has no host.

1. Why `GoogleOAuth2AuthenticationMiddleware` doesn't support sign-out. OpenId Connect supports logout, doesn't it?
2. I could set `EndSessionEndpoint` manually but I don't know right value. Could you advise `EndSessionEndpoint` for Google?

Thank you!

**Comment by Tratcher** [comment]
The OAuth2 spec doesn't define a sign-out mechanism, that was first included in the OpenIdConnect spec. 

Looking at google's OIDC [docs](https://developers.google.com/identity/protocols/oauth2/openid-connect#discovery) there's no mention of them supporting the OIDC signout flow.

I see you're doing a lot of development with the Microsoft.Owin libraries lately. Have you looked at using ASP.NET Core instead? That's recommended for new development.

**Comment by SeminDM** [comment]
Is it mean if I want to support SSO and SLO by Google I have to use "not-OIDC" library?

I work on big monolith application which use Asp.net MVC5. We plan to migrate Asp.net Core in the future.

**Comment by Tratcher** [comment]
That's a question for Google, but I don't see any indication they support SLO on any protocol.

**Comment by SeminDM** [comment]
@Tratcher ok. Thank you very much for your help!
