### ISSUE TITLE
Microsoft.IdentityModel.Tokens 5.3 ASP.NET MVC The referenced assembly could not be found

### ISSUE THREAD

**Issue by hannespreishuber** [aspnet/AspNetKatana#407]
after update packages today.

Serverfehler in der Anwendung /.
Die Datei oder Assembly "Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
Beschreibung: Unbehandelte Ausnahme beim Ausführen der aktuellen Webanforderung. Überprüfen Sie die Stapelüberwachung, um weitere Informationen über diesen Fehler anzuzeigen und festzustellen, wo der Fehler im Code verursacht wurde.

Ausnahmedetails: System.IO.FileLoadException: Die Datei oder Assembly "Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)

Quellfehler:

Zeile 90: 
Zeile 91: 
Zeile 92:         }
Zeile 93: 
Zeile 94:       

Quelldatei: C:\GraphMVC\AppModelv2-WebApp-OpenIDConnect-DotNet\Startup.cs    Zeile: 92

Überwachung beim Laden der Assembly: Mit folgenden Informationen kann bestimmt werden, warum die Assembly Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 nicht geladen werden konnte.

=== Zustandsinformationen vor Bindung ===
LOG: DisplayName = Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/GraphMVC/AppModelv2-WebApp-OpenIDConnect-DotNet/
LOG: Ursprünglicher PrivatePath = C:\GraphMVC\AppModelv2-WebApp-OpenIDConnect-DotNet\bin
Aufruf von Assembly : Microsoft.Owin.Security.OpenIdConnect, Version=4.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: Diese Bindung startet im default-Load-Kontext.
LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\GraphMVC\AppModelv2-WebApp-OpenIDConnect-DotNet\web.config
LOG: Die Hostkonfigurationsdatei wird verwendet: C:\Users\hanne\Documents\IISExpress\config\aspnet.config
LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config wird verwendet.
LOG: Verweis nach der Richtlinie: Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Download von neuem URL file:///C:/Users/hanne/AppData/Local/Temp/Temporary ASP.NET Files/vs/b79820a9/df74fed8/Microsoft.IdentityModel.Tokens.DLL.
LOG: Download von neuem URL file:///C:/Users/hanne/AppData/Local/Temp/Temporary ASP.NET Files/vs/b79820a9/df74fed8/Microsoft.IdentityModel.Tokens/Microsoft.IdentityModel.Tokens.DLL.
LOG: Download von neuem URL file:///C:/GraphMVC/AppModelv2-WebApp-OpenIDConnect-DotNet/bin/Microsoft.IdentityModel.Tokens.DLL.
WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Hauptversion.
ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.

Stapelüberwachung:

[FileLoadException: Die Datei oder Assembly "Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)]
   AppModelv2_WebApp_OpenIDConnect_DotNet.Startup.Configuration(IAppBuilder app) in C:\GraphMVC\AppModelv2-WebApp-OpenIDConnect-DotNet\Startup.cs:92

[TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +168
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +105
   Owin.Loader.<>c__DisplayClass19_1.<MakeDelegate>b__0(IAppBuilder builder) +66
   Owin.Loader.<>c__DisplayClass9_0.<LoadImplementation>b__0(IAppBuilder builder) +123
   Microsoft.Owin.Host.SystemWeb.<>c__DisplayClass5_0.<InitializeBlueprint>b__0(IAppBuilder builder) +81
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +462
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +40
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +70
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +119
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +106
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +523
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +176
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +220
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +303

[HttpException (0x80004005): Ein Aufrufziel hat einen Ausnahmefehler verursacht.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +658
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +189

Versionsinformationen: Microsoft .NET Framework-Version:4.0.30319; ASP.NET-Version:4.8.4330.0

**Comment by Tratcher** [comment]
Please share your full dependency list from the packages.config file.
