### ISSUE TITLE
Getting infinite loop when trying to authenticate against Oracle Identity Cloud Service

### ISSUE THREAD

**Issue by RaduAlexe** [aspnet/AspNetKatana#408]
Hi,
I’m trying to authenticate against the Oracle Identity Cloud Service.

Currently using version 4.0.1 (also tried with version 4.1.1) but getting the same behavior.

The AuthenticateCoreAsync method is called correctly but the AuthenticationProperties object is null thus getting the "The state field is missing or invalid." Error and begging redirected to the login page.

Parsing the GetPropertiesFromState method I’ve noticed that the “status” value present in the Form object has not been URL Decoded (which is the case when authenticating against Azure AD for example.). If I intercept the value from the Form array and URL decoded it and then update the value, the logic works correctly.

Any help with this would be appreciated or if anybody was already able to authenticate using the Oracle solution.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/AspNetKatana/issues/288

**Comment by RaduAlexe** [comment]
Thank you @Tratcher
