### ISSUE TITLE
Increase Request Size?

### ISSUE THREAD

**Issue by Thypari** [aspnet/AspNetKatana#410]
I have the exact same issue as described here: https://forums.asp.net/t/2083605.aspx?+413+Request+Entity+Too+Large+in+ASP+Net+Web+Api+OWIN+self+host+service

Is there a way to increase the request size for Owin self-hosted?

The mentioned solution uses the nuget packages LimitsMiddleware and LimitsMiddleware.OwinAppBuilder which are both deprecated.

**Comment by Tratcher** [comment]
Microsoft.Owin does not implement request size limits. Are you hitting a limit in WebAPI? https://github.com/aspnet/AspNetwebstack
