### ISSUE TITLE
Correlate OWIN Requests with Windows Event Logs

### ISSUE THREAD

**Issue by shubham1172** [aspnet/AspNetKatana#417]
Hi,

We want to track TLS usage across our self-hosted app, like #387, and there was a suggestion to use SCHANNEL logging  https://stackoverflow.com/a/25090724. I can see the logs in Windows Event Viewer after turning on SCHANNEL information logs:
![image](https://user-images.githubusercontent.com/22132944/119804284-d4bb9a80-befd-11eb-98fb-a67433ad03b2.png)

How can I correlate this log with an OWIN request? There is a correlation ID in the Event Viewer, but how can one use that in OWIN?

**Comment by Tratcher** [comment]
I think you would need to enable ETW for Http.Sys to correlate TLS and HTTP data.
