### ISSUE TITLE
Does this library support code flow and JWT based authentication instead of client secret?

### ISSUE THREAD

**Issue by amitt0488** [aspnet/AspNetKatana#421]
Can we send signed request through this library?

**Comment by Tratcher** [comment]
Are you talking about the OpenIdConnect provider? It requires a client secret for doing code redemption. However, you can hook into the AuthorizationCodeReceived notification and redeem the code yourself.
https://github.com/aspnet/AspNetKatana/blob/fae38fae683bb0977bcaf7c3ffce244aced82135/src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationNotifications.cs#L38
