### ISSUE TITLE
Determine TLS version clients are using on a Webapi service using OWIN

### ISSUE THREAD

**Issue by AtulBhartia** [aspnet/AspNetKatana#427]
Our WebAPI services are using OWIN stack. We need to determine which clients are not using TLS 1.2
Is there a way to get TLS version on the server side?

**Comment by Tratcher** [comment]
Are you hosting on HttpListener or IIS? That information isn't accessible on HttpListener. From IIS it's available through server variables.

We recommend moving to ASP.NET Core where this information is accessible.

**Comment by AtulBhartia** [comment]
Thanks Tratcher for your reply. The service is hosted in httpsys and uses OwinHttpListener.
Is it possible to get the tls info via HttpListenerRequest?

**Comment by Tratcher** [comment]
> Is it possible to get the tls info via HttpListenerRequest?

No, there's no API for that.
