### ISSUE TITLE
Crash within WebApp.Start(), no cleanup

### ISSUE THREAD

**Issue by mjnovice** [aspnet/AspNetKatana#433]
We are observing an issue where there is a crash within `WebApp.Start(startoptions StartOptions)`.

Upon taking a process dump we see the object persists in the memory. We also observe an `System.Net.HttpListener` object with `IsListening` attribute as `true` but upon doing a `netstat` for that port we do not see anything. 
![image](https://user-images.githubusercontent.com/3083824/139503453-5870ce47-b051-4203-b94c-bf08b8ee5646.png)
Can this happen ? If yes, what could be the reason for this happening ? Please let me know if I missed anything.

**Comment by Tratcher** [comment]
Is there an exception and stacktrace?
