### ISSUE TITLE
OpenIDConnect Authorization Code Flow - redeems token on IIS express but not local IIS - C# asp.net

### ISSUE THREAD

**Issue by cjmak** [aspnet/AspNetKatana#438]
relates to this issue on SO:
https://stackoverflow.com/questions/70813536/why-is-the-authorization-code-not-automatically-redeeming-automatic-code-rede

It's possible I have something misconfigured but I find that with IIS Express OWIN attempts to redeem the token.  With Local IIS it doesn't.  I guess this could be an issue with IIS but i'm not sure where to look.

Any thoughts?

**Comment by Tratcher** [comment]
Answered on SO.
