### ISSUE TITLE
Wiki entry Selfhosting has links to branch that does not exist (or is not accessible)

### ISSUE THREAD

**Issue by CZEMacLeod** [aspnet/AspNetKatana#446]
A recent edit of the page [Selfhosting](https://github.com/aspnet/AspNetKatana/wiki/Selfhosting) included a change to point to the source page and readme file of the `Microsoft.Owin.SelfHost` package.
However, it points at the `dev` branch which does not exist (at least is not publicly accessible).
I think it needs to point to https://github.com/aspnet/AspNetKatana/tree/main/src/Microsoft.Owin.SelfHost instead.

**Comment by Tratcher** [comment]
The dev branch was recently removed. I've fixed the link, thanks.
