### ISSUE TITLE
Microsoft.Owin.fr and Microsoft.Owin.Security.fr not updated

### ISSUE THREAD

**Issue by nelero** [aspnet/AspNetKatana#471]
Hi,
when upgrading Microsoft.Owin.* from 4.2.0 to 4.2.2, i'm facing an issue with dependencies.
Microsoft.Owin.fr and Microsoft.Owin.Security.fr are in 4.2.0 and are not supporting Microsoft.Owin 4.2.2 version.

Could you upgrade requirements or localized packages on nuget to update Owin components to latest version ?
thanks

**Comment by faix** [comment]
@nelero see #453 language packs are no longer generated.
