### ISSUE TITLE
SignInAsAuthenticationType option gets ignored in OpenIdConnect middleware

### ISSUE THREAD

**Issue by eggersa** [aspnet/AspNetKatana#472]
The OpenIdConnectAuthenticationOptions.SignInAsAuthenticationType property is being ignored by the OpenIdConnect middleware. In fact, its definied but not referenced anywhere in the Microsoft.Owin.Security.OpenIdConnect project. Inside the MicrosoftAccountAuthenticationHandler for example, a new ClaimsIdentity (signInIdentity) gets generated if the mentioned option is set like so:

```C#
// Inside MicrosoftAccountAuthenticationHandler.InvokeReturnPathAsync() method
if (context.SignInAsAuthenticationType != null && context.Identity != null)
{
    ClaimsIdentity signInIdentity = context.Identity;
    if (!string.Equals(signInIdentity.AuthenticationType, context.SignInAsAuthenticationType, StringComparison.Ordinal))
    {
        signInIdentity = new ClaimsIdentity(signInIdentity.Claims, context.SignInAsAuthenticationType, signInIdentity.NameClaimType, signInIdentity.RoleClaimType);
    }
    Context.Authentication.SignIn(context.Properties, signInIdentity);
}
```

Whereas inside the OpenIdConnectAuthenticationHandler this logic is missing and the tickets Identity gets directly applied for the SignIn call:

```C#
// Inside OpenIdConnectAuthenticationHandler.InvokeReplyPathAsync()
if (ticket.Identity != null)
{
    Request.Context.Authentication.SignIn(ticket.Properties, ticket.Identity);
}
```

**Comment by Tratcher** [comment]
It's passed through to TokenValidationParamters here:
https://github.com/aspnet/AspNetKatana/blob/e55f48be5352469eaf116ba376806855ed9cf4be/src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs#L250

The ClaimsIdentity is generated by a lower level library that uses this.

**Comment by eggersa** [comment]
Thank you. Seems I overlooked the actual getters and setters. My bad.
