### ISSUE TITLE
How does the OwinHost.SystemWeb  regiester it's module and handler ?

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetKatana#473]
when use Owin , there no configuration in web.config,  but how it regiester the `OwinHttpModule` and `OwinHttpHandler` ?

**Comment by CZEMacLeod** [comment]
See https://github.com/aspnet/AspNetKatana/blob/main/src/Microsoft.Owin.Host.SystemWeb/PreApplicationStart.cs
Basically, the assembly has a `PreApplicationStartMethod` attribute defined that causes the IIS dotnet hosting runtime to execute the Initialize function which then registers the `OwinHttpModule`. I don't think the handler is registered as such - it is just setup as a route handler, same as MVC etc. based on the paths you map when you setup your owin app.

**Comment by John0King** [comment]
Thanks ,  I figured out the `httpmodule` registeration ,   but there is also a  `OwinHttpHandler.cs`  , and how it work  or does it work at all ?

**Comment by Tratcher** [comment]
The handler is only used when manually registered.
https://github.com/aspnet/AspNetKatana/blob/dbe159e43e2eee44f315f26268943e8ab5a4f60d/src/Microsoft.Owin.Host.SystemWeb/RouteCollectionExtensions.cs#L112-L117
https://github.com/aspnet/AspNetKatana/blob/dbe159e43e2eee44f315f26268943e8ab5a4f60d/src/Microsoft.Owin.Host.SystemWeb/OwinRouteHandler.cs#L62-L64

**Comment by John0King** [comment]
Thanks @Tratcher 

Does that means the `OwinRouteHandler`  is not been used normally (now all owin stuff  handled by the `OwinHttpModule`)?  

and Maybe it too late for the `System.Web`  stuff.   but   I think  we should add  a doc/wiki about how owin  `startup`  ,  

currently  the doc only have a very short word about the `startup`  ,  https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-middleware-in-the-iis-integrated-pipeline#how-owin-middleware-executes-in-the-iis-integrated-pipeline  


> In the IIS integrated pipeline the request pipeline consists of [HttpModules](https://msdn.microsoft.com/library/ms178468(v=vs.85).aspx) subscribed to a pre-defined set of the pipeline events such as [BeginRequest](https://msdn.microsoft.com/library/system.web.httpapplication.beginrequest.aspx), [AuthenticateRequest](https://msdn.microsoft.com/library/system.web.httpapplication.authenticaterequest.aspx), [AuthorizeRequest](https://msdn.microsoft.com/library/system.web.httpapplication.authorizerequest.aspx), etc.

but not mention  why there no httpmodule register without the web.config
