### ISSUE TITLE
Keeps redirecting to login page

### ISSUE THREAD

**Issue by tech-thanoshotels** [aspnet/AspNetKatana#482]
I am using asp.net 4.8 and in the production environment sometime the login does not work. As soon as I recycle the app pool then users can login. 

I have updated via nuget to version 4.2.2 and other projects running version 4.2.0 does not seem to have the problem. Any ideas ?

**Comment by Tratcher** [comment]
Can you share a Fiddler trace?

Check:
https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues

**Comment by tech-thanoshotels** [comment]
We have tried several things, from generating a unique machine key to changing versions of the below to the latest and to previous versions but no option worked. Please also find attached a fiddler trace. If you see in the trace the user trying to login to the https://hr.thanoshotels-apps.com/Login page and entered correctly his credentials. The system authenticated him (see below my code for doing that) and I also have a record saved to verify that the authentication was successful but for some reason he was treated as not authenticated and returned to login page.

***@***.***



***@***.***

Code to authenticate user (used the same as the standard asp.net project creation using identity) see below

***@***.***

Also in the login page I have this code which if the user is indeed authenticated it rectirects them to correct page.

***@***.***


Kindly let us know your thoughts on this.


Best regards,

Ioannis Ioannou
Software Engineering Manager

**Comment by Tratcher** [comment]
Most of that didn't come through, including the attachment. You'll have to post them directly on github, or send it to the address in my profile.

**Comment by tech-thanoshotels** [comment]
Hi Chris,

Please see the fiddler export here [​Folder icon]  asp.net identity log<https://thanoshotels.sharepoint.com/:f:/s/tech/Eoz835RuRpNHvRPUkTWP_VABUhgB8Y187Ug5nuSlv6aL2w?e=OgobVr>

I am also including my previous email below




We have tried several things, from generating a unique machine key to changing versions of the below to the latest and to previous versions but no option worked. Please also find attached a fiddler trace. If you see in the trace the user trying to login to the https://hr.thanoshotels-apps.com/Login page and entered correctly his credentials. The system authenticated him (see below my code for doing that) and I also have a record saved to verify that the authentication was successful but for some reason he was treated as not authenticated and returned to login page.

***@***.***



***@***.***

Code to authenticate user (used the same as the standard asp.net project creation using identity) see below

***@***.***

Also in the login page I have this code which if the user is indeed authenticated it rectirects them to correct page.

***@***.***







Best regards,

Ioannis Ioannou
Software Engineering Manager

**Comment by Tratcher** [comment]
Your login response is not including any cookies, but it does include the cache headers that would normally be set with the cookies. Try the following workaround:
https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues

**Comment by tech-thanoshotels** [comment]
This refers though to asp.net core, we are using asp.net 4.8 web forms project or it does not matter ?
Also any ideas why it does happen randomly ? and why once I recycle the app pool then the logins works without issue

**Comment by Tratcher** [comment]
That writeup is about Katana and ASP.NET 4.8, not AspNetCore.

The issue can appear randomly because of conflicts with other cookies in the application.
