### ISSUE TITLE
Disposal of OwinContext.Request.User.Identity

### ISSUE THREAD

**Issue by letrec** [aspnet/AspNetKatana#49]
It would be nice to have OwinContext.Request.User.Identity disposed upon completion of each request. It was causing handle leak for me and for now I'm disposing it manually.

**Comment by Tratcher** [comment]
What kind of user was it? A WindowsIdentity?

Where did it come from? System.Web or HttpListener?

**Comment by letrec** [comment]
Yes, it was a WindowsIdentity one.
Yes, HttpListener.

**Comment by Tratcher** [comment]
If you let it run are they eventually collected when there's a big GC?

**Comment by letrec** [comment]
If running with server GC the process eventually runs out of handles.

**Comment by Tratcher** [comment]
This is an issue with the underlying HttpListener, it manages the identity and can cache it across requests on the same connection. This needs to be reported to https://connect.microsoft.com/VisualStudio or https://github.com/dotnet/corefx.
