### ISSUE TITLE
AspNetKatana is on .Net 4.5 framework which is out of support and developer pack not present to build the application

### ISSUE THREAD

**Issue by dibyenduk** [aspnet/AspNetKatana#491]
I am planning to create a pull request for AspNetKatana but the aspnetkatana main branch is on .Net 4.5 framework which is out of support. Developer pack for .Net 4.5 is not provided by Microsoft anymore to build the application. 
I tried to upgrade it to 4.8 but the build does not work properly as it is missing a lot of dlls.

**Comment by Tratcher** [comment]
I see you were able to submit your PR, did you get this targeting issue worked out?

We can't change the TFM without breaking the package graph for all 3rd party packages. I have the 4.5 targeting pack installed as part of VS 2019, but it still works in 2022.

https://learn.microsoft.com/en-us/answers/questions/993957/how-to-target-net-framework-4-0-in-vs-2022-on-wind

**Comment by dibyenduk** [comment]
@Tratcher - I was able to install visual studio 2019 with 4.0 and 4.5 target pack and then was able to build the application using build.cmd. Thanks for the help.
