### ISSUE TITLE
Form POST data is lost when the user is redirected to the Identity provider.

### ISSUE THREAD

**Issue by dibyenduk** [aspnet/AspNetKatana#493]
I am using the ws federation authentication middleware for passive federated authentication and facing below issue - 
When an user posts a form to our application and he / she is not authenticated, they are redirected to the Identity server for authentication. Once the authentication is completed, the browser redirects the user to the original application endpoint using a GET request. This loses all the form post values and also incorrectly changes the request to a GET rather than a POST.

I have created Pull request https://github.com/aspnet/AspNetKatana/pull/492 to add a pre redirect hook event to the pipeline so that the application can handle the redirect rather than it getting handled by the ws federation authentication handler.

Explanation - 
In the OnRedirectingtoIdentityprovider event, I check if it is a post request and save the form values in cache. Once the request returns from the Identity server, I hook into the preredirect hook event and rehydrate the request with the form values from cache and mark that I have handled the redirect by calling HandleRedirect function for the pre redirect hook. In the InvokeAsync function, the handler will check if the application has handled the redirect themselves and will not execute the code to redirect to the application using a GET request. I have tested this on my end and it works fine.

**Comment by Tratcher** [comment]
The user was previously authenticated to receive the form, correct? This is mainly about handling the race condition of their auth expiring between retrieval and submission?

Can you show a code sample of how you're use these events?

I think you can already do what you want by using the SecurityTokenValidated event.
https://github.com/aspnet/AspNetKatana/blob/00d999d5c8bd3e733d0417b87e22a2683f5ee93d/src/Microsoft.Owin.Security.WsFederation/WsFederationAuthenticationHandler.cs#L361
The only part you'd need to duplicate is
https://github.com/aspnet/AspNetKatana/blob/00d999d5c8bd3e733d0417b87e22a2683f5ee93d/src/Microsoft.Owin.Security.WsFederation/WsFederationAuthenticationHandler.cs#L192

**Comment by dibyenduk** [comment]
We use single sign on mechanism of ADFS / Azure for the authentication and it is possible to post values from one application to the other application. In that case, the user is not authenticated for the second application and hence they are redirected to the Identity server. When the redirection happens, all the values in form post are lost and the user is redirected after authentication to the url as a GET rather than a POST. Till the time the request reaches SecurityTokenValidated event, all the values are already lost so we save them on RedirectingToIdentityProvider event before it get redirected to the Identity server. Now even though the values are saved, wsfederationhandler invokeasync method will redirect to the original url as a GET rather than a POST.
Code explanation below -
1. On RedirectToIdentityProvider I save the form values -
`private Task RedirectToIdentityProvider(RedirectToIdentityProviderNotification<WsFederationMessage, WsFederationAuthenticationOptions> arg)
{
....
if (httpRequest.HttpMethod != HttpMethod.Post.ToString()) return Task.CompletedTask;
var requestId = HttpContext.Current.Items["RequestId"].ToString();
arg.ProtocolMessage.SetParameter("wctx", string.Concat(wctx, "&", CookieName, "=", requestId));
var formCollection = AuthRedirectionManager.GetFormValues(path, httpRequest);
AuthRedirectionManager.SaveState(requestId, formCollection);
}`

2. Once authentication is done and the request is returned back to the application, On SecurityTokenValidated I get the requestId from the wctx context (as I had appended it before in RedirectingToIdentityProvider) and push the value in AuthenticationTicket Property.

`private Task SecurityTokenValidated(SecurityTokenValidatedNotification<WsFederationMessage, WsFederationAuthenticationOptions> arg)
{
   var wctx = HttpContext.Current.Request.Params[WCTX];
   var requestId = AuthRedirectionManager.ExtractStateValue(wctx, CookieName);
   arg.AuthenticationTicket.Properties.Dictionary["RequestId"] = requestId; 
}`

3. In the WSFederation configuration, configure PreRedirectReceived as below 

`
var wsFederationOptions = new WsFederationAuthenticationOptions()
            {                
                Notifications = new WsFederationAuthenticationNotifications()
                {
                    RedirectToIdentityProvider =  RedirectToIdentityProvider                    
                    SecurityTokenValidated = SecurityTokenValidated,
                    PreRedirectReceived =  PreRedirectReceived , 
                },
}

private Task PreRedirectReceived(PreRedirectReceivedNotification<WsFederationMessage, WsFederationAuthenticationOptions> arg)
{
      // Get the request Id
       var requestId = authenticationTicket.Properties.Dictionary["RequestId"];

     // Get the stored form values for the request Id
       var data = AuthRedirectionManager.GetState(requestId);

      // Create a form to post with the values
       var html = AuthRedirectionManager.CreatePostForm(data);

     // Clean up the stored state
     AuthRedirectionManager.ResetState(requestId);
    
    // Write response
    HttpContext.Current.Response.Write(html);
    HttpContext.Current.Response.End();
    
    // Mark that I have handled the redirection and wsfederationhandler does not need to do it.
    arg.HandledRedirect(); 
}`

**Comment by Tratcher** [comment]
If you use HandleResponse() in SecurityTokenValidated then it will skip the redirect:
https://github.com/aspnet/AspNetKatana/blob/423f80e7f82708e3f78a596cf405a2a5595c12f1/src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L926-L933

**Comment by dibyenduk** [comment]
With HandledResponse, it will clear out the AuthenticatedTicket identity & properties and not even call Request.Context.Authentication.SignIn(ticket.Properties, ticket.Identity). 
```
private static AuthenticationTicket GetHandledResponseTicket()
        {
            return new AuthenticationTicket(null, new AuthenticationProperties(new Dictionary<string, string>() { { HandledResponse, "true" } }));
        }
```

Are you saying that we call the Request.SignIn() on SecurityTokenValidated and hence even if it does not call it in InvokeReplyPathAsync then it will work fine ?

**Comment by dibyenduk** [comment]
I changed the securitytokenvalidated as follows and it worked. Thanks for the help.

```
private Task SecurityTokenValidated(SecurityTokenValidatedNotification<WsFederationMessage, WsFederationAuthenticationOptions> arg)
{
......
......
                var html = AuthRedirectionManager.CreatePostForm(data);
                arg.OwinContext.Authentication.SignIn(arg.AuthenticationTicket.Properties, arg.AuthenticationTicket.Identity);
                arg.HandleResponse();
                HttpContext.Current.Response.Write(html);             
                return Task.CompletedTask;
}
```

**Comment by dibyenduk** [comment]
This issue can be closed as I found a workaround (mentioned above).
