### ISSUE TITLE
Question: Why does the 4.2.2 package specifically require .NET Framework 4.5?

### ISSUE THREAD

**Issue by Rhialto74** [aspnet/AspNetKatana#510]
I'm updating from the 4.1.1 version which has no specific Framework dependency and noticing that 4.2.2 specifies .NET Framework = 4.5.

**Comment by Tratcher** [comment]
That was only a packaging change as a result from updated infrastructure. .NET 4.5 has always been the minimum required version to run the binaries.

**Comment by Rhialto74** [comment]
Thanks
