### ISSUE TITLE
Strange behavior on port 50000 for Owin self hosting.... 

### ISSUE THREAD

**Issue by harperjohn** [aspnet/AspNetKatana#515]
This repo has two simple  test apps:  https://github.com/publicdotnet/selfHostTests

The dotnet framework 4.81 "Owin" version thinks that port 50000 is in use... and then the asp.net Dotnet 7 version runs fine....

The Owin version runs fine on some other ports... for example 1315....

Thoughts?

**Comment by harperjohn** [comment]
@Tratcher Did the "owin" example work without error for you?

**Comment by Tratcher** [comment]
Ah, I do see the same error. This post might explain why: https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows

**Comment by harperjohn** [comment]
Interesting @Tratcher !

PS C:\Users\john> netsh int ip show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
     50000       50059     *

* - Administered port exclusions.

**Comment by harperjohn** [comment]
Ok... So something is reserving those ports...

But now I am very very curious why the asp.net either does not "see" or does not "care" or just overrides the reservation for some reason...  (and it just just asp.net... the Hugo static site generator has a built in web server, and it gladly uses 50000)

**Comment by Tratcher** [comment]
In AspNetCore you're using the Kestrel server by default which runs in user mode with direct Sockets. In Owin self-host you're using HttpListener -> Http.Sys which runs in kernel mode. I don't know why the Http.Sys stack honors those reservations when Sockets don't, but that would explain why other apps your using don't care either.

**Comment by Tratcher** [comment]
Closing as answered.
