### ISSUE TITLE
Session in ASP.NET WebForm is cleared after authenticated by Entra ID with CookieAuthentication and WsFederationAuthentication

### ISSUE THREAD

**Issue by yooontheearth** [aspnet/AspNetKatana#518]
Hello,

I just figured out that Session is cleared right after redirecting back from authenticating by Entra ID with CookieAuthentication and WsFederationAuthentication when I use Global.asax together. Without Global.asax, there is no problem. Assembly version is 4.2.2.

I use Global.asax to enable Session for WebAPI request (Not in the example though), so it is not an option to remove it for Entra ID authentication. Do you have any ideas to make it work?

I am not sure to be ok to attach a sample here but I made a minimum working example, so I will be appreciated if you would take a look at the example.
[EntraIdAuthTest.zip](https://github.com/aspnet/AspNetKatana/files/13935745/EntraIdAuthTest.zip)

**How to reproduce**
On chrome incognito mode, navigate to Test2.aspx which sets Session["Test"] and redirects to Test1.aspx. Test1.aspx shows Session ID and Session["Test"] value. Then you navigate to Authentication.aspx which challenges to Entra ID and redirects back from there. At that time, Session ID is already different from the one at the Test1 shown.

**Comment by Tratcher** [comment]
@yooontheearth unfortunately this product is not under active development. We may consider PRs, but don't expect feature work or investigations at this point. I recommend StackOverflow for this class of question.

**Comment by yooontheearth** [comment]
@Tratcher thank you for letting me know about it. I'll ask at StackOverflow then.
