### ISSUE TITLE
Nuget Packages cannot be upgraded due to missing localizations

### ISSUE THREAD

**Issue by Suchiman** [aspnet/AspNetKatana#53]
Using a rather default setup of packages, you'll run into the error
```
Dependencies can not be resolved. "Microsoft.Owin 3.1.0 ' is not compatible with' Microsoft.Owin.de 3.0.1 Restriction: Microsoft.Owin (= 3.0.1) '.
```
When trying to upgrade to the v3.1.0 release with localizations installed.
Apparently the localizations aren't updated: https://www.nuget.org/packages/Microsoft.Owin.de/

**Comment by Tratcher** [comment]
Out of curiosity why are you using the localization packages? They only contain a few exception messages.

**Comment by Suchiman** [comment]
To be honest, they were added through the default web template, so i've kept them. Now they're failing the update but they are many (probably over 10) and removing them all manually is tedious and i'm not certain which effect it will have.

**Comment by EdoardoG** [comment]
I have the same problem with Italian localizations.

**Comment by muratg** [comment]
Localized packages are just uploaded to nuget.org.  Indexing can potentially take a little time, but if you still have issues later today, please let me know.

**Comment by EdoardoG** [comment]
Thank you very much
