### ISSUE TITLE
Is it possible to add WsFederationAuthenticationOptions at runtime?

### ISSUE THREAD

**Issue by wmmihaa** [aspnet/AspNetKatana#57]
I've been trying to add WsFederationAuthenticationOptions at runtime, letting site administrators adding trusts to external IP's.

````
app.Map("/Account", configuration =>
{
    var option= new WsFederationAuthenticationOptions
    {
        AuthenticationType = organizationModel.ADFS_Domain,
        MetadataAddress = organizationModel.ADFS_MetadataAddress,
        BackchannelCertificateValidator = null,
        Wtrealm = organizationModel.ADFS_Realm,
        Wreply = serveraddress + "/Account/ExternalLoginCallback/"+ wsFederationSetting.providerName,
    };

     configuration.UseWsFederationAuthentication(option);

});
````
But calling *HttpContext.GetOwinContext().Authentication.GetExternalAuthenticationTypes()* does not include the new option, hence the *owinCtx.Authentication.Challenge* will fail...

The code above is working from my startup class, but not at runtime. AndI don't want to have to restart the application just to add an Identity Provider...

**Comment by Tratcher** [comment]
No, that's not supported. Auth middleware are part of the app pipeline which is constructed once at startup. We've only just added a way to dynamically add auth providers in ASP.NET Core 2.0.0-preview1.

**Comment by wmmihaa** [comment]
Thanks @Tratcher. And there is no work around at all?

**Comment by Tratcher** [comment]
Nothing's impossible, but we haven't built anything to handle this scenario. You would need some custom middleware that let you shim in additional middleware at runtime.

**Comment by wmmihaa** [comment]
(Last question)
Do you know if there is a way to reload the context from the AppBuilder. I assume this is done automaticly after the Startup:Configuration method is called. I've tried calling the AppBuilder:Build method, but it has no effect on the context...
Thanks

**Comment by Tratcher** [comment]
I don't follow. Hosting takes the AppBuilder, calls build to create a request processing pipeline, and plugs that into the server. Calling AppBuilder.Build again produces a new pipeline, but it's not connected to the server.
