### ISSUE TITLE
Update facebook provider

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#6]
Facebook (Graph) API 2.4 made some breaking changes to their request formats and flow.
https://katanaproject.codeplex.com/workitem/417

**Comment by marsupialmouse** [comment]
Is there likely to be a release containing this fix soon? The change to the format of the access_token response happened in API v2.3 (from URL encoded in v2.2 to JSON in v2.3), and on 27 March v2.2 will be deprecated.
