### ISSUE TITLE
Getting Intermittent Invalid Redirect_uri while using MSA with AAD Convergence

### ISSUE THREAD

**Issue by Praveen-911** [aspnet/AspNetKatana#60]
On providing the userid (Live/Outlook/Hotmail) we are being redirected to 

https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application[.....]

which is basically error page.

On monitoring with fiddler we observe that in these cases the redirect_uri parameter is having space appended at the start.

GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=XXXXXXXXXXXXXXXXXXXX&redirect_uri=%e2%80%8e%e2%80%8ehttps%3a%2f%2flocalhost%2fAzureAD.TestWebClient&response_mode=form_post&[...]

This extra characters are getting added intermittently, while we are assigning this property in StartUp ,there is no space characters.

Please help in figuring out where these space characters are getting appended from, or redirect to relevant forums.

Thanks in advance

**Comment by Tratcher** [comment]
??? Those aren't spaces, those are non-printable control characters:
`U+200E	‎	e2 80 8e	LEFT-TO-RIGHT MARK`
http://utf8-chartable.de/unicode-utf8-table.pl?start=8192&number=128

How did you assign this in startup? It's a generated string: https://github.com/aspnet/AspNetKatana/blob/b850cd8b4de61e65bbd7127ce02b5df7c4cb6db5/src/Microsoft.Owin.Security.MicrosoftAccount/MicrosoftAccountAuthenticationHandler.cs#L233

**Comment by Praveen-911** [comment]
Hi Tracther ,

I am reading from config file 
 _redirectUri = ConfigurationHelper.GetStringValueFromConfig("XXXXXXX");

and assigning it under 
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                {

                    ClientId = _clientID.Trim(),
                    Authority = _authority.Trim(),
                    RedirectUri=_redirectUri.Trim(),


Please Note Same Application code works fine most of the time while sometime it throws this error.

Thanks,
Praveen

**Comment by Tratcher** [comment]
Yeah, it looks like those characters are coming in from your config file. You should be able to verify that by inspecting _redirectUri. E.g. calling Uri.EscapeDataString(_redirectUri) should make those characters more visible.

As to why it only happens sometimes, I wonder if it only happens when the file is edited by a specific user / machine with international settings.

**Comment by muratg** [comment]
@Praveen-911 closing this one as it looks like a problem with your side (e.g. someone editing the file.)  If you still have problems, please feel free to file another issue. Thanks.
