### ISSUE TITLE
Non form_post server response 

### ISSUE THREAD

**Issue by tstojecki** [aspnet/AspNetKatana#63]
I understand that by default this version of OIDC middleware (.net 4.5.1) assumes the response_mode is form post which has worked well for us with Azure. We are now being asked to integrate with another OIDC authorization server that supports hybrid flow, however the server's response to a hybrid flow OIDC request is always with a encoded url fragment. Per Dominic's post, this does appear to be a valid type of response in a hybrid flow:
https://leastprivilege.com/2014/10/10/openid-connect-hybrid-flow-and-identityserver-v3/

I have looked around but wasn't able to find anything that describes this type of response and how to handle it? Is there a way to support this type of response in OIDC middleware?

**Comment by Tratcher** [comment]
Fragments are for client apps, they are never transmitted to the server so there's nothing you can do to handle them in the middleware. You would use a client side SDK together with something like the OAuthBearer middleware instead.

**Comment by tstojecki** [comment]
Thanks @Tratcher 
Are you referring to anything specific for the client side SDK or just in general a js library that handles OIDC response?

**Comment by Tratcher** [comment]
I was referring to provider specific SDKs like ADAL:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries
