### ISSUE TITLE
OAuth authentication in Asp.Net MVC 4.5

### ISSUE THREAD

**Issue by imvigo** [aspnet/AspNetKatana#67]
Hi,
I have an ASP.NET MVC web application running on .NET Framework 4.5. I want my application to be able to use OAuth protocol of Linkedin to allow a user to authenticate into the application using Linkedin identity. 

I am not able to find any Owin module for implementing this. I could only find _app.UseOAuthAuthorizarionServer_ and _app.UseOAuthBearerAuthentication_. The first one is for implementing an authorization server and the second is for verifying the Bearer token present in the header in order to secure a service such as a Web API. There is another module app.UseOauthAuthentication, but that only works in ASP.NET Core project, and not ASP.NET 4.5.
**Is there any way using which I can get Linkedin OAuth flow to work in ASP.Net 4.5 project, or will I have to migrate my project to ASP.NET Core ?**

**Comment by Tratcher** [comment]
Have you looked at these?
https://github.com/TerribleDev/OwinOAuthProviders/tree/master/src
https://www.nuget.org/packages/Owin.Security.Providers.LinkedIn/

**Comment by imvigo** [comment]
Using these, I am not able to sign my assembly. It says these references are not strongly-named.

**Comment by Tratcher** [comment]
Your next best option is to clone that implementation into your project, licence permitting.
