### ISSUE TITLE
The MSDN API points to an empty page

### ISSUE THREAD

**Issue by davidshen84** [aspnet/AspNetKatana#68]
On the WIKI page, the MSDN links to a page with only the following line:

    The topics in this section describe the public namespaces, classes, and interfaces that support Microsoft OWIN components.

How can people learn the API from this sentence?

**Comment by Tratcher** [comment]
https://github.com/aspnet/AspNetKatana/wiki

@davidshen84 I updated it to point to this one instead:
https://msdn.microsoft.com/en-us/library/microsoft.owin(v=vs.113).aspx

@tdykstra any idea what happened to the content at this link?
https://msdn.microsoft.com/en-us/library/dn253840(v=vs.113).aspx

**Comment by tdykstra** [comment]
@Tratcher I don't know what happened to dn253840, but 
https://msdn.microsoft.com/en-us/library/mt152002(v=vs.113).aspx
looks like a closer match for it than
https://msdn.microsoft.com/en-us/library/microsoft.owin(v=vs.113).aspx

@Rick-Anderson do you know how to get the dn253840 URL to forward to mt152002?

**Comment by muratg** [comment]
*ping* @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@tdykstra  can you redirect dn253840 URL to forward to mt152002?

**Comment by tdykstra** [comment]
@Rick-Anderson - Ha, I asked you first :smiley: 
I'm not aware of a way to do that; I guess we'll have to open a sitehelp ticket.

**Comment by tdykstra** [comment]
[Work item](https://mseng.visualstudio.com/VSChina/_workitems?id=1016932) created.

**Comment by muratg** [comment]
Thanks @tdykstra and @Rick-Anderson.  Closing this one external.
