### ISSUE TITLE
DeleteCookie doesn't set HttpOnly and Secure flags

### ISSUE THREAD

**Issue by bbowyersmyth** [aspnet/AspNetKatana#69]
Picked up by automated security scanners (yes I know) that the cookie is missing these flags. Although not an actual problem I think these could pass on the options the same as when setting an actual value.

https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Host.SystemWeb/SystemWebCookieManager.cs#L132

**Comment by Tratcher** [comment]
We avoid making non-functional product changes as they can often have un-intended consequences.
