### ISSUE TITLE
Security Exception

### ISSUE THREAD

**Issue by ferronicardoso** [aspnet/AspNetKatana#73]
Hi Developers

I'm developing two projects, one ASP.NET MVC and one Web API, both using Framework 4.5.2, nothing different from what we traditionally used in our projects. These common projects use Owin and the public on a server where it is set up as Medium Trust, send the error below:

`Exception Details: System.Security.SecurityException: Request permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089' failed.`

```
[SecurityException: Request permission of type 'System.Security.Permissions.SecurityPermission, mscorlib, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b77a5c561934e089' failed.]
Microsoft.Owin.Host.SystemWeb.Infrastructure.DefaultTraceFactory.InitializeTraceSource (String) +0
System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd (TKey key, Func`2 valueFactory) +62
Microsoft.Owin.Host.SystemWeb.Infrastructure.DefaultTraceFactory.GetOrAddTraceSource (String name) +52
Microsoft.Owin.Host.SystemWeb.Infrastructure.DefaultTraceFactory.Create (String name) +28
Microsoft.Owin.Host.SystemWeb.OwinAppContext..ctor () +43
Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build (Action`1 startup) +30
Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint () +70
System.Threading.LazyInitializer.EnsureInitializedCore (T & target, Boolean & initialized, Object & syncLock, Func`1 valueFactory) +115
Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init (HttpApplication Context) +106
System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS (IntPtr appContext, HttpContext context, MethodInfo [] handlers) +534
System.Web.HttpApplication.InitSpecial (HttpApplicationState state, MethodInfo [] handlers, IntPtr appContext, HttpContext context) +172
System.Web.HttpApplicationFactory.GetSpecialApplicationInstance (intPtr appContext, HttpContext context) +339
System.Web.Hosting.PipelineRuntime.InitializeApplication (IntPtr appContext) +296
```

What I identified was at the same time, and use the **Microsoft.Owin.Host.SystemWeb** to hide this trust problem. What I know is also how libraries have the desired name The strong name and host on which an application is to run can not this type of configuration changed by company rules accounts (a company and a Locaweb).
I have already tried to download the source and recompile, including _System.Security.AllowPartiallyTrustedCallers_ but I have not yet succeeded.

Has anyone ever had the same problem and would know a way around it? Remembering that I can not have your Level Trust settings changed.

Thank you in advance!
Raphael Cardoso

**Comment by Tratcher** [comment]
Partial trust was deprecated years ago and is unsupported.

**Comment by MaximRouiller** [comment]
Reminds me of my SharePoint years.

Is the concept of full trust still supported? I know SharePoint used to make a big case out of it.

**Comment by Tratcher** [comment]
Full trust is the only supported mode.

**Comment by ferronicardoso** [comment]
So in my case, the host only only accepts _Medium Trust_ and **Microsoft.Owin.Host.SystemWeb** causes an Exception.

**Comment by MaximRouiller** [comment]
From Levi:
https://stackoverflow.com/questions/16849801/is-trying-to-develop-for-medium-trust-a-lost-cause

Quoted comment here: 

>We have provided guidance to hosters that they should migrate away from Medium Trust and use proper OS-level isolation instead (http://support.microsoft.com/kb/2698981).

And that was 4 years ago. I would, personally, reconsider my host if it can't keep up with Microsoft security guidance.

**Comment by ferronicardoso** [comment]
Well, now I get it. Microsoft recommends reviewing the appropriate insulation instead of using Medium Trust.

**Comment by MaximRouiller** [comment]
Medium trust wasn't doing what it was supposed to do. 

As it should have been from the start, we should rely on the security feature of the OS to allow or not certain operations. This is what the KB is basically saying. 

What your bug is telling me, is that your hoster is still using Medium Trust as a security feature which is completely wrong. Could you share the name please? Would love to avoid my clients from going there.

**Comment by ferronicardoso** [comment]
@MaximRouiller 

Yes, I can share the name. Since the company was one that always followed the recommendations of Microsoft and today still insisted on following the same restrictions. I opened a call with technical support to request the release (which I believe will not occur) to review this rule. If they do not release, I will consider the host switch.
The company is **Locaweb** (www.locaweb.com.br) and I'm considering migrating to another Host, in case I'm analyzing _GoDaddy_.

Thank you for the help and clarification you gave me. I was really out of the way.

**Comment by MaximRouiller** [comment]
@ferronicardoso 

If you are changing host, take the time to price and consider Azure. If you are hosting your clients, Elastic Pools allows you to share the load of multiple database over one pool of data with an easy migration path to a dedicated database.

Same thing can also be done with Multiple AppServices over Hosting Plan.

Can be a real cost saver.

**Comment by ferronicardoso** [comment]
Thanks, I'll evaluate your suggestion.
