### ISSUE TITLE
OpenIdConnectAuthenticationHandler uses incorrect order of parameters for string.format when an error has been received in an open id connect message

### ISSUE THREAD

**Issue by scrivuk** [aspnet/AspNetKatana#75]
Lines starting 252 of OpenIdConnectAuthenticationHandler.cs:
`throw new OpenIdConnectProtocolException(
      string.Format(CultureInfo.InvariantCulture,
                    openIdConnectMessage.Error,
                    Resources.Exception_OpenIdConnectMessageError, openIdConnectMessage.ErrorDescription ?? string.Empty, openIdConnectMessage.ErrorUri ?? string.Empty));`

The openIdConnectMessage.Error and Resources.Exception_OpenIDConnectMessageError are in the wrong order - [string.Format(IFormatProvider, string, object, object, object)](https://msdn.microsoft.com/en-us/library/dn906221(v=vs.110).aspx) defines the format string as the second parameter but in the code it is the third.

This results in a loss of a lot of information when the exception is thrown. For example all I receive is "unsupported_response_type" but the openIdConnectMessage.ErrorDescription contains a lot more information about the actual error returned by the IdP. 

I acknowledge you can use AuthenticationFailedNotification to get access to the full OpenIdConnectMessage object but it would be good for the initial error (if  you don't utilize the AuthenticationFailedNotification notification) to display the full information. 

This is obviously low priority.

**Comment by Tratcher** [comment]
Note this has been addressed in the ASP.NET Core version:
https://github.com/aspnet/Security/blob/879f0b7f4053a34b44e34bd22c788c6129115175/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L1214
