### ISSUE TITLE
Anti Forgery Token Issue with .Net 4.7

### ISSUE THREAD

**Issue by AdamDotNet** [aspnet/AspNetKatana#77]
See: IdentityServer/IdentityServer3/issues/3741

I know IdentityServer3 is built as an OWIN component, but I'm not terribly sure if this is the right place to ask this.

In short, the referenced issue is that after upgrading the *server* to .Net 4.7 (Windows Server 2012 R2, was .Net 4.6.2, up to 4.7, app is still compiled to .Net 4.6.2), the Anti Forgery token isn't being sent in the cookie header, specifically from the IE 11 embedded browser for WPF. The *client* was unchanged, but happened to be on a machine running .Net 4.7. Reverting the *server* to .Net 4.6.2, everything worked again. Full web browser log ins always worked, making things muddier.

The owner or the IdentityServer3 repo commented on the linked issue and wondered if it's something on Microsoft's end instead of Identity Server.

**Comment by Tratcher** [comment]
Katana (Microsoft.Owin) doesn't deal with Anti Forgery Tokens. You're likely having a problem with System.Web or MVC. @Eilon?

**Comment by AdamDotNet** [comment]
Well, thanks for trying to ping Eilon, but I guess he was too busy? I just hit this exact road block again, this time during development and I can't actually move forward on debugging what I need to unless I rebuild my VS environment in a virtual machine not running .Net 4.7... It's such a strange bug and I don't know who to turn to.

**Comment by AdamDotNet** [comment]
I found out it's definitely got to be System.Web or MVC. Refer to my comments in the linked issue in the original post. In short, Asp.Net 4.7 is only sending 1 of 2 anti forgery tokens, each with different names, instead of both like Asp.Net 4.6.x did. I'm not sure how to debug further into Asp.Net to see why this happens...

Anyway, I'll close this issue as it's definitely not Katana/Owin.

**Comment by CZEMacLeod** [comment]
@AdamDotNet Just curious if the Anti-Forgery tokens issue is related to the issues with Katana/OWIN cookies and System.Web cookies sometimes causing problems?
Slightly worried if we will have problems when 4.7 is installed on our servers. (Need to do some testing!)
