### ISSUE TITLE
Facebook and Google Middlewares not using ICookieManager for CSRF

### ISSUE THREAD

**Issue by rzontar** [aspnet/AspNetKatana#79]
Although the Middlewares provide the option to pass in a custom `ICookieManager` the implementation does not use the overloads of `GenerateCorrelationId` and `ValidateCorrelationId` which would receive an `ICookieManager` as the first parameter thereby ignoring the passed in option.

See Example:
https://github.com/aspnet/AspNetKatana/blob/release/src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs#L68

**Comment by Tratcher** [comment]
Fair point. Want to send a PR (to the dev branch)?

Luckily that's not the code path where we've had as many issues and needed the SystemWebCookieManager workaround.
