### ISSUE TITLE
Infinite loop after authentication using Microsoft.Owin.Security.WsFederation

### ISSUE THREAD

**Issue by marcosbg** [aspnet/AspNetKatana#82]
Authentication occurs correctly, when STS tries redirects to my application a infinite loop starts.

Looking at the requests, we figured out that the problem was caused by cookies' path using a diferent casing from the URL typed by user.

We noticed that the problem occurs when we use the version 3.0.1 or higher of the Microsoft.Owin.Host.SystemWeb.

With older versions the final redirect is made using the same casing of the parameter Realm of the WsFederation configuration,in newer versions this redirect is made using the casing of url typed in browser. Due to this the authentiction cookie isn't sent back to server causing the redirect to STS, the STS redirects back to client because the user is already authenticated, starting a infinite loop.

For us it's important to use a custom cookie Path because we are using Virtual Directories to host the applications in IIS in a SSO scenario.

We think that this behavior was caused by the commit "Servers: #349 - Preserve PathBase casing from client." (https://github.com/aspnet/AspNetKatana/commit/b9c00d5031e55ebcba6e249d4a3f694a0fbfa3f5)

Thanks in advance.

**Comment by Tratcher** [comment]
You're setting a custom CookieAuthenticationOptions.Path, correct?
https://github.com/aspnet/AspNetKatana/blob/ddefa9ec120ec40a039e4c03bd02b5b28afa6167/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationOptions.cs#L59
https://github.com/aspnet/AspNetKatana/blob/ddefa9ec120ec40a039e4c03bd02b5b28afa6167/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs#L142

You could hook into the OnResponseSignIn event and normalize the Path casing on CookieOptions:
https://github.com/aspnet/AspNetKatana/blob/ddefa9ec120ec40a039e4c03bd02b5b28afa6167/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs#L179
Or in the CookieManager:
https://github.com/aspnet/AspNetKatana/blob/ddefa9ec120ec40a039e4c03bd02b5b28afa6167/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs#L203

**Comment by marcosbg** [comment]
First of all, thank you for answering!

We implemented a custom Cookie Manager as you suggested and it got like this:

```
public void AppendResponseCookie(IOwinContext context, string key, string value, CookieOptions options)
	{
		…
	    if (pathHasValue)
	    {
	    	cookie.Path = options.Path.EndsWith("/")?options.Path:options.Path+"/";
	       	if (context.Response.StatusCode == 302) {
	        	Uri locationUri = new Uri(context.Response.Headers["Location"], UriKind.Absolute);
	            if (locationUri.AbsolutePath.StartsWith(cookie.Path, StringComparison.InvariantCultureIgnoreCase)) {
	            	cookie.Path = locationUri.AbsolutePath.Substring(0,cookie.Path.Length);
	            }
			}
	    }
		…
	}
```

Cookie's path changes as the user digits the URL, the code is under test.

**Comment by anurse** [comment]
Closing as we don't intend to change this behavior. The workaround of a custom cookie manager is what we would recommend here.
