### ISSUE TITLE
Should OAuthAuthorizationServerHandler directly change signin.Properties in ApplyResponseGrantAsync?

### ISSUE THREAD

**Issue by kinglywork** [aspnet/AspNetKatana#83]
Target assembly: Microsoft.Owin.Security.OAuth
Version Info: 3.0.1

In OAuthAuthorizationServerHandler.ApplyResponseGrantAsync, it directly change signin.Properties which is shared for each ClaimsIdentity in AuthenticationResponseGrant.Principal.Identities, should'nt it deep clone a new signin.Properties and use it.

The problem scenario will like this:
If I register AuthenticationMiddleware like this:

```
app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = AuthenticationTypes.ApplicationCookie,
                AuthenticationMode = Microsoft.Owin.Security.AuthenticationMode.Passive,
                LoginPath = new PathString(Paths.LoginPath),
                LogoutPath = new PathString(Paths.LogoutPath),
                ExpireTimeSpan = TimeSpan.FromDays(1),
            });
app.UseOAuthAuthorizationServer(OAuthConfig.CreateOption()); // ExpireTimeSpan will be 7 days
```

and SignIn these two types of Identity in controller like this:

```
AuthenticationManager.SignIn(bearerIdentity);
AuthenticationManager.SignIn(cookieAuthResult.Properties, cookieIdentity);
```

the cookie ExpireTimeSpan will be 7 days although I expected 1 day.

**Comment by anurse** [comment]
We don't plan to change this behavior.
