### ISSUE TITLE
OAuthBearerAuthenticationHandler does not respect ValidateLifetime from TokenValidationParameters

### ISSUE THREAD

**Issue by fpintos** [aspnet/AspNetKatana#86]
I'm trying to debug how an application handles a particular token, which happens to be expired.
In order to let it thru, I'm setting the TokenValidationParameters.ValidateLifetime to false in my debug session.

This allows the token to get past the validation in the token handler, but OAuthBearerAuthenticationHandler still fails saying the token is expired.

**Expected**: if lifetime validation is disabled, an expired token should be accepted by the middleware.

Example:
```csharp
var tokenValidationParameters = 
    new TokenValidationParameters
        {
            ...
#if DEBUG
            ValidateLifetime = false,
#endif
        };

app.UseWindowsAzureActiveDirectoryBearerAuthentication(
    new WindowsAzureActiveDirectoryBearerAuthenticationOptions
    {
        ...
        TokenValidationParameters = tokenValidationParameters
    });
```

The request that sends the expired token (for debug purposes) still fails by hitting these lines in `OAuthBearerAuthenticationHandler.AuthenticateCoreAsync`:
```csharp
// Validate expiration time if present
DateTimeOffset currentUtc = Options.SystemClock.UtcNow;

if (ticket.Properties.ExpiresUtc.HasValue &&
    ticket.Properties.ExpiresUtc.Value < currentUtc)
{
    _logger.WriteWarning("expired bearer token received");
    return null;
}
```

**Comment by fpintos** [comment]
I worked around this by having my own token handler and removing the 'exp' claim while debugging.

**Comment by Tratcher** [comment]
The way the layering works out OAuthBearerAuthenticationHandler doesn't know about TokenValidationParameters. At this point removing the expiration check is likely to break other providers. Removing the exp claim is a good debugging workaround.
