### ISSUE TITLE
Changing name of correlation cookie in security middleware

### ISSUE THREAD

**Issue by svhero658** [aspnet/AspNetKatana#87]
Cause the cookie name in Generate/ValidateCorrelationId method is hard coded, I found no way to change that in my application. Similarly there is a issue in aspcore for your reference: https://github.com/aspnet/Security/issues/1033

**Comment by Tratcher** [comment]
aspnet/Security#1033 was recently fixed for ASP.NET Core 2.0. There are not currently plans to backport the change.

**Comment by explunit** [comment]
In the meantime, one workaround is to wrap the oidc options `CookieManager` in your own `ICookieManager`

**Comment by svhero658** [comment]
@explunit The workaround I'm using is use a middleware to find and modify the corresponding cookie in and out.

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi MI 5 发送_

**Comment by anurse** [comment]
Closing as we don't intend to backport this functionality to Katana. Working around this by wrapping `ICookieManager` is a reasonable alternative.
