### ISSUE TITLE
OAuth flow across multiple machines

### ISSUE THREAD

**Issue by solankisamir** [aspnet/AspNetKatana#93]
We are using the `Microsoft.Owin.Security.AAD` to manage the Oauth flow for us. What we observed was when the request to authenticate at external login provider originates from one machine in Azure Cloud Service, but the callback from the external login provider lands on another machine, the login fails.

There are 3 calls in this Oauth dance which could land on different machines
1. Request to authenticate at external login provider. This gets a `state` token.
2. Callback from external login provider having `auth_code` and the above `state` token to the `CallbackPath` in the Owin Framework
3. Callback our ASP.NET Application, with Cookie containing the `access_code`.

Questions:
1. How can we make the `state` token generation and validation consistent across machines
2. How can we make the `cookie` generation and authentication consistent across machines.

Any samples?

**Comment by Tratcher** [comment]
The main issue here is the machine key that is used to encrypt both the state and auth cookie. Get that set on all the machines and you should be good to go.

**Comment by solankisamir** [comment]
We validated that the MachineKey in the Web.Config is same across machines.
<machineKey decryption="AES" decryptionKey="C995A.." validation="HMACSHA512" validationKey="B6A8..." />

Any other pointers?

**Comment by Tratcher** [comment]
Why does that say `</machinekey.../>`? Shouldn't it be `<machinekey... />`?
https://msdn.microsoft.com/en-us/library/w8h3skw9(v=vs.100).aspx

**Comment by solankisamir** [comment]
That is a typo in the comment. It is actually `< machinekey ... />`

**Comment by Tratcher** [comment]
It is keyed off the site id, are those consistent?
https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Host.SystemWeb/OwinAppContext.cs#L38
https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Security/DataProtection/AppBuilderExtensions.cs#L69

**Comment by solankisamir** [comment]
Yes, we checked, the SiteName-ApplicationId is consistent across machines.

**Comment by Tratcher** [comment]
My only other suggestion is to try manually encrypting and decrypting test content across the two machines via IAppBuilder.CreateDataProtector or DpapiDataProtectionProvider to see if your settings are being honored.
