### ISSUE TITLE
UseStageMarker

### ISSUE THREAD

**Issue by phatcher** [aspnet/AspNetKatana#97]
I know about using UseStageMarker to put OWIN middleware into the appropriate IIS pipeline stage,

What I'm wondering is does this give any architectural/performance benefit?

**Comment by Tratcher** [comment]
It's primarily about ordering, it's not intended as a performance feature. If you terminated the response early then you may see some small benefit, but I wouldn't count on it.

**Comment by phatcher** [comment]
Thanks, part of the reason I ask is sometimes from my profiler (Stackify) is reporting delay between the pipeline steps of up to 5 s, so I'm trying to minimise this - server's not even that heavily loaded ~50% RAM, ~60% CPU
