### ISSUE TITLE
OwinHost running from outside of project root

### ISSUE THREAD

**Issue by grofit** [aspnet/AspNetKatana#98]
I have noticed that in the source for OwinHost @ https://github.com/aspnet/AspNetKatana/blob/dev/src/OwinHost/Program.cs#L80

It has:

```
ResolveAssembliesFromDirectory(Path.Combine(Directory.GetCurrentDirectory(), "bin"));
```

So does this mean that you can ONLY use OwinHost when the CWD is the project? i.e if I was in a build script and my CWD was elsewhere it never seems to resolve assemblies correctly and it *seems* (only taken a quick look through) like it will always assume the current working directory is the project dir.

So am I wrong? and if not what is the purpose of the passed in argument `-d` as that implies it should be the directory to be used (assuming for assembly resolving), if `-d` means something different could an argument be added to support telling it where to resolve the assemblies from?

(On a side note here is the SO article which started my descent into madness)
https://stackoverflow.com/questions/45350198/telling-owinhost-on-command-line-how-to-load-a-owinsetup-class-with-cwd-outside

**Comment by Tratcher** [comment]
That directory param is used when setting up the app domain: https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Hosting/Starter/DomainHostingStarter.cs#L48

It should be able to resolve assemblies from that path. Are you setting -d to the project or bin directory? The line you quoted above was added to allow starting in the project directory rather than just the bin directory.

**Comment by grofit** [comment]
Hey, I have tried setting it to the project root (folder containing the `bin` dir) and to the `bin` dir itself, also tried going to `bin/Debug` too or manually specifying the specific dll that contains the owin startup class.

Just to make sure it is not me being an idiot could you just provide me a quick example of command line usage that should work when the cwd is not the project root? as on my internet travels I have not seen a single example of how it should look when doing this, every question alluding to this problem generally has the solution of *set cwd to project root*.

**Comment by Tratcher** [comment]
From the solution directory of WebApplication6:
`D:\temp\WebApplication6>packages\OwinHost.3.1.0\tools\OwinHost.exe -d .\WebApplication6\`
